### ISSUE TITLE
Requirement ID Uniqueness

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#100]
MB/NC: DK-014-032
Clause/Subclause: 5.7
Paragraph/Figure/Table: Para 1
Type of comment: Ed/te
Comments: In the text it stated that “Each requirements class, requirement and recommendation are identified by a unique identifier”. The way it can be read is that either the requirement class, each separate requirement and recommendation will each have their own unique ID or that they all share a unique ID. 
Proposed change: Please clarify in the text.

**Comment by sgrellet** [comment]
'are' ->'is'
