### ISSUE TITLE
Semantics of "phenomenon"

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#101]
MB/NC: DK-024-042
Clause/Subclause: 7.1.3
Paragraph/Figure/Table: Para 1
Type of comment: Te 
Comments: The definition of “phenomenon” is different from what can be found in ISO 19101-1:2014. The term phenomenon is not directly defined in ISO 19101-1, but as part of the term feature. The term feature is defined as “abstraction of real world phenomena. Note to entry: A feature may occur as a type or an instance. Feature type or feature instance shall be used when only one is meant.
Proposed change: Consider to harmonize with ISO 19101-1:2014, which act as a reference model for this series of standards.

KS: while 19101 uses the term phenomenon in the definition of the feature concept, phenomenon itself is never defined. Usage as follows:
```
4.1.11
feature
abstraction of real world phenomena
```

------------------------------------------

MB/NC: DK-025-043
Clause/Subclause: 7.1.3
Paragraph/Figure/Table: Para 1
Type of comment: Ed 
Comments: A little confusing wording.
Proposed change: Change to “An observation result is a value being assigned to a phenomenon”.

Related to #96

**Comment by sgrellet** [comment]
DK-024-042 : https://www.merriam-webster.com/dictionary/phenomenon

**Comment by rhaener** [comment]
An observation result is a value **### _being assigned to_** a phenomenon HAS

**Comment by KathiSchleidt** [comment]
Ori: An observation results in a value being assigned to a phenomenon. 
vs
Proposal: An observation result is a value being assigned to a phenomenon

SWG Proposal: An observation leads to a value being assigned to a phenomenon

**Comment by dr-shorthair** [comment]
Again I would suggest aligning with ISO 19109. Use 'property' and 'characteristics'. 
![image](https://user-images.githubusercontent.com/608303/105163356-ecf26600-5b67-11eb-8a6c-28b0235de49f.png)
![image](https://user-images.githubusercontent.com/608303/105163408-fd0a4580-5b67-11eb-8ef3-8e9b44eece14.png)
![image](https://user-images.githubusercontent.com/608303/105163472-0f847f00-5b68-11eb-96bc-8c00be6d0459.png)
![image](https://user-images.githubusercontent.com/608303/105163657-4c507600-5b68-11eb-9c06-f662ad7cf0d7.png)

**Comment by KathiSchleidt** [comment]
Change sentence from 
An observation results in a value being assigned to a phenomenon.
to 
An observation leads to a value being assigned to a phenomenon.

General discussion - removing the word phenomenon has major impact on the rest of the standards document (many reqs are impacted, also could require renaming phenomenonTime attribute (widely used)). Characteristic in common English is usually used for a static fact, whereas phenomenon is more commonly associated with events and dynamic changes

plural phenomena : an observable fact or event
https://www.merriam-webster.com/dictionary/phenomenon

UML: Investigate deriving the ObservableProperty from the metaclass PropertyType from the General Feature Model (not an official comment)
See Diagram Context Diagram: 19109 Phenomenon - ValueAssignment

**Comment by KathiSchleidt** [comment]
Suggestion:
An observation leads to a value being assigned to a phenomenon pertaining _to a feature_.

**Comment by KathiSchleidt** [comment]
Note: would then make sense to modify the following sentence from 
The phenomenon is a property of a feature, the latter being the feature-of-interest of the observation.
to
The phenomenon is a property of **the** feature, the latter being the feature-of-interest of the observation.

**Comment by sgrellet** [comment]
An observation leads to a value being assigned to a **characteristic** pertaining to a feature.

**Comment by KathiSchleidt** [comment]
Rethinking this, and seeing how few mentions there are of the word phenomenon in the text, think it's worth the reduced confusion to replace phenomenon to characteristic throughout the document
Exceptions:
- phenomenonTime
- /req/sam-cpt/Sampling/featureOfInterest-sem: The concept, real-world object or phenomenon   (feature-of-interest) the Sample(s) of the Sampling represent.

**Comment by sgrellet** [comment]
proposal for phenomenonTime definition adjustment (leaving the property name untouched) : (/req/obs-cpt/Observation/phenomenonTime-sem) : The time that the Result applies to _the characteristic of_ the FeatureOfInterest _being observed_

which is coherent with V2 (19156:2011) def : The attribute phenomenonTime:TM_Object shall describe the time that the result (7.2.2.9) applies to _the property of_ the feature-of-interest (7.2.2.7).

**Comment by KathiSchleidt** [comment]
Done, including Sylvain's addition on /req/obs-cpt/Observation/phenomenonTime-sem
