### ISSUE TITLE
Association Role to ObservingProcedure

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#104]
MB/NC: AU06-032-050
Clause/Subclause: 7.3.1
Paragraph/Figure/Table: Figure 5
Type of comment: Te 
Comments: observingProcedure role no longer exists
Proposed change: Split ‘observer’ and ‘procedure’ in the diagram

KS: to my view, the error is elsewhere (in the model) - all association roles to ObservingProcedure are named observingProcedure, except for the association from Observation, there its just procedure. Believe this is an artifact of the procedure class definition (started with simple procedure, then specialized when we hit Sampling, didn't fully fix in Observation)

**Comment by sgrellet** [comment]
Typo in propagating change in the model for the association role name.
Still we need to enrich the 'Scale:Observer' description.

**Comment by KathiSchleidt** [comment]
https://www.coventryscale.co.uk/scale-type/pallet-scales/

**Comment by KathiSchleidt** [comment]
add intermediate diagram without observer/host

**Comment by sgrellet** [comment]
question : what about enriching the instance diagram with images. We did that for some INSPIRE specs (with instance diagrams) and add very good feedback on this

**Comment by KathiSchleidt** [comment]
Summary:
fix association name from procedure to observingProcedure
Add diagrams as described above
