### ISSUE TITLE
Semantics of validTime

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#105]
MB/NC: DK-035
Clause/Subclause: 8.2.5
Paragraph/Figure/Table: 
Type of comment: Te 
Comments: It is not clear what exactly the meaning is of ”valid time”. It is   currently defined as the ”time period during which the result is valid”. What   exactly is meant by valid in this context?   Note that the term ”valid time” is used in the computer science domain,   see https://link.springer.com/referenceworkentry/10.1007/978-1-4614-8265-9_1066   and ISO 19108.   Is this the same concept? Or a different concept?
Proposed change: Clarify the   meaning of “valid time”. Additional notes and perhaps an example would be   useful.

**Comment by lvdbrink** [comment]
As far as I understand it, "valid time" is relevant for statistical models, simulations etc. The most obvious example being weather predictions. These models have a given "shelf life" i.e. period in which they are valid.

**Comment by sgrellet** [comment]
I always used it as described by @lvdbrink

**Comment by KathiSchleidt** [comment]
**Geolexica / 19108 :** 
source Jensen et al. , (1994)
eng valid time 
time when a fact is true in the abstracted reality
ORIGIN: ISO/TC 211 Glossary of Terms - English (last updated: 2020-06-02)

**Springer**
Definition
The valid time of a fact is the time when the fact is true in the modeled reality. Any subset of the time domain may be associated with a fact as its valid time. Thus, valid timestamps may be sets of time instants and time intervals, with single instants and intervals being important special cases. Valid times are usually supplied by users.

**Comment by KathiSchleidt** [comment]
Based on the definitions from ISO and Springer, our definition is correct. We prefer not to further constrain the validity concept here in order to allow for flexibility across domains.

**Comment by KathiSchleidt** [comment]
If additional information on the nature of validity is required, this can be provided via the standard in various methods, e.g. observation parameter, process
Dependent on the explicit use case.

**Comment by heidivanparys** [comment]
> Based on the definitions from ISO and Springer, our definition is correct.

I think the definition could be perceived as being circular:

**valid** time = time period during which the result is **valid**

"time period" is probably not a term that will cause confusion, but "valid" may need some explanation, and "valid" is used in the term and in the definition, therefore circularity.

How about one of the following:
valid time = time period during which the result is true in the modeled reality
valid time = time period during which the result is true in the reality
valid time = time period during which the result is in agreement with the reality

**Comment by dr-shorthair** [comment]
'time interval' is a better match to ISO 19108

**Comment by cportele** [comment]
> 'time interval' is a better match to ISO 19108

Actually, the type in ISO 19108 is called `TM_Period`, but period and interval are both used in 19108. I prefer time interval, too, this is what is more commonly used, e.g., in ISO 8601 or OWL Time.

**Comment by hylkevds** [comment]
Ah, the semantic confusion between period, interval and duration.
What ISO_8601 calls a duration ANSI SQL calls an interval...
And the ISO_8601 duration encoding starts with a P...??

**Comment by heidivanparys** [comment]
> "time period" is probably not a term that will cause confusion

I couldn't be more wrong 😄.

I agree with the comments above, that "time interval" should be used. It is, as mentioned before, used in [ISO 8601](https://www.iso.org/obp/ui#iso:std:iso:8601:-1:ed-1:v1:en:term:3.1.1.5), it is also used in the [Date-Time Vocabulary of the Object Management Group](https://www.omg.org/spec/DTV/1.3/), and it is in line with the mathematical concept "[interval](https://mathworld.wolfram.com/Interval.html)".

And [1] (a previous version of some entries in [2]) also recommends "time interval" in non-SQL-related scientific work. It seems that SQL is the exception.

> **time interval**
> Definition 1:
> A time interval is a convex subset of the time domain. A time interval may be open or closed (at either
> end) and can be defined unambiguously by its two delimiting time instants. In a system that models
> the time domain using granules, an interval may be represented by a set of contiguous granules. See
> the definition of time period.
> Definition 2:
> An interval is a directed duration of time. A duration is an amount of time with known length, but no
> specific starting or ending instants. For example, the duration “one week” is known to have a length of
> seven days, but can refer to any block of seven consecutive days. An interval is either positive, denoting
> forward motion of time, or negative, denoting backwards motion in time.
>
> Unfortunately, the term “time interval” is being used in the literature with two distinct meanings: as the time
> between two instants, in the general database research literature and beyond, and as a directed duration of time,
> in the SQL database language. The term “time period” is associated with the first definition above.
> Definition 1 is recommended for non-SQL-related scientific work. Definition 2 is recommended for SQL-related
> work.

[1] JENSEN, Christian S. and SNODGRASS, Richard T., eds. TR-90, _Temporal Database Entries for the Springer Encyclopedia of Database Systems_. Technical Report. TimeCenter, 22 May 2008. Available from: http://timecenter.cs.aau.dk/TimeCenterPublications/TR-90.pdf
[2] LIU, Ling and ÖZSU, M. Tamer, eds. _Encyclopedia of Database Systems_. 2nd ed. New York : Springer, New York, NY, 2018. ISBN 978-1-4614-8265-9. Available from: https://doi.org/10.1007/978-1-4614-8265-9

**Comment by KathiSchleidt** [comment]
valid time = time interval during which the result is assumed to be in agreement with the reality

**Comment by ilkkarinne** [comment]
Related note: the type of the validTime attribute is currently TM_Object both in the Observation interface (Conceptual Observation schema package) and in AbstractObservationCharacteristics class, thus allows for both TM_Period and TM_Instant to used. In the O&M v2.0 validTime was of type TM_Period.

I cannot remember the reason why we decided to support time instants (or any other possible TM_Object specialization) as validTime, and keeping it as TM_Period would probably create less issues with the implementations and migration.

**Comment by KathiSchleidt** [comment]
To my memory, we couldn't find a good reason to rule validTime instants out, thus decided to leave this flexibility in the model. As we have no requests to change (only to clarify the text of the definition), and do have enough work with the comments we do have, I'd prefer not to reopen this issue.

Turning it around - what dangers do you see ensuing from this flexibility?

**Comment by ilkkarinne** [comment]
@KathiSchleidt in theory adding flexibility should not hurt, but it is yet another change in the model that all software implementers, application schema  and data migrators have to deal with.

From the GML implementation based application coder's perspective changing the ```TM_Period``` into ```TM_Object``` means that the containing XML element for validTime (via the intermediate property type) changes from ```gml:TimePeriod``` to ```gml:AbstractTimeObject```, which is also typically reflected into software libraries for prosessing the data. This in turn means that the where software for v2.0 could rely on the library to contain a method ```Observation.getValidTime():TimePeriod``` they now would have ```Observation.getValidTime():AbstractTimeObject``` the result of which they would have to separately tested for actually being of type ```TimePeriod```.

If we do not have any foreseen use case for this change, I would prefer to revert it.

**Comment by KathiSchleidt** [comment]
Guess this is the downside of the lack of split between conceptual and implementation models.

- From a conceptual level, I'd leave TM_Object
- If we're interpreting the model as a logical or physical model, should probably go for TM_Period

**Comment by ilkkarinne** [comment]
@KathiSchleidt: to me it's exactly opposite: we have defined validTime as "The time period during which the result is valid" (/req/obs-cpt/Observation/validTime-sem), thus _conceptually_ it's always a period, although in an implementation model this period may sometimes be so short that it's precise enough to express it as an instant of time (interpreted as a short period around that instant).

**Comment by alexrobin** [comment]
@KathiSchleidt I also don't see how conceptually the `validTime` could be a single instant. That would mean the result value can only be used for an infinitesimal amount of time, which makes it pretty useless.

I agree with Ikka that conceptually it is always a period although it could be implemented as an time instant with a (maybe implied) tolerance. I think to increase interoperability we should discourage the latter.

However, perhaps one thing that could be useful at the implementation level is allow setting `validTime` relative to `resultTime` (e.g. as in "result is valid for 24h after it is issued"). This is a very common case for models and would allow setting `validTime` for an entire collection instead of each observation individually.

If it's not already the case, I think we should also have a constraint that `validTime` is always after `resultTime`. That would help clarifying the intent of this property.

**Comment by ilkkarinne** [comment]
Actually @alexrobin I do see an (edge) case where validTime could be before the resultTime: in meteorology and climate research the weather and oceanographic prediction models are also used to re-run previously happened situations to for example to validate the model. In this case the re-run time would become the resultTime, but the validTime might stay as-is

**Comment by alexrobin** [comment]
@ilkkarinne I think this is exactly the kind of use cases that cause confusion. In that case it's the `phenomenonTime` that stays the same, but I don't see how the result values can be valid before they even exist, so IMHO the `validTime` should be updated too.

**Comment by alexrobin** [comment]
@ilkkarinne But I see what you mean. As mentioned above, there are just several different possible interpretations of validTime, but the way it is defined now that's how I understand it.

**Comment by KathiSchleidt** [comment]
Adjust constraint from

`If validTime(s) are described they SHALL be provided by the attribute validTime:TM_Object`

to 

`If validTime(s) are described they SHALL be provided by the attribute validTime:TM_Period`

**Comment by KathiSchleidt** [comment]
valid time = time interval during which the result is assumed to be applicable for use.

**Comment by ilkkarinne** [comment]
Agreement to change from TM_Object to TM_Period

**Comment by alexrobin** [comment]
Interestingly, https://link.springer.com/referenceworkentry/10.1007/978-1-4614-8265-9_1066 defines `validTime` as "The valid time of a fact is the time when the fact is true in the modeled reality."

Am I wrong to think that this is more like our `phenomenonTime`?

**Comment by dr-shorthair** [comment]
Jeremy Tandy had a presentation to show 1bout 14 different kinds of time associated with ensemble weather forecasts. 
We chose to just implement 3 for general use.

**Comment by alexrobin** [comment]
@dr-shorthair Yes there are more and it's fine to implement only 3 but we do need to improve our definition of `validTime`.

Perhaps instead of just saying:
"time period during which the result is valid"

which is indeed kind of circular, we could say:
"time period during which the result value is a valid representation of the property value observed at the given phenomenon time"

**Comment by ilkkarinne** [comment]
The type of the ```validTime``` has now been changed in the HMMG cloud UML repo from ```TM_Object``` to ```TM_Period``` of ISO 19108 Ed. 1 both in ```Conceptual Observation schema:Observation``` interface and in ```Abstract Observation core:AbstractObservationCharacteristics``` class as agreed.

**Comment by ilkkarinne** [comment]
I like the new definition proposal provided by @alexrobin. Taking into account the "time period" vs. "time interval" discussion above, I would propose "time interval during which the **result** value is considered to be a truthful representation of the value of the **observedProperty** of the **featureOfInterest** at the given **phenomenonTime**"

**Comment by alexrobin** [comment]
@ilkkarinne Perhaps we could even mention that any information provided by `resultQuality` is only guaranteed to hold during that `validTime` interval.

**Comment by ilkkarinne** [comment]
@alexrobin: I would not explicitly link the resultQuality to validTime. Meteorology case again: the validTime for a periodically created weather forecast is set to until the expected resultTime of the next forecast (say 3 hours from the resultTime). The same quality evaluation procedure is done for each result (say "good" / "suspicious" / "error"), and recorded as the resultQuality. The resultQuality would still be as "guaranteed" to be good after the validTime as it was during the validTime.

Also: the resultQuality attribute is not included in the Observation interface of the Conceptual Observation schema package, thus it would be difficult to refer to it from a requirement contained in the requirements class of that package.

**Comment by heidivanparys** [comment]
FYI: [Martin Fowler](https://en.wikipedia.org/wiki/Martin_Fowler_(software_engineer)) recently published an article on [bitemporal history](https://martinfowler.com/articles/bitemporal-history.html), thus on valid time and transaction time (or actual time and record time as he calls them, see also footnote, but the concepts are exactly the same, just different terms). Perhaps what is written there may help in clarifying "valid time" in the context of O&M.

**Comment by ilkkarinne** [comment]
Thanks @heidivanparys. If I interpret Fowler's text correctly, he's "two dimensions" of time are O&M ```phenomenonTime``` (at which time observed result represents the observed property) and ```resultTime``` (at which time the observation was recorded). A later Observation (by resultTime) of the same observed property regarding the same phenomenon time may yield a different result as the information available for capturing is different. The ```validTime``` has always been s slightly difficult concept for me as it seems to be  (a) challenging to reliably provide at the recording time of the Observation and (b) highly depending on the use case for the Observation data.

**Comment by alexrobin** [comment]
@ilkkarinne I think you're right that linking `validTime` directly to the `resultQuality` property is properly not desirable. However, i feel that there is always/often some kind of link between result quality/accuracy and `validTime`? 

In the example you provide, it seems to me that the whole reason why there is a `validTime` attached to a weather forecast is because a run executed at a later `resultTime` is supposed to be a more "accurate" estimate of the atmospheric state that the result of the previous run. That's because the uncertainty of the model increases with `phenomenonTime` going farther from the `resultTime`. So, at least for this use case, isn't the intent of `validTime` to guide the user to pick the result/run that is most accurate?

The question is: is it always the intent of `validTime`? In other words, is `validTime` always used to hint that there may be some other/better estimate of the property value for the same `phenomenonTime`?

**Comment by ilkkarinne** [comment]
@alexrobin: the typical cases for using ```validTime``` I have seen indeed use it as an exclusion criteria for choosing Observation instances: Only the ones within their validTime interval are even considered as useful inputs for a particular process. This is also the danger I see with using providing validTimes: If the user does not know which data use case the provider of the Observation had in mind when providing the validTime, they may unintentionally miss some Observations that may have been useful for their different use case.

**Comment by alexrobin** [comment]
@ilkkarinne Indeed, as you allude to, IMHO observations are never completely "invalid". It just depends on your use case. That's why we should try to come up with a more specific definition of `validTime`, so less is up for interpretation and it's used in a more consistent manner. Ideally `validTime` does not depend on how the data is used downstream but rather depends solely on how the result is produced (i.e. the observing procedure).

It seems to me that it is usually used to mean "use this observation result within this `validTime` interval for optimum accuracy. If you're outside of the time interval, there may be other results that provide better accuracy".

If that's the case, perhaps we could refine the definition further to say: "time interval during which the **result** value is considered to be the best possible representation/estimate of the value of the **observedProperty** of the **featureOfInterest** at the given **phenomenonTime**, from this particular **Observer**".

But what a mouthful! :smile:

**Comment by KathiSchleidt** [comment]
Dear all, while I appreciate the creativity in this thread, I'm getting a bit worried :(

The way that phenomenonTime is now being integrated to the validTime definition seems to preclude modelling, though the sentence has become so obfuscated that I really can't tell!!

Also - if we overly extend the validTime definition, we should probably (NOT! ;) ) do the same with the others, e.g. Observation-sem:

An observation is an act carried out by an entity deemed as the **Observer**, potentially deployed at a **Host** during the temporal interval during with this act is performed, to determine the best possible representation/estimate of value of an **ObservableProperty** of an object (**featureOfInterest**) at the given **phenomenonTime** by using a **Procedure**; the best possible representation/estimate of the value is provided as the **result**. 

I do NOT think that this will increase understandability!

;)

**Comment by alexrobin** [comment]
@KathiSchleidt I agree but I also think we ought to do better than stating the obvious "validTime is when the observation is valid" ;)

**Comment by dr-shorthair** [comment]
ValidTime was introduced particularly to support modeling. 
It is the time period during which the data provider says the result should be used as the preferred value for the property at the designated phenomenon-time. The value for that phenomenon-time might be changed later, when more information becomes available. 

Phenomenon-time and result-time should always be present (their values may be the same). Valid-time is only useful in some scenarios.

**Comment by ilkkarinne** [comment]
I also agree with @KathiSchleidt that we are sliding into a too complex definition. At this stage of the specification drafting we must only attempt the simplest fix to what's actually broken. To me the issue to fix is the circularity of the current definition.

Another attempt to capture the essence of the concept based on this discussion:

"time interval during which the result is considered by the data provider to be the preferred estimate of observedProperty value at the given phenomenonTime"

**Comment by KathiSchleidt** [comment]
@alexrobin @ilkkarinne  The agreement we had had before this discussion was reopened was:

`The time interval during which the result is assumed to be applicable for use.`

I don't think that any of the options that have been discussed since make this any more understandable, thus would propose reverting back to our original agreement

**Comment by alexrobin** [comment]
@KathiSchleidt I would say if you keep the definition so wide open, at least make it clear in the spec that the exact meaning of `validTime` should be further specified by the application.

But if the intent of this property was indeed mostly to support model data, then why not write the definition in that sense?

**Comment by KathiSchleidt** [comment]
@alexrobin if you'd like a recommendation on how the application should further specify the semantics of validTime within the application context, please propose such a recommendation.

To the (to my view overly complex and obfuscating) proposals for validTime definitions, if you add the **Observer**, you should probably also add the **ObservingProcedure** (maybe more if you want to be totally complete) - however, then we should probably rework ALL definitions to always include the entirety of impacted classes, opening the door for potential inconsistencies (I'd really like to avoid revisiting ALL definitions), making the standard ever harder to understand, while breaking existing usages.

I personally find "applicable for use" clear in all contexts, "the most truthful representation of the value of the observedProperty available from the Observer." becomes pseudo-explicit, "the most truthful representation" seems like fairly stilted English, the observedProperty is already implicit in the Observation, the Observer just continues the spaghetti...

**Comment by alexrobin** [comment]
@KathiSchleidt It's always the same question: applicable for what use?

In the forecast model example where `validTime` is typically used, if I want to compare several model runs I would always use observations outside of their `validTime` interval although they are "applicable for my use".

So I don't understand how this definition is an improvement upon the original definition (expect perhaps that "applicable" has a little softer connotation than "valid").

All I'm trying to do is help come up with a definition that is independent from any intended use.

**Comment by ilkkarinne** [comment]
Agreed in SWG on 12th May: definition: The time interval during which the result is assumed to be applicable for use

**Comment by sgrellet** [comment]
working on the DIS docx. Definition propertly propagated to /req/obs-cpt/Observation/validTime-sem 
But why is '/req/obs-cpt/Observation/validTime-sem' both 

- in 8.2.1	Observation Requirements Class  '/req/obs-cpt/Observation' 
- and in 9.2.1	AbstractObservationCharacteristics Requirements Class '/req/obs-core/AbstractObservationCharacteristics

**Comment by KathiSchleidt** [comment]
The validTime (and most of the other) reqs are directly included in both Observation and ObservationCharacteristics requirements classes individually, as Observation and ObservationCharacteristics have different base semantics:

- /req/obs-cpt/Observation/Observation-sem
- /req/obs-core/AbstractObservationCharacteristics/AbstractObservationCharacteristics-sem

**Comment by sgrellet** [comment]
my bad, got lost cross-checking.
