### ISSUE TITLE
Abstraction Requirements Glitch

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#106]
MB/NC: DK-036
Clause/Subclause: 8.3.2
Paragraph/Figure/Table: Req 
Type of comment: Ed 
Comments: In the requirement   it is stated that “the feature of interest that may….”. According to the ISO   Directive Part 2 table 3 the word may should be a shall. 
Proposed change: Change   the wording to “An observable quality (property, characteristic) of the feature   of interest that shall be observed”

------------------------------------------

MB/NC: DK-038
Clause/Subclause: 8.6.2
Paragraph/Figure/Table: Req 
Type of comment: Ed 
Comments: In the requirement   it is stated that “…entity that may generate….”. According to the ISO   Directive Part 2 table 3 the word may should be a shall.
Proposed change: Change   the wording to “An identifiable entity that shall generate Observations pertaining to an observableProperty   by implementing a Procedure

**Comment by KathiSchleidt** [comment]
MB/NC: DK-036 Requirement   /req/obs-cpt/ObservableProperty/ObservableProperty-sem: An observable   quality (property, characteristic) of the feature of interest that may be observed.

MB/NC: DK-038 Requirement   /req/obs-cpt/Observer/Observer-sem | An identifiable entity that may generate Observations pertaining to an observableProperty by implementing a Procedure.

Proposal: change may to can, takes us out of the normative triggers

**Comment by dr-shorthair** [comment]
Take care to align terminology with ISO 19109

**Comment by KathiSchleidt** [comment]
need to check again in light of today's Characteristics discussion on Semantics of "phenomenon" #101

**Comment by KathiSchleidt** [comment]
checked, is good

**Comment by KathiSchleidt** [comment]
"may" changed to "can" in:

- /req/obs-cpt/ObservableProperty/ObservableProperty-sem
- /req/obs-cpt/Observer/Observer-sem
