### ISSUE TITLE
Parameter NOTES to recommendation

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#107]
MB/NC: DK-039
Clause/Subclause: 9.2.4
Paragraph/Figure/Table: Note 1 and note 2
Type of comment: Ed/te
Comments: When reading note   1 and 2, and read the ISO Directive Part 2 Table 4, we become uncertain if   the content of the notes should be rephrased to recommendations.
Proposed change: Reconsinder if the   notes should be recommendations.

**Comment by KathiSchleidt** [comment]
NOTE		Disambiguation: Parameter should not be used instead of the procedure to describe the steps performed in order to determine the value of the ObservableProperty
NOTE		Parameter should NOT be utilized to provide information already contained in the model by existing attributes or associations.

Agreement to make recommendation

**Comment by dr-shorthair** [comment]
Parameter is a kludge. It is a soft-extension point. I would prefer to remove it. It is not needed in RDF because of the OWA (you can always add another property from any namespace) but UML and XML-Schema are not as easy to supplement without formal sub-classing :-(

**Comment by KathiSchleidt** [comment]
@dr-shorthair thanks for reminding us that we're stuck down here in the UML stone-age banging rocks together! However, as that's all they let us play with in OGC/ISO at present, fear its the best we can do with the rocks they give us ;)
