### ISSUE TITLE
Mapping to other concept vocabularies

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#109]
MB/NC: DK-042
Clause/Subclause: Annex B
Paragraph/Figure/Table: 
Type of comment: ge 
Comments: It could be useful to document the mappings in a machine-readable way,   e.g. by connecting the ISO/TC 211 concepts to the concepts used in other   domains (e.g. in Geolexica).
Proposed change: Get in touch with   TMG to see if this could be useful.

------------------------------------------

MB/NC: DK-043
Clause/Subclause: Annex B
Paragraph/Figure/Table: 
Type of comment: ge 
Comments: There are no references / sources available for the terms used in the   other domains. E.g. for B.3, a reference to the number of the term referred   to in [VIM3] would be useful, perhaps also the definitions used in those   other domains.   [VIM3]   JOINT COMMITTEE FOR GUIDES IN METROLOGY. International vocabulary of   metrology – Basic and general concepts and associated terms (VIM)   [online]. 3rd edition. Joint Committee for Guides in Metrology, 2012. JCGM   200:2012. Available from: https://www.bipm.org/utils/common/documents/jcgm/JCGM_200_2012.pdf 
Proposed change: Make the mapping   more detailed and add relevant sources. See also other Danish comments.

------------------------------------------

MB/NC: DK-044
Clause/Subclause: Annex B
Paragraph/Figure/Table: 
Type of comment: ge 
Comments: According to the title of the annex and according to B1, this is mapping   of terminology, but the contents of the tables suggest a data model mapping. 
Proposed change: Replace the data   model constructs with natural language. E.g. replace   “Observation::observedProperty” with “observed property”.   Note: make sure   that any terms are present in the diagrams illustrating the concepts and in   the “Terms and definitions”, see also the other Danish comments.

**Comment by KathiSchleidt** [comment]
Contact TMG on outlook for GeoLexica

**Comment by ilkkarinne** [comment]
Would be good to have the references to the domain terms, but most of them are as-is in the 19156:2011, and it's a lot of work to find and check the references

**Comment by KathiSchleidt** [comment]
DK-044 
change name of Annex B from
Common usage of O&M terminology
to
Common usage of O&M concepts

**Comment by KathiSchleidt** [comment]
We would welcome danish support in this work!

**Comment by sgrellet** [comment]
That could be the topic of a paper

**Comment by KathiSchleidt** [comment]
Categorized in principle as our solutions differ from the proposed

**Comment by sgrellet** [comment]
Moving to implemented especially regarding DK-044. And as think other actions do cover DK-042 and DK-043
