### ISSUE TITLE
Modify Heading

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#11]
Pertaining to clause 07.01.06, it is not evident to us that this should be a clause. To me it looks like a NOTE
If we are wrong about this, we think a rephrased title of “Measurements vs. Observations” would be more to the point

KS: I'd be for the title modification

Source: TC211 Comments DK019

**Comment by KathiSchleidt** [comment]
Section text:

> In conventional measurement theory (e.g.[1], [5], [7], [8], [16]) the term “measurement” is used. However, a distinction between measurement and category-observation has been adopted in more recent work ([2], [9], [18]) so the term “observation” is used here for the general concept. “Measurement” may be reserved for cases where the result is a numeric quantity. 

Current Heading: "Measurements"

Proposal: Change to "Measurements vs. Observations"

**Comment by ilkkarinne** [comment]
Agreed to close in 18th Dec SWG meeting
