### ISSUE TITLE
Relationship to 19123 Coverage

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#110]
**MB/NC:** FR-2-046
**Clause/Subclause**: Coverage   / ISO 19123 and O&M
**Paragraph/Figure/Table**: 
**Type of comment:** ge 
**Comments**: What is the relation between ISO 19156 (O&M) and   ISO 19123 (Coverage). Are ISO 19123 and ISO 19123-2 normative references?   Coverage is not included in O&M data model and 6.2 UML package structure   and its Figure 3 — External UML package dependencies.   
It seems ISO 19123 is used normatively in Section 3,   7.1.5 and 8.2.8 when Observation result is a Coverage, and informatively in   Annex D.   
Therefore shouldn't 6.2 UML package structure and its   Figure 3 — External UML package dependencies reflect the relation with ISO   19123 - Coverage?   Note: In ISO 19156:2011, there was a   CoverageObservation class in addition to Geometry and Temporal Observations,   which is no longer included in the model.    Annex C does not provide any guidance for backward   compatibility / alignment with ISO 19156:2011 for CoverageObservation
**Proposed change:** 1. Probably ISO 19123 is to be considered as   normative, and ISO 19123-2 is only a bibliographic reference (to be   discussed)   2. Consider clarifying this relation and normative   use of Coverage, if included in ISO 19156.   3. Consider (if considered as of interest) to clarify   backward compatibility for ObservationCoverage.

**Comment by ilkkarinne** [comment]
There is no mention to the ISO coverage standard (19123) version(s) in the 19156:2020 normative content, thus no normative reference is required. However, the migration path for CoverageObservation of v2.0 to soft-typed coverage-valued result in v3.0 should be included as informative content in Annex C and D).

In the current spec we have under Normative references:

> ISO 19123-1:20xx, Geographic information — Schema for coverage geometry and functions — Part 1:
Fundamentals1
ISO 19123-2:2018, Geographic information — Schema for coverage geometry and functions — Part 2:
Coverage implementation schema

Take these away, move to Bibliography?

**Comment by KathiSchleidt** [comment]
In D.4, change references to CIS to ISO 19123-1

**Comment by cportele** [comment]
See [this comment](https://github.com/opengeospatial/om-swg/issues/95#issuecomment-763468175) in #95, where we agreed to move both 19123-1 and 19123-2 to the bibliography (no normative dependency, but both standards are background in informative parts).

**Comment by KathiSchleidt** [comment]
Add a note to annex C (both sections) after the table stating that we have shifted to soft typing, the specialized observations are no longer covered in the standard, up to domain users.

**Comment by KathiSchleidt** [comment]
Summary:

- move both 19123-1 and 19123-2 to the bibliography
- Add a note to annex C (both sections) after the table stating that we have shifted to soft typing, the specialized observations are no longer covered in the standard, up to domain users.
- In D.4, change references to CIS to ISO 19123-1

**Comment by KathiSchleidt** [comment]
In order to keep D.4 readable, I've gone a different route - mentioned ISO 19123-1 as ISO version of OGC Coverage Implementation Schema - and added (CIS) at the end
Then just refer to CIS
Otherwise, should probably also remove all references of O&M, also change to ISO, then the text becomes very unreadable!

**Comment by KathiSchleidt** [comment]
Notes in Annex C:

- NOTE: due to the shift to soft-typing, the specialized Observation Types are no longer provided within the standard.
- NOTE: due to the shift to soft-typing, the specialized Sample Types are no longer provided within the standard.

Food for thought - we do have specialized sample types - ah...?

**Comment by sgrellet** [comment]
Regarding the reference to 19123. In the CD, we had '19123:20xx with footnote ‘to be published’. 
Is that still the case or can we point more precisely to it.

**Comment by sgrellet** [comment]
Shouldn't we list the deprecated specialized Observation Types in "C.9	Discarded concepts" ?

**Comment by sgrellet** [comment]
Sorry for my latency on this but : could we keep the tables (maybe with slight adjustment if needed) at the end of section C.
The new explanatory text explains the rationale for change and that's good but, I've checked with colleagues here and people will also need a quick look-up table 
Idea : in the table we could (now) point to the relevant chapter for detailled explanation

**Comment by KathiSchleidt** [comment]
19123:20xx - unfortunately still in review, running almost parallel to us :( 

I checked against 19123-1:2005, but quite a few of the association roles are different than in the new version so we can't reference this. But, as 19123-2:2018 (Encoding) has all the structural elements I refer to in the text, would propose deleting the reference to 10123-1

**Comment by KathiSchleidt** [comment]
To Annex C (not really part of this thread), I'd also really like to see the tables back in the doc!

While the updated version is very explicit, I struggle to find anything (get lost in the mass of text). Example bit I find hard to understand in the new version - how do proximate and ultimate FoI map back to V1? In the tables clear that both map back to the original FoI, in the new version have to search

**Comment by KathiSchleidt** [comment]
final decision by Mats was "ISO/DIS 19123-1", no year. ISO secretariat will sort closer to publication when both standards have a clear year
