### ISSUE TITLE
Make available on OGC Site & Annex C

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#111]
**MB/NC:** FR-1-047
**Clause/Subclause**: Introduction 
**Paragraph/Figure/Table**: Last sentence
**Type of comment**: ed 
**Comments:** The technical note is not (yet) available on   http://www.opengeospatial.org/standards/om
**Proposed change:** Ensure   this note is made available or adjust the text

**Comment by KathiSchleidt** [comment]
Add info on:
split of procedure into procedure and observer
specialized observations no longer there, soft typing
additional types

**Comment by ilkkarinne** [comment]
Change the sentence to point to the Annex C.
Emmanuel: must include comprehensive backward-mapping from v2.0 to v3.0, general info on what has changed, TC 211 resolution adopted on this.

Annex C name change to "Backward-compatibility with the previous version"

**Comment by KathiSchleidt** [comment]
OGC3: 1/35 (first comment of total 35 comments).
1. Requirement: A technical note describing the changes from the earlier version is available from the Open Geospatial Consortium (see http://www.opengeospatial.org/standards/om).
2. Implementation Specification Section number: Introduction
3. Criticality: Editorial
4. Comments for changes: The technical note can not be found at the specified web location.

**Comment by KathiSchleidt** [comment]
Done the reference from the Intro and the change of title for Annex C (adopted the full name proposed by Ilkka in his text)

**Comment by sgrellet** [comment]
Works on different sections of the docx clash between Kathi & Me. 
AnnexBumping this to cross-checked and passing Annex C revision to Kathi
