### ISSUE TITLE
References to old ISO 19103 edition

### ISSUE THREAD

**Issue by jetgeo** [opengeospatial/om-swg#112]
The two attributes `name` and `value` in the data type `Abstract Observation core.NamedValue` are using the `Any` data type from the old ISO 19103 edition (`ISO/**TS** 19103 Edition 1`). They should refer to the new interface in `ISO 19103 Edition 1`.

**Comment by KathiSchleidt** [comment]
Are you referring to the written text or the UML model?
Pertaining to the references in the text, all updates listed here: https://github.com/opengeospatial/om-swg/issues/95

**Comment by jetgeo** [comment]
The error is in the UML model. The attributes need to have the correct data type from the most recent version of ISO 19103. 
This is part of the controls I do for the UML model between CD and DIS stages, referring to ISO/TC 211 [resolution 891](https://committee.iso.org/sites/tc211/home/resolutions.html#Resolution%20891)
The error is quite simple to fix, I would recommend to fix it now, rather than waiting. At least, it needs to be fixed before DIS ballot.

**Comment by KathiSchleidt** [comment]
Agreed!

**Comment by ilkkarinne** [comment]
I'm on it

**Comment by ilkkarinne** [comment]
Changed 
* ```NamedValue.name``` from ISO/TS 19103 Edition 1 ```GenericName``` to ISO 19103 Edition 1 ```GenericName``` and
* ```NamedValue.value``` from ISO/TS 19103 Edition 1 ```Any``` to ISO 19103 Edition 1 ```Any```

**Comment by sgrellet** [comment]
Checking the doc (not the UML)
- references are now to ISO 19103 Edition 1 and not ISO/TS 19103 Edition 1 anymore
- Figure 3 is correct in the reference.
Seems ok. 

Bumping to cross-checked
