### ISSUE TITLE
Missing definitions in the UML model

### ISSUE THREAD

**Issue by jetgeo** [opengeospatial/om-swg#113]
Definitions are addressed in other issues as well, but here's a complete list of all missing definitions for classes (elements), attributes and navigable association roles in the UML model. All elements, attributes and navigable association ends shall have definitions in the model. 

Missing element definition: Abstract Observation core.AbstractDeployment
Missing attribute definition: Abstract Observation core.AbstractDeployment.deploymentReason
Missing attribute definition: Abstract Observation core.AbstractDeployment.deploymentTime
Missing Navigable association role definition: Abstract Observation core.AbstractDeployment.observer
Missing element definition: Abstract Observation core.AbstractHost
Missing element definition: Abstract Observation core.AbstractObservableProperty
Missing Navigable association role definition: Abstract Observation core.AbstractObservableProperty.observer
Missing element definition: Abstract Observation core.AbstractObservation
Missing attribute definition: Abstract Observation core.AbstractObservationCharacteristics.observationType
Missing attribute definition: Abstract Observation core.AbstractObservationCharacteristics.parameter
Missing attribute definition: Abstract Observation core.AbstractObservationCharacteristics.phenomenonTime
Missing attribute definition: Abstract Observation core.AbstractObservationCharacteristics.resultTime
Missing attribute definition: Abstract Observation core.AbstractObservationCharacteristics.resultQuality
Missing attribute definition: Abstract Observation core.AbstractObservationCharacteristics.validTime
Missing Navigable association role definition: Abstract Observation core.AbstractObservationCharacteristics.observedProperty
Missing element definition: Abstract Observation core.AbstractObservationTypeCodeListValue
Missing element definition: Abstract Observation core.AbstractObserver
Missing element definition: Abstract Observation core.AbstractObservingProcedure
Missing element definition: Abstract Sample core.AbstractPreparationProcedure
Missing element definition: Abstract Sample core.AbstractPreparationStep
Missing attribute definition: Abstract Sample core.AbstractPreparationStep.description
Missing attribute definition: Abstract Sample core.AbstractPreparationStep.time
Missing element definition: Abstract Sample core.AbstractSample
Missing attribute definition: Abstract Sample core.AbstractSample.sampleType
Missing attribute definition: Abstract Sample core.AbstractSample.parameter
Missing element definition: Abstract Sample core.AbstractSampler
Missing attribute definition: Abstract Sample core.AbstractSampler.samplerType
Missing element definition: Abstract Sample core.AbstractSamplerTypeCodeListValue
Missing element definition: Abstract Sample core.AbstractSampleTypeCodeListValue
Missing element definition: Abstract Sample core.AbstractSampling
Missing attribute definition: Abstract Sample core.AbstractSampling.samplingLocation
Missing attribute definition: Abstract Sample core.AbstractSampling.time
Missing attribute definition: Abstract Sample core.AbstractSampling.parameter
Missing element definition: Abstract Sample core.AbstractSamplingProcedure
Missing element definition: Basic Observations.AbstractObservationCollectionTypeCodeListValue
Missing element definition: Basic Observations.Deployment
Missing attribute definition: Basic Observations.Deployment.link
Missing element definition: Basic Observations.GenericDomainFeature
Missing attribute definition: Basic Observations.GenericDomainFeature.link
Missing attribute definition: Basic Observations.GenericDomainFeature.location
Missing element definition: Basic Observations.Host
Missing attribute definition: Basic Observations.Host.link
Missing attribute definition: Basic Observations.Host.location
Missing element definition: Basic Observations.ObservableProperty
Missing attribute definition: Basic Observations.ObservableProperty.link
Missing element definition: Basic Observations.Observation
Missing element definition: Basic Observations.ObservationCharacteristics
Missing Navigable association role definition: Basic Observations.ObservationCharacteristics.collection
Missing element definition: Basic Observations.ObservationCollection
Missing attribute definition: Basic Observations.ObservationCollection.collectionType
Missing Navigable association role definition: Basic Observations.ObservationCollection.relatedCollection
Missing Navigable association role definition: Basic Observations.ObservationCollection.collection
Missing element definition: Basic Observations.Observer
Missing attribute definition: Basic Observations.Observer.link
Missing attribute definition: Basic Observations.Observer.location
Missing element definition: Basic Observations.ObservingCapability
Missing element definition: Basic Observations.ObservingProcedure
Missing attribute definition: Basic Observations.ObservingProcedure.link
Missing attribute definition: Basic Samples.MaterialSample.size
Missing attribute definition: Basic Samples.MaterialSample.storageLocation
Missing attribute definition: Basic Samples.MaterialSample.sourceLocation
Missing element definition: Basic Samples.NamedLocation
Missing attribute definition: Basic Samples.NamedLocation.name
Missing attribute definition: Basic Samples.NamedLocation.representativeGeometry
Missing attribute definition: Basic Samples.NamedLocation.address
Missing element definition: Basic Samples.PhysicalDimension
Missing attribute definition: Basic Samples.PhysicalDimension.dimension
Missing attribute definition: Basic Samples.PhysicalDimension.value
Missing element definition: Basic Samples.PreparationStep
Missing element definition: Basic Samples.Sample
Missing element definition: Basic Samples.SampleCollection
Missing Navigable association role definition: Basic Samples.SampleCollection.relatedCollection
Missing element definition: Basic Samples.Sampler
Missing element definition: Basic Samples.Sampling
Missing element definition: Basic Samples.SpatialSample
Missing attribute definition: Basic Samples.SpatialSample.shape
Missing attribute definition: Basic Samples.SpatialSample.horizontalPositionalAccuracy
Missing attribute definition: Basic Samples.SpatialSample.verticalPositionalAccuracy
Missing element definition: Basic Samples.StatisticalClassification
Missing attribute definition: Basic Samples.StatisticalClassification.concept
Missing attribute definition: Basic Samples.StatisticalClassification.classification
Missing element definition: Basic Samples.StatisticalSample
Missing attribute definition: Basic Samples.StatisticalSample.classification
Missing element definition: Codelist realizations.ObservationTypeByResultTypeCodeListValue
Missing element definition: Codelist realizations.SamplerClassificationCodeListValue
Missing element definition: SamplingCascade.W32564

**Comment by KathiSchleidt** [comment]
To my understanding, the UML is not normative, only informative. While we foresee adding the definitions to the UML, we're prefer to wait until the textual descriptions are finalized in the normative text to avoid inconsistencies
Also - while I'm assuming it's due to automated generation of the list above, you you really require a definition for a class defined soully for an informative instance diagram?

**Comment by jetgeo** [comment]
> To my understanding, the UML is not normative, only informative. While we foresee adding the definitions to the UML, we're prefer to wait until the textual descriptions are finalized in the normative text to avoid inconsistencies

The normative representation of the standard is the document. That is true.
However, ISO/TC 211, as well as OGC, is focusing strongly on model-driven architecture, which concerns not only resources for implementation, but also documentation. CityGML 3.0 and ISO 19170-1 are examples of standards where the document is derived directly from the UML model. The definitions need to be in the model for deriving implementation resources and documentation, and also for future revisions. For ISO/TC 211, the UML model is the original. 

I do these controls now as convenor of the ISO/TC 211 HMMG, referring to ISO/TC 211 [resolution 891](https://committee.iso.org/sites/tc211/home/resolutions.html#Resolution%20891).
It is up to the 19156 project to decide how to work with definitions, but my advice would be to have the original definitions in the model and then derive the documentation. No matter how you chose to maintain the definitions, they need to be in the UML model before the next ballot. 

>Also - while I'm assuming it's due to automated generation of the list above, you you really require a definition for a class defined soully for an informative instance diagram?

Yes, the list is generated by a script. I can understand that a definition may not be important for the class in question, but, on the other hand, it may be useful for anyone using the UML model later. It should be quite easy to write a simple definition that describes what the class represents.

**Comment by ilkkarinne** [comment]
Ok, agreed that we need the definitions UML model. Should/can we copy&paste them from the corresponding requirement statements in the specification? I'm a bit worried that we will get out-of-sync and produce new typos if the content cannot be 1-1 with the specification content.

**Comment by KathiSchleidt** [comment]
Reason I proposed not adding definitions to UML until they're finalized. Was the agreement the entire time we were modelling

**Comment by jetgeo** [comment]
Sorry, thought I had replied to Ilkka's question, but I must have forgotten to press "Comment" ;). 
It's up to the project to decide how to handle the definitions, as long as they are complete and identical in the document and in the UML model at the time of the ballot. 
If you decide to use definitions in the document as the original, you need to keep track of changes and update the UML model before the ballot. In that case, the list above can be seen as a reminder of definitions you need to check especially. Or you could maintain the original definitions in the UML model and export them for use in the document, which is the best way to make sure you are in sync.

**Comment by KathiSchleidt** [comment]
Are there any requirements to the formatting of the notes?
We'd recommend adding the requirement identifier to the text

**Comment by jetgeo** [comment]
The requirements from ISO 19013 are:
_Requirement 3. All normative class models shall contain definitions sufficient for understanding of all classes, attributes, associations, operations and appropriate data type definitions._  

_Requirement 3. All normative class models shall contain definitions sufficient for understanding of all classes, attributes, associations, operations and appropriate data type definitions._  

See also the UML Best Practices wiki: https://github.com/ISO-TC211/UML-Best-Practices/wiki/Definitions

Normally, an identifier will not be part of the definition. Could you provide an example?

**Comment by KathiSchleidt** [comment]
The definitions of the UML Classes, Associations... are all clearly linked with the requirements. 
Example


**Requirement**   /req/obs-cpt/gen/relatedObservation-sem | An Observation   the Observation is related to.   If a reference   to a related Observation is provided, the association with role relatedObservation   SHALL be used. The context:GenericName qualifier of this association   may be used to provide further information as to the nature of the relation.
-- | --

As there are cases where multiple requirements pertain to the same UML concept, I'd recommend adding the "/req/obs-cpt/gen/relatedObservation-sem" part

**Comment by dr-shorthair** [comment]
Suggest: 

Another Observation the context Observation is related to. If a reference to a related Observation is provided, the association with role relatedObservation SHALL be used. The context:GenericName qualifier of this association may be used to provide further information as to the nature of the relation.

**Comment by KathiSchleidt** [comment]
related to #86

**Comment by jetgeo** [comment]
Thanks, this is a good example. Sorry for the late reply.

I will claim that there is a difference between a definition that describes what a thing or a property is and a requirement that describes how it shall be used. 

- The first sentence in the example is the actual definition that explains what the association role "relatedObservation" is. I agree to @dr-shorthair 's suggested modification for that sentence, but should there be a "that" as well? "`Another Observation that the context Observation is related to`".
- The second sentence is not a description of what the role is. It is a requirement that specifies how the model shall be used, and that this particular role shall be used under specific circumstances: "`If a reference to a related Observation is provided, the association with role relatedObservation SHALL be used.`". In my view, this sentence alone should be the requirement, and not a part of the definition. On the other hand - is the requirement necessary? Is there any other way of providing a reference to a related observation?
- The role of the third sentence is less clear to me. It believe it may be an additional note to the definition: "`The context:GenericName qualifier may provide further information to the nature of the relation`", or it could be a recommendation as part of the recommendation: "`The context:GenericName qualifier SHOULD be used to provide further information to the nature of the relation`", depending on whether it is simply a possibility or a recommended use. As a note to the project team: The role classifisers (e.g., context:GenericName) are also classifiers and shall have definitions.

**Comment by jetgeo** [comment]
I am aware that you are still working on the definitions, but FYI, here's a list of missing definitions in the UML model from an automated control today. Please make sure the definitions for classes, attributes, enumeration values and navigable association ends are updated in the UML model before moving to the next ballot. 
[20210607 ISO 19156 Missing defintions.txt](https://github.com/opengeospatial/om-swg/files/6609361/20210607.ISO.19156.Missing.defintions.txt)

**Comment by ilkkarinne** [comment]
Populated the definitions from the [Word version of 17th June](https://github.com/opengeospatial/om-swg/blob/df727f3eabc3ec63c180c68f6361a8390e786be0/oms-abstract-spec/ogc-as-topic20/20-082r2_OGC_Abstract_Specification_Topic_20_-_Observations_and_measurements.docx) to the UML:

- Classes, attributes and associations for the package Conceptual Observation schema
- Classes and attributes for the  Conceptual Sample schema (associations TODO)

Still missing the rest of the packages

**Comment by ilkkarinne** [comment]
Populated the definitions from the [Word version of 27th July](https://github.com/opengeospatial/om-swg/blob/20db5bcd7ccaf5ec357a6e78da2a5a7bd8bd4b83/oms-abstract-spec/ogc-as-topic20/20-082r2_OGC_Abstract_Specification_Topic_20_-_Observations_and_measurements.docx) to the UML:

- Classes, attributes and associations for the package Abstract Observation core

**Comment by ilkkarinne** [comment]
Populated the definitions from the [Word version of 3rd Aug](https://github.com/opengeospatial/om-swg/blob/c2c4b44d7a404bb63362c3e76d78bc3a1cb7bf72/oms-abstract-spec/ogc-as-topic20/20-082r2_OGC_Abstract_Specification_Topic_20_-_Observations_and_measurements.docx) to the UML:

- Classes, attributes and associations for the package Abstract Sample core

**Comment by ilkkarinne** [comment]
Hi @jetgeo I've now gone through all the packages in the UML model and added the missing definitions based on the text in the specification. Could you run the check script once more to double-check that I have not not missed so of them?

We still need to work on a few of these in the spec and sync back to UML. To make the comparison easier it would  be great if you would have a script / XSL transformation available that would print out the definition texts of of classifiers in the model by package and class. I quickly tried to do something based on the XMI export of EA, but my XSL skills are too rusty

**Comment by jetgeo** [comment]
Hi @ilkkarinne 
Great work! I have run the script now, and there are only a few missing definitions left:
```
Missing role definition for Navigable association  in package "Abstract Observation core": AbstractObservationCharacteristics.observer (towards Observer)
Missing role definition for Navigable association  in package "Basic Samples": Sample.relatedObservation (towards AbstractObservation)
Missing role definition for Navigable association  in package "Basic Samples": SampleCollection.metadata (towards Any)
Missing definition for Class in package "Basic Samples": StatisticalClassification
Missing definition for Class in package "Codelist realizations": SamplerClassification
Missing definition for Class in package "SamplingCascade": W32564
Missing definition for Class in package "ModelConsistency - Gender": GenderValue
Missing definition for attribute in package "ModelConsistency - Gender": GenderValue.sex
```
For the documentation of definitions from the model: You should ask Ribose and Ronald Tse (@ronaldtse) (tse@ribose.com) for help. They can generate very good documentation of the model, prepared for use in the ISO template.

**Comment by ilkkarinne** [comment]
Thanks @jetgeo. Fixed the rest (excluding the examples), but the second one ```Missing role definition for Navigable association  in package "Basic Samples": Sample.relatedObservation (towards AbstractObservation)``` seems strange. There should be no associations in between Basic Samples: Sample (featureType) and Abstract Observation core: AbstractObservation (featureType)

**Comment by jetgeo** [comment]
Well, the association exists in the model :). For illustration, I created a diagram `"Sample and AbstractObservation"` now in the package `"Basic Samples"`. See bellow. 
![image](https://user-images.githubusercontent.com/7501876/129029673-655b73db-0c95-438a-933f-4c02d628a28f.png)

**Comment by ilkkarinne** [comment]
Ok, so it did, must have been an artifact of some refactoring! The association now deleted from the model, thanks for spotting!

**Comment by jetgeo** [comment]
I checked the model now, these four remain, I guess they are what you refer to as examples:
```
Missing definition for Class in package "Codelist realizations": SamplerClassification
Missing definition for Class in package "SamplingCascade": W32564
Missing definition for Class in package "ModelConsistency - Gender": GenderValue
Missing definition for attribute in package "ModelConsistency - Gender": GenderValue.sex
```
I would prefer that you add some simple definition to them as well... Everything in a model should have a definition that explains what it is.

**Comment by ilkkarinne** [comment]
I have now added definitions to 
- ```SamplerClassification``` and improved the one for ```SampleByMaterialClass``` and
- ```GenderValue``` and its ```gender``` attribute (I guess this used to be ```sex```)

I remove the class W32564 completely as it was not used in any of the diagrams

**Comment by ilkkarinne** [comment]
Agreed to delete these from EA as soon as @KathiSchleidt has had the time export them for further use. Moving to implemented as all definitions are already in place in UML
