### ISSUE TITLE
Observation Types

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#114]
**OGC Comment**
 1. Evaluator:
  Robin Huisman
  SIKB - Stichting Infrastructuur Kwaliteitsborging Bodembeheer - Soil data management and exchange / TerraIndex
  robin@terraindex.com

1. Requirement: AbstractObservationTypeCodelistValue is not clear
2. Implementation Specification Section number:   9.2.3             Attribute observationType
3. Criticality:  Minor
4. Comments/justifications for changes: 
              It's not clear how to use the AbstractObservationTypeCodelistValue and other codeLists.
              Can we get more description of how this should be used by defining your own lists and an example of how to do this?

**Comment by KathiSchleidt** [comment]
Add information on how to deal with the Observation Types in Annex B

**Comment by KathiSchleidt** [comment]
http://defs.opengis.net/elda-common/ogc-def/resource?uri=http://www.opengis.net/def/observationType&_format=ttl
vs
imported
defs-dev.opengis.net/static/definitions/conceptschemes/om.ttl
Issue seems to be from line 418, 
<http://www.opengis.net/def/ogc-om/>
      owl:sameAs <http://www.opengis.net/def/observationType/OGC-OM/2.0/> , <http://www.opengis.net/def/ogc-om/> ;
add member samplingSolid etc

**Comment by sgrellet** [comment]
Indeed, working on the V2 <-> V3 mapping, we land on ObservationTypes as currently defined in OGC definition Server.

Looking at http://defs.opengis.net/elda-common/ogc-def/resource?uri=http://www.opengis.net/def/observationType&_format=ttl
we don't understand why things such as <http://www.opengis.net/def/sampling-feature-type/ogc-om/2.0/sf_sampling-solid> are in scheme of 
skos:inScheme  <http://www.opengis.net/def/observationType>

The initial source is claimed to be (http://defs-dev.opengis.net/static/definitions/conceptschemes/om.ttl)

http://www.opengis.net/def/ogc-om/
owl:sameAs http://www.opengis.net/def/observationType/OGC-OM/2.0/ , http://www.opengis.net/def/ogc-om/

this leads SamplingFeatures types to be listed as ObservationTypes

**Comment by KathiSchleidt** [comment]
AbstractObservationTypeCodeListValue must be defined
provide reference to annex C part

Add subclause to Annex C providing mapping from obstypes (see v2) to codelists (what OGC  currently has, where missing TBD)

**Comment by KathiSchleidt** [comment]
Also pertains to other codelists:

- AbstractSampleTypeCodeListValue
- AbstractSamplerTypeCodeListValue

**Comment by ilkkarinne** [comment]
The ```ObservationTypeByResultType``` codelist was moved from the informative Codelist realizations package into the Basic Observations package, and thus made normative. As per resolution defined in the issue https://github.com/opengeospatial/om-swg/issues/123#issuecomment-857534640, I have how added the following new constraints in the UML:
- Abstract Observation core: AbstractObservation: new constraint "property values shall comply with the constraints defined in the class of the observationType attribute value" added.
- Basic Observations: ObservationTypeByResultType: new constraint "/req/obs-basic/ObservationTypeByResultType-con" added with the following note:

> The following constraints shall be applied to the value of the result association of the Observation based on the codelist value used: 
> * If value "measurement" is used, the value of the result shall be of type Measure.
> * If value "category-observation" is used the value of the result shall be of type ScopedName.
> * If value "truth-observation" is used, the value of result shall be a truth value.
> * If the value "count-observation" is used, the value of the result shall be of type Integer.
> * If the value "temporal-observation" is used, the value of the result shall be of type TM_Object.
> * If the value "geometry-observation" is used, the value of the result shall be of type Geometry
> * If the value "complex-observation" is used, the value of the result shall be of type Record.
> * If the value "discrete-coverage-observation" is used, the value of the result shall be of type DiscreteCoverage.
> * If the value "discrete-point-coverage" is used, the value of the result shall be of type DiscretePointCoverage.
> * If the value "timeseries-observation" is used, the value of the result shall be a timeseries (a sequence of data values which are ordered in time) constrained by the phenomenonTime.

If the text above seems ok, I can copy it as the value of the new requirement ```/req/obs-basic/ObservationTypeByResultType-con``` is the specification

**Comment by KathiSchleidt** [comment]
Rephrased as follows:

If information on the type of Observation is provided, the constraints defined in the referenced codelist SHALL be used.

**Comment by KathiSchleidt** [comment]
Added Requirement

/req/obs-core/AbstractObservationType/AbstractObservationType-sem	

A codelist detailing the semantics of observation types. A concrete realization must be created for the application.
