### ISSUE TITLE
Interface Observation missing reference

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#117]
**OGC PART B 17/35**
1. Requirement: This aspect is further clarified in .
2. Implementation Specification Section number: 8.2.2 Interface Observation
3. Criticality: Editorial
4. Justifications for changes: reference is missing.

Original Text from 8.2.2 Interface Observation:
NOTE	It is important to note that the terms ‘observation’, ‘interpretation’, ‘forecast’, ‘simulation’ do correspond to this definition. This aspect is further clarified in .

**Comment by KathiSchleidt** [comment]
Missing reference to clause 7, will be added

**Comment by sgrellet** [comment]
To be done at the end

**Comment by sgrellet** [comment]
UML image will be updated through issue #91

**Comment by KathiSchleidt** [comment]
Reference to clause 7 needs to be crosslinked once the doc has settled, UML is OK
