### ISSUE TITLE
Interface Deployment Note

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#119]
PART B 19/35
1. Requirement: - the description of a ship cruise to
2. Implementation Specification Section number: 8.8.2 Interface Deployment
3. Criticality: Editorial
4. Justifications for changes: missing information.

KS: 
change
-	the description of a ship cruise to

-	the description of a ship cruise linking a research vessel with a marine network

**Comment by KathiSchleidt** [comment]
Adjust first intro line from
NOTE	A Deployment can range from
to
NOTE	Examples of deployment are:

**Comment by sgrellet** [comment]
Fixed right now
