### ISSUE TITLE
Define “descriptive metadata”

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#12]
In the text there is some requirements regarding “descriptive metadata”. However, this concept is not defined anywhere. So the question is what does this cover?
Pertains to clause 7.2.2.11 Metadata: Describe what descriptive metadata consist of. I.e. what elements from ISO 19115-1 is included.

Source: TC211 Comments DK020

**Comment by KathiSchleidt** [comment]
This section should be refined once we have resolved the issue on metadata type #34 
Do we need to keep this one open, or can we just add a note on 34?

**Comment by ilkkarinne** [comment]
Agreed to close in 18th Dec SWG meeting.
Details to sorted with defining the type of the metadata, see #34
