### ISSUE TITLE
Time Period Attributes

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#121]
**OGC PART B 22/35**
1. Requirement: validTime
2. Implementation Specification Section number: 9.3.3 Constraint validTime period
3. Criticality: Minor
4. Comments for changes: rename attribute to validityPeriod
4. Justifications for changes: name matches the semantics and type.
 
**OGC PART B 23/35**
1. Requirement: deploymentTime
2. Implementation Specification Section number: 9.8.3 Attribute deploymentTime
3. Criticality: Minor
4. Comments for changes: rename attribute to deploymentPeriod
4. Justifications for changes: name matches the semantics and type.

KS: to my view, this maintains alignment with the Observation attributes

**Comment by dr-shorthair** [comment]
FWIW there is a nice list of 'time-lines' here, which I think is related
http://www.anchormodeling.com/time-in-databases/

**Comment by KathiSchleidt** [comment]
also well aligned with V2 and existing deployments
