### ISSUE TITLE
Remove Sample specialisation of Any

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#124]
**OGC PART B 28/35**
1. Requirement: Figure 49: Sample is specialisation of Any
2. Implementation Specification Section number: 11.1.1 Conceptual Sample schema model
3. Criticality: Minor
4. Comments for changes: remove specialisation relation
4. Justifications for changes: redundant.

KS: makes sense, think was there to show that the other foi associations can also point to sample

**Comment by KathiSchleidt** [comment]
Agreed

**Comment by ilkkarinne** [comment]
The specialization was added to highlight that a   Sample could be used as the value of the ```proximateFeatureOfInterest``` association of ```AbstractObservation```.   But as stated in the comment this is not necessary.

**Comment by sgrellet** [comment]
The specialization is still in the docx. Comment added not to forget

**Comment by KathiSchleidt** [comment]
UML Diagrams are all still the old ones, many should be revisited, made a bit more legible

**Comment by sgrellet** [comment]
UML image will be updated through issue #91
