### ISSUE TITLE
Attribute parameter example

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#126]
**OGC PART B 31/35**
1. Requirement: EXAMPLE When taking water samples, the sampling procedure specifies that an amount of time must pass to allow sediments to settle. The exact waiting time for a specific sample can be stored in the parameter.
2. Implementation Specification Section number: 12.2.3 Attribute parameter
3. Criticality: Editorial
4. Comments for changes: EXAMPLE For a water sample, sampled for chemical analysis, it may be relevant to know its sampling temperature.
4. Justifications for changes: The current example is more suitable to 12.3 AbstractSampling.

KS: disagree. Reason for the example here is to illustrate the use of the parameter, not to explain that the sampling temperature can be relevant

**Comment by KathiSchleidt** [comment]
EXAMPLE 	When taking water samples, the sampling procedure specifies that an amount of time must pass to allow sediments to settle. The exact waiting time for a specific sample can be stored in the parameter.

Providing the temperature would be more suitable via a relatedObservation.

Add an additional note:
parameter should not be used to provide information that is available via a relatedObservation

**Comment by KathiSchleidt** [comment]
Delete example to avoid confusion

**Comment by sgrellet** [comment]
+1 on deleting the Domain example

**Comment by sgrellet** [comment]
but I'd be very much in favour of adding an IT example
this attribute is very useful as it enables to use O&M as a backbone + allow extension when things don't fit in the current model

**Comment by KathiSchleidt** [comment]
Thinking this one through once more, I'm seeing the charm of the original example. While I get the point that the time for sediment settling is part of the process, I also get the fact that reality often subtly diverges from the best laid plans.

EXAMPLE 	When taking water samples, the sampling procedure specifies the amount of time that must pass to allow sediments to settle. As reality is rarely as exact as plans, the actual waiting time applied to a specific sample can be stored in the parameter.
