### ISSUE TITLE
Sample Semantics

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#127]
OGC PART B 32/35
1. Requirement: /req/sam-basic/Sample/Sample-sem
2. Implementation Specification Section number: 13.2.1 Sample Requirements Class
3. Criticality: Minor
4. Justifications for changes: Add a requierement explaining the semantics (reason for existance) of the Sample class. See e.g. D.3.1 a).

KS: to my view this meaning is contained in the base Sample definition from the conceptual model

/req/sam-cpt/Sample/Sample-sem | A Sample is   an object that is representative   of a concept, real-world object or phenomenon.

D.3.1 a). an intermediate Sample class that allows the assignment of primitive and intermediate properties within a processing chain

**Comment by KathiSchleidt** [comment]
**OGC PART B 33/35**
1. Requirement: /req/sam-basic/Sampler/Sampler-sem
2. Implementation Specification Section number: 13.7.1 Sampler Requirements Class
3. Criticality: Minor
4. Justifications for changes: Add a requierement explaining the semantics (reason for existance) of the Sampler class. Particularly if the class is abstract or not (I assume is is not).

KS: basically same as above, requirement is included via the cascade

**Comment by KathiSchleidt** [comment]
Requirement included in the requirements cascade, thus works for us

**Comment by sgrellet** [comment]
seems ok 
but in the doc we have either ../sampler-sem or .../Sampler-sem which one do we go for ?

**Comment by KathiSchleidt** [comment]
Depends on if we're referring to the semantics of the Sampler class itself or the sampler association from other classes (Class sem req is always Capital, association semantics always lowercase). We have the following instances of sampler-sem, consistent to my logic:

11.3.1	Sampling Requirements Class (/req/sam-cpt/Sampling)
/req/sam-cpt/Sampling/sampler-sem


11.4.1	Sampler Requirements Class (/req/sam-cpt/Sampler)
/req/sam-cpt/Sampler/Sampler-sem

11.7.1	SamplingProcedure Requirements Class (/req/sam-cpt/SamplingProcedure)
/req/sam-cpt/SamplingProcedure/sampler-sem

**Comment by sgrellet** [comment]
Makes full sense and we even have this in section 5.
"_For naming of individual requirements pertaining to classes, the following syntax is used:
•	{Class Name}-sem: The semantic definition of the concept, together with the naming of the Class.
For naming of individual requirements pertaining to attribute or associations, the following syntax is used:
•	{Attribute/Association Name}-sem:_"

I'm supposed to have co-defined this with you, and after couple months, I stumble (twice) on our very own rationale.
-> what about adding a note/warning in section 5.4 right after '_For naming of individual requirements pertaining to attribute or associations, the following syntax is used_ Stating : '**Individual requirements are case sensitive, following UML rules applied, one have to be careful when reading them**'

**Comment by KathiSchleidt** [comment]
Added the following paragraph after the syntax list:
Please note that the individual requirements are case sensitive, following UML naming conventions. Requirements pertaining to classes contain the class name in UpperCamelCase, requirements pertaining to associations utilize the association role name in lowerCamelCase.
