### ISSUE TITLE
Order of clauses 4 and 5

### ISSUE THREAD

**Issue by ilkkarinne** [opengeospatial/om-swg#129]
MB/NC: TMG-058
Clause/Subclause: 4 & 5
Paragraph/Figure/Table:
Type of comment: ed
Comments: normally the Abbreviated terms and acronyms are closer to clause 3, such as a subclause of clause 3 or typically in clause 4, along with other notation;
Proposed change: consider switching the order of clauses 4 and 5

**Comment by ilkkarinne** [comment]
Clause 4: Conformance
Clause 5: Document conventions

**Comment by KathiSchleidt** [comment]
Change to
Clause 4: Document conventions
Clause 5: Conformance

**Comment by KathiSchleidt** [comment]
I've added comments to both clause headers, but haven't moved yet so that the other tracked changes don't get lost

**Comment by sgrellet** [comment]
okay, to be done at the end. thus not moving it to Implemented yet
