### ISSUE TITLE
Duplicate property names in self-associations for Observation and Host

### ISSUE THREAD

**Issue by jetgeo** [opengeospatial/om-swg#131]
The self-associations for Observation (relatedObservation) and Host (relatedHost) are modelled bidirectionally and with identical role names on both ends. 

I believe that I understand the idea, which we recognise as symmetric properties in OWL. Unfortunately, symmetric properties are not defined in UML, but an approach with the tagged value owlLogicalCharacteristics for properties was suggested in OGC Testbed 14 and is implemented in the ShapeChange UML Profile (https://shapechange.net/app-schemas/uml-profile/).

The identical role names give each of the classes two identical property names, which breaks requirement 16 of ISO 19103 (unique names within their namespace, which for an association is its class), and will be a problem when deriving implementation schemas in XML.  If the purpose is to define symmetric properties in OWL, I recommend to rather use the tagged value owlLogicalCharacteristics. 

The association in UML should be one-way only. In an XML-based implementation, I suppose the relation would need to be added to both two involved instances of classes in order to become symmetric. A note attached to the relations in the UML diagram may be useful for an explanation. 

![image](https://user-images.githubusercontent.com/7501876/107235609-26aae400-6a25-11eb-92a7-d4fe3d9dbe55.png)

**Comment by ilkkarinne** [comment]
These bi-directional self-association have now been changed into single-directional in the following places:

- Conceptual Observation Schema
   - Observation.relatedObservation
   - Host.relatedHost
- Conceptual Sample Schema
   - Sample.relatedSample
   - Sampling.relatedSampling
- Basic Observations
   - ObservationCollection.relatedCollection
- Basic Samples
   - SampleCollection.relatedCollection

**Comment by ilkkarinne** [comment]
I checked the https://shapechange.net/app-schemas/uml-profile/ and decided not to use tagged value ```owlLogicalCharacteristics=Symmetric```, as the relatedObservation on others are not required to **always** be symmetric at the object level: if one Observation has ```relatedObservation``` association to another Observation, the other one may not have an explicit identical ```relatedObservation``` association back to the first one. Definitely the ```context``` qualifier would not have an identical value in both directions. Thus, if I understood correctly, the association is not ```Symmetric``` as defined by ```owlLogicalCharacteristics```.

**Comment by KathiSchleidt** [comment]
Doc diagram will be updated via issue #91
