### ISSUE TITLE
Bibliography

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#134]
I've tried to update the bibliography, but cannot sanely edit this part. Issues:

- Can't add references that have been deleted (in the text) to existing entries in the bibliography
- Can't add new entries to the bibliography

I'll leave comments in the doc where things should happen, hope somebody else can figure out the current formating

**Comment by sgrellet** [comment]
still in TODO stage. proposal to move this from 'implemented' to 'resolution agreed'. We should not underestimate the job here

**Comment by KathiSchleidt** [comment]
Set back to resolution agreed, hope somebody else can get the references sorted (I failed!)

**Comment by KathiSchleidt** [comment]
Can we add a further section to the bibliography - "Further relevant standards"
Don't know how to link in the references to these in the bib as don't know where to reference them

**Comment by KathiSchleidt** [comment]
ToDo:

- Figure out syntax for referencing ISO Standards from the Bibliography
- Assure that the reference numbers are correct, remove the ones marked as (removed as no longer relevant)

**Comment by sgrellet** [comment]
@ilkkarinne  : will then be the cross-checker
