### ISSUE TITLE
Carl Reed's Feedback version!!!

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#138]
Going through the dregs of the feedback, found a version of the doc that Carl Reed nicely edited through, caught all sorts of minor typos and changed in track changes mode. Think it's OK to merge this?

**Comment by sgrellet** [comment]
+1

**Comment by KathiSchleidt** [comment]
@sgrellet when do you think you'll find (steal) time for the review? e.g. should I merge in Carl's comments before or after?

**Comment by sgrellet** [comment]
I had planned starting this Thursday (partly), then Friday (partly) and see where I am after this :)
