### ISSUE TITLE
Pattern for the codelist related requirements in the spec

### ISSUE THREAD

**Issue by ilkkarinne** [opengeospatial/om-swg#140]
In the Word doc version of [17th June](https://github.com/opengeospatial/om-swg/blob/df727f3eabc3ec63c180c68f6361a8390e786be0/oms-abstract-spec/ogc-as-topic20/20-082r2_OGC_Abstract_Specification_Topic_20_-_Observations_and_measurements.docx) the code list related content is still mostly absent, only the ObservationCollection related requirements under the basic Observations are there:

- 10.4 ObservationCollection
   - ```/req/obs-basic/ObservationCollection/collectionType-homogenous-con```
   - ```/req/obs-basic/ObservationCollection/collectionType-summarizing-con```
- 10.12 Codelists
   - 10.12.1 AbstractObservationCollectionTypeCodeListValue
      -  ```/req/obs-basic/ObservationCollection/AbstractObservationCollectionTypeCodeListValue-sem```
   - 10.12.2 CollectionTypeByMemberCharacteristicsSemantics
      - ```/req/obs-basic/ObservationCollection/CollectionTypeByMemberCharacteristicsSemantics-sem```

The requirements for the classification schemes for Observations and Samples as missing (see #56 #114). Also it was decided in #123 that the requirements related to the ObservationCollection constraints would be moved from clause ObservationCollection to CollectionTypeByMemberCharacteristicsSemantics.

I propose the following changes to the clause and req.class structure to keep the codelist related content consistent:

**Abstract Observation core package**
1. Add new sub-clause _9.2.8 Codelist AbstractObservationType_ under _9.2 AbstractObservationCharacteristics_: 
   -  ```/req/obs-basic/AbstractObservationCharacteristics/AbstractObservationType-sem``` with content "an empty codelist parent class for Observation classification schemes. All codelists used for classifying Observations SHALL be specialized from this class."
1. Add new sub-clause _9.3.6 Constraint Observation typing_ under _9.3 AbstractObservation_:
   - ```/req/obs-basic/AbstractObservation/observationType-con``` with content "property values shall comply with the constraints defined in the class of the observationType attribute value"

**Abstract Sample core package**
1. Add new sub-clause _12.2.4 Constraint Sample typing_ under _12.2 AbstractSample_:
   - ```/req/sam-core/AbstractSample/sampleType-con``` with content "property values shall comply with the constraints defined in the class of the sampleType attribute value"
1. Add new sub-clause _12.2.5 Codelist AbstractSampleType_ under _12.2 AbstractSample_: 
   -  ```/req/sam-core/AbstractSample/AbstractSampleType-sem``` with content "an empty codelist parent class for Sample classification schemes. All codelists used for classifying Samples SHALL be specialized from this class."
1. Add new sub-clause _12.4.3 Constraint Sampler typing_ under _12.4 AbstractSampler_:
   - ```/req/sam-core/AbstractSampler/samplerType-con``` with content "property values shall comply with the constraints defined in the class of the samplerType attribute value"
1. Add new sub-clause _12.4.4 Codelist AbstractSamplerType_ under _12.4 AbstractSampler_: 
   -  ```/req/sam-core/AbstractSampler/AbstractSamplerType-sem``` with content "an empty codelist parent class for Sampler classification schemes. All codelists used for classifying Samplers SHALL be specialized from this class."

**Basic Observations package**
1. Add new sub-clause _10.4.7 Constraint ObservationCollection typing_ under _10.4 ObservationCollection_:
   - ```/req/obs-basic/ObservationCollection/collectionType-con``` with content "properties of both the ObservationCharacteristics associated with role memberCharacteristics and of the Observations associated with role member shall comply with the constraints defined in the class of the used collectionType value."
1. Move the clause 10.12.1 AbstractObservationCollectionTypeCodeListValue to a sub-clause _10.4.8 Codelist AbstractObservationCollectionType_ under _10.4 ObservationCollection_ :
   -  ```/req/obs-basic/ObservationCollection/AbstractObservationCollectionType-sem``` with content "an empty codelist parent class for ObservationCollection classification schemes. All codelists used for classifying ObservationCollections SHALL be specialized from this class." 
1. Move ```/req/obs-basic/ObservationCollection/collectionType-homogenous-con``` and ```/req/obs-basic/ObservationCollection/collectionType-summarizing-con``` under the CollectionTypeByMemberCharacteristicsSemantics clause (see below)
1. Rename/re-structure the current 10.12 Codelists clause:
   - _10.12 Codelist CollectionTypeByMemberCharacteristicsSemantics_
      - _10.12.1 CollectionTypeByMemberCharacteristicsSemantics Requirements Class_
         -  ```/req/obs-basic/CollectionTypeByMemberCharacteristicsSemantics/CollectionTypeByMemberCharacteristicsSemantics-sem``` with content "ObservationCollection classification scheme based on how the properties of the ObservationCharacteristics associated with role memberCharacteristics shall be related to the corresponding properties of the Observations associated with role member"
      - _10.12.2 Constraint homogenous ObservationCollection_
         - ```/req/obs-basic/CollectionTypeByMemberCharacteristicsSemantics/homogenous-con``` (see proposed revised content in the following comment)
      - _10.12.3 Constraint summarizing ObservationCollection_
         - ```/req/obs-basic/CollectionTypeByMemberCharacteristicsSemantics/summarizing-con``` (see proposed revised content in the following comment)
   - _10.13 Codelist ObservationTypeByResultType_
      -  _10.13.1 ObservationTypeByResultType Requirements Class_
         -  ``` /req/obs-basic/ObservationTypeByResultType/ObservationTypeByResultType-sem``` with content "Observation classification scheme based on the type of its result property"
       - _10.13.2 Constraint Observation specialization by result type_
          -  ``` /req/obs-basic/ObservationTypeByResultType/result-con``` (see proposed content in the following comment)

**Basic Samples package**
1. Add new clause _13.12 Codelist SampleByGeometryType_
   - _13.12.1 SampleByGeometryType Requirements Class_
      - ```/req/sam-basic/SampleByGeometryType/SampleByGeometryType-sem``` with content "SpatialSample classification scheme based on the geometry type of its shape attribute"
      - ```/req/sam-basic/SampleByGeometryType/shape-con``` (see proposed content in the following comment)
      - ```/req/sam-basic/SampleByGeometryType/context-con``` with content "this codelist shall only be used for classifying SpatialSamples"

(edited URIs etc. based on SWG meeting on 23rd June)

**Comment by ilkkarinne** [comment]
Proposed revised content for ```/req/obs-basic/CollectionTypeByMemberCharacteristicsSemantics/homogenous-con```:

> If the value "homogenous" is used, the following constraints apply to the ObservationCharacteristics instance and all Observation instances associated with the ObservationCollection with roles memberCharacterics and member:
> 
> For each property of the associated ObservationCharacteristics, the following constraints apply to the corresponding property of each Observation member:
> * Property not provided: varying values may be provided for the corresponding property by the member Observations.
> * Property provided but with no content: none of the Observation members  shall contain a value for the corresponding property.
> * Property has other value: the same value applies to the corresponding property of all Observation members even if no value is provided in the particular member.
> 
> NOTE: The mechanism for providing a property with no content is implementation specific. Examples include providing a special "null" or "nil" value.
>

**Comment by ilkkarinne** [comment]
Proposed revised content for ```/req/obs-basic/CollectionTypeByMemberCharacteristicsSemantics/summarizing-con```:

> If the value "summarizing" is used, the following constraints apply to the ObservationCharacteristics instance and all Observation instances associated with the ObservationCollection with roles memberCharacterics and member:
> 
> For each property of the associated ObservationCharacteristics instance, the following constraints apply to the corresponding property of each Observation member:
> * Property not provided: varying values may be provided for the corresponding property by the Observation members and no summary is provided at the collection level.
> * Property provided but with no content: none of the Observation members shall contain a value for the corresponding property.
> * Property contains a single, non-range value: the same value applies to the corresponding property of all Observation members even if no value is provided in the particular member.
> * Property contains a value set or range value: all Observation members shall contain a value for the corresponding property that is within the provided value set or range.
> 
> NOTE: The mechanism for providing a property with no content is implementation specific. Examples include providing a special "null" or "nil" value.

**Comment by ilkkarinne** [comment]
Proposed content for ```/req/obs-basic/ObservationTypeByResultType-con```:

> The following constraints shall be applied to the value of the result association of the Observation based on the codelist value used: 
> 
> - If the value "measurement" is used, the value of the result shall be of type Measure.
> - If the value "category-observation" is used the value of the result shall be of type ScopedName.
> - If the value "truth-observation" is used, the value of result shall be a truth value.
> - If the value "count-observation" is used, the value of the result shall be of type Integer.
> - If the value "temporal-observation" is used, the value of the result shall be of type TM_Object.
> - If the value "geometry-observation" is used, the value of the result shall be of type Geometry
> - If the value "complex-observation" is used, the value of the result shall be of type Record.
> - If the value "discrete-coverage-observation" is used, the value of the result shall be of type DiscreteCoverage.
> - If the value "discrete-point-coverage" is used, the value of the result shall be of type DiscretePointCoverage.
> - If the value "timeseries-observation" is used, the value of the result shall be a timeseries (a sequence of data values which are ordered in time) constrained by the phenomenonTime.

**Comment by ilkkarinne** [comment]
Proposed content for ```/req/sam-basic/SampleByGeometryType-geometry-con```:

> The following constraints shall be applied to the value of the shape attribute of the SpatialSample based on the codelist value used: 
> 
> - If value "point" is used, the value of the shape shall be of type Point.
> - If value "curve" is used, the value of the shape shall be of type Curve.
> - If value "surface" is used, the value of the shape shall be of type Surface.
> - If value "solid" is used, the value of the shape shall be of type Solid.

**Comment by ilkkarinne** [comment]
Note: the abstract (empty) code list classes would not become separate requirements classes, as they cannot be implemented by themselves, and must be supported by anyone supporting their context req. classes (AbstractObservation, ObservationCollection, AbstractSample and AbstractSampler).

**Comment by KathiSchleidt** [comment]
Remove CodeListValue from abstract codelist names

**Comment by KathiSchleidt** [comment]
Update doc to reflect these changes

**Comment by ilkkarinne** [comment]
The "CodeListValue" post-fix has now been removed from names of the following codelists:

- Abstract Observation core:AbstractObservationType
- Abstract Sample core:AbstractSampleType
- Abstract Sample core:AbstractSamplerType
- Basic Observations:AbstractObservationCollectionType

**Comment by ilkkarinne** [comment]
Note that the it was proposed in the OMS JSON workshop on 29th Sep 2021 that the value specific constraints for the ```ObservationTypeByResultType``` and ```SampleByGeometryType``` be removed from the UML model and not added as requirements ```/req/obs-basic/ObservationTypeByResultType-con``` and ```/req/sam-basic/SampleByGeometryType-geometry-con``` into the specification.

The justification was that any requirements imposed by using particular current or future values of the referred codelists should be provided and maintained with the definitions of these codelist values, and not fixed in the OMS model.

Moving this back into the In discussion to agree on the possible change to the previous resolution.

**Comment by KathiSchleidt** [comment]
Add req with minimal values for the codelist

**Comment by KathiSchleidt** [comment]
Anybody who uses this codelist owes us a beer!

**Comment by KathiSchleidt** [comment]
Definitions for last 3
"discrete-coverage-observation" : geometry will be a coverage that returns the same feature attribute values for every direct position within any single spatial object, temporal object, or spatiotemporal object in its domain
"discrete-point-coverage" : geometry will be a coverage that has a domain composed of points
"timeseries-observation" the value of the result shall be a timeseries (a sequence of data values which are ordered in time).
