### ISSUE TITLE
Parameter constraint: duplicate key

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#141]
Highlighted by Carl in his edits, we have the following Note under the AbstractObservationCharacteristics parameter description that implies a constraint on parameter:

`NOTE		This might be an environmental parameter, an instrument setting or input, or an event-specific sampling parameter that is not tightly bound to either the feature-of-interest or to the observation procedure. To avoid ambiguity, there shall be no more than one parameter with the same name.`

Do we want/need to make a formal constraint out of this?

**Comment by KathiSchleidt** [comment]
note from Ilkka: This is constrained for the AbstractObservation in /req/obs-core/AbstractObservation/parameterName-card. Remove from here?

**Comment by KathiSchleidt** [comment]
Add constraint to all usages of parameter, check where best fits in the cascade

**Comment by ilkkarinne** [comment]
Just for the record: We also have parameters in Abstract Sample schema AbstractSample and AbstractSampling, but the requirements classes of those do not contain a similar constraints on thee duplicate parameter names.

It is probably too late to add new requirements for these at this point.

Ping @KathiSchleidt and @sgrellet

**Comment by KathiSchleidt** [comment]
@ilkkarinne good catch, but also think too late to add this sanely.
To my view, NOT mission critical, and sane users will do this anyway, while the others won't let a little constraint stop them from providing duplicates ;)
