### ISSUE TITLE
Informative Clause for Codelists

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#142]
Is mentioned in Annex C, but doesn't exist yet, should!

**Comment by KathiSchleidt** [comment]
Need to decide if we add an informative clause for "other codelists", also decide if this just for sampling, or also required for obs
As we describe at least some of the codelists in the normative clauses (see #140 ), the statement in Annex C needs to be checked

**Comment by sgrellet** [comment]
Which bring along the discussion about pushing a codeList that corresponds to the softyping of SF_SamplingPoint, SF_SamplingCurve, SF_SamplingSurface, SF_SamplingSolid. 

In OM V2, IMHO those classes 'just' provided constraints on the geometry. 

Does that make sense to keep this even in a softTyping oriented codeList ? 

I am fully aware of many standards that specialize it. But most of them will have to consider revision after OM V3 is available and while doing that they will have to consider whether their current specialization of SF_Samplingxxx is semantically describing a SpatialSample, an Observer, a Host, ....

**Comment by ilkkarinne** [comment]
@KathiSchleidt: you mean that we should consider adding an informative clause with no reqs or recs in the spec for the two codelist extension examples (```SampleTypByMaterialClass``` and ```SamplerClassification```) in the Codelist realizations UML package? These are added in the package just as examples of how the specialization could be done, and are not meant to be taken seriously.

**Comment by ilkkarinne** [comment]
@sgrellet: I think I do not fully get you point. In v2.0 spec the ```Geometry(shape)``` association is provided pointing to GM_Object in the SF_SpatialSamplingFeature and defined again in the SF_SamplingPoint, SF_SamplingCurve, SF_SamplingSurface, SF_SamplingSolid pointing to GM_Point, GM_Curve, GM_Surface and GM_Solid respectively (with an intention (?) to re-define/override the same association. Interestingly the Geometry association of the SF_SpatialSamplingFeature is actually not visible in the any of the figures in the UML repo (!?). As far as I can tell the geometry restrictions are not by constraints, but by overriding the associations.

In the v3.0 model this specialization is done with using one of the ```SampleTypeByGeometryType``` codelist values (see [proposed values in SKOS](https://github.com/opengeospatial/om-swg/blob/master/oms-abstract-spec/codelists/sampleTypeByGeometryType.json)) as the value for the ```AbstractSample.sampleType```  attribute. I think we need to keep this to provide a clear migration path for the cases where spatial samples are classified based on their geometry type.

**Comment by ilkkarinne** [comment]
Another option for handling the SampleTypeByMaterialClass and SamplerClassification stub example codelists would be moving them to the Examples package and adding as figures in Annex C. Then we could remove the entire informative Codelist realizations UML package which is currently not presented in the spec at all.

**Comment by KathiSchleidt** [comment]
SampleTypeByGeometryType - values need to be added to the standard, codelist sent by Ilkka to Gobe

**Comment by KathiSchleidt** [comment]
formulate the geometry type codelist as recommendations, note that not required

**Comment by ilkkarinne** [comment]
Ping @KathiSchleidt: the proposed constraint requirement for the SampleTypeByGeometryType is already drafted in https://github.com/opengeospatial/om-swg/issues/140#issuecomment-864944657, sorry for not remembering this in the SWG meeting today.

Same also drafted for the ObservationTypeByResultType at https://github.com/opengeospatial/om-swg/issues/140#issuecomment-864943819

Do we still need recommendations in addition for these ```-con``` requirements for stating that one should use ObservationTypeByResultType for classifying Observations by result type and SampleTypeByGeometryType for classifying Samples by geometry type? Maybe it's already clear enough by the fact that these codelists are included and have their purpose clearly defined in their ```-sem``` requirements (as proposed in https://github.com/opengeospatial/om-swg/issues/140#issue-926094973)

**Comment by ilkkarinne** [comment]
Moved the ```SampleByMaterialClass``` and ```SamplerClassification``` under Examples package, and added as Figures 85 and 86 in Annex C, see https://github.com/opengeospatial/om-swg/commit/c2c4b44d7a404bb63362c3e76d78bc3a1cb7bf72
