### ISSUE TITLE
/req/obs-core/AbstractObservation missing Observation-sem req

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#143]
/req/obs-core/AbstractObservation is missing Observation-sem requirement - should be added to my view

**Comment by sgrellet** [comment]
need to analyse 
- /req/obs-core/AbstractObservationCharacteristics :     is it importing all entries from /req/obs-cpt/Observation apart from Observation-sem ?         and cards ?
- /req/obs-core/AbstractObservation : seem to be missing Observation-sem import

**Comment by KathiSchleidt** [comment]
obs-cpt/Observation-sem is not included in the abstract characteristics as these are not semantically observations. Need to make sure that all necessary reqs get through


Should check the other reqs to make sure that all reqs come up where we need them

**Comment by hylkevds** [comment]
/req/obs-cpt/Observation
1. /req/obs-cpt/Observation/Observation-sem
1. /req/obs-cpt/Observation/phenomenonTime-sem
1. /req/obs-cpt/Observation/phenomenonTime-card
1. /req/obs-cpt/Observation/resultTime-sem
1. /req/obs-cpt/Observation/resultTime-card
1. /req/obs-cpt/Observation/validTime-sem
1. /req/obs-cpt/Observation/featureOfInterest-sem
1. /req/obs-cpt/Observation/featureOfInterest-card
1. /req/obs-cpt/Observation/observedProperty-sem
1. /req/obs-cpt/Observation/observedProperty-card
1. /req/obs-cpt/Observation/result-sem
1. /req/obs-cpt/Observation/result-card
1. /req/obs-cpt/Observation/observingProcedure-sem
1. /req/obs-cpt/Observation/observingProcedure-card
1. /req/obs-cpt/Observation/observer-sem
1. /req/obs-cpt/Observation/host-sem
1. /req/obs-cpt/gen/relatedObservation-sem
1. /rec/obs-cpt/Observation/observerhost-con
1. /rec/obs-cpt/Observation/observedProperty-con
1. /rec/obs-cpt/Observation/procedure-con
1. /rec/obs-cpt/Observation/result-con
1. /rec/obs-cpt/Observation/phenomenonTimeResult-con

/req/obs-core/AbstractObservation
1. /req/obs-core/AbstractObservation/resultTime-type
1. /req/obs-core/AbstractObservation/validTime-type
1. /req/obs-cpt/Observation/phenomenonTime-card
1. /req/obs-cpt/Observation/resultTime-card
1. /req/obs-core/AbstractObservation/FoI-con
1. /req/obs-cpt/Observation/observedProperty-card
1. /req/obs-cpt/Observation/procedure-card
1. /req/obs-cpt/Observation/result-card
1. /req/obs-core/AbstractObservation/parameterName-card
1. /rec/obs-cpt/Observation/observedProperty-con
1. /rec/obs-cpt/Observation/observerhost-con
1. /rec/obs-cpt/Observation/procedure-con
1. /rec/obs-cpt/Observation/result-con
1. /req/obs-core/AbstractObservationCharacteristics

/req/obs-core/AbstractObservationCharacteristics
1. /req/obs-core/AbstractObservationCharacteristics/AbstractObservationCharacteristics-sem
1. /req/obs-core/AbstractObservationCharacteristics/type-sem
1. /req/obs-core/AbstractObservationCharacteristics/parameter-sem
1. /req/obs-core/AbstractObservationCharacteristics/resultQuality-sem
1. /req/obs-cpt/Observation/phenomenonTime-sem
1. /req/obs-cpt/Observation/resultTime-sem
1. /req/obs-cpt/Observation/validTime-sem
1. /req/obs-cpt/Observation/featureOfInterest-sem
1. /req/obs-core/AbstractObservationCharacteristics/pFoI-sem
1. /req/obs-core/AbstractObservationCharacteristics/uFoI-sem
1. /req/obs-cpt/Observation/observedProperty-sem
1. /req/obs-cpt/Observation/result-sem
1. /req/obs-cpt/Observation/procedure-sem
1. /req/obs-cpt/Observation/observer-sem
1. /req/obs-cpt/Observation/host-sem
1. /req/obs-cpt/gen/relatedObservation-sem
1. /req/obs-core/gen/metadata-sem
1. /rec/obs-core/AbstractObservationCharacteristics/parameter-procedure
1. /rec/obs-core/AbstractObservationCharacteristics/parameter-redundant
1. /rec/obs-core/AbstractObservationCharacteristics/uFoI
1. /req/obs-core/NamedValue

**Comment by hylkevds** [comment]
Missing from the bottom two that appear in the first:
* Observation-sem
* observingProcedure-sem
* observingProcedure-card
* featureOfInterest-card
* phenomenonTimeResult-con

**Comment by KathiSchleidt** [comment]
2 ways of doing the cascade:
* add Observation-sem to AbstractObservation reqClass
* add cpt Observation Class to core AbstractObservation  Class (note that many reqs will be duplicated from core AbstractObservationCharacteristics)

**Comment by ilkkarinne** [comment]
I would prefer adding Observation-sem to the AbstractObservation reqClass. This would be consistent with the UML (AbstractObservation realizes Observation).

We should also double-check that each time a class realises an interface, it imports the corresponding ```-sem``` requirement of that interface.

**Comment by KathiSchleidt** [comment]
open point solved in #148
