### ISSUE TITLE
Missing requirement for the "collection" association of the ObservationCharacteristics 

### ISSUE THREAD

**Issue by ilkkarinne** [opengeospatial/om-swg#145]
Clause 10.3. ObservationCharacterstics (in Basic Observation) should contain a requirement for the association role ```collection``` towards the ```ObservationCollection``` class.

**Comment by KathiSchleidt** [comment]
Requirement
/req/obs-basic/ObservationCharacteristics/collection-sem	An ObservationCollection that is described by these ObservationCharacteristics.
If a reference to a collection ObservationCharacteristics is provided, the association with the role collection SHALL be used.
