### ISSUE TITLE
Missing requirement "observingProcedure-card"

### ISSUE THREAD

**Issue by ilkkarinne** [opengeospatial/om-swg#148]
The ```/req/obs-cpt/Observation/observingProcedure-card``` is listed in the Requirements class "/req/obs-cpt/Observation" table as in Requirement, but there is no sub-clause declaring it under clause 8.2 Observation.

Additionally in clause 9.3 AbstractObservation Requirements Class "/req/obs-core/AbstractObservation" table Imports ```/req/obs-cpt/Observation/procedure-card``` which should probably also be  ```/req/obs-cpt/Observation/observingProcedure-card```

**Comment by KathiSchleidt** [comment]
Need to add req /req/obs-cpt/Observation/observingProcedure-card
Should be added to both: 

- /req/obs-cpt/Observation
- /req/obs-core/AbstractObservation (there still only procedure-card)
