### ISSUE TITLE
Property vs ObservedProperty

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#154]
we define "property" in the defs, then only talk about observedProp, wondering if we need to bridge this gap or if it's implicit

**Comment by dr-shorthair** [comment]
Remove 'observable' --> 
"A quality (property, characteristic) of the feature-of-interest that can be observed."

**Comment by sgrellet** [comment]
Indeed 'observable' and 'can be observed' in the same sentence look redundant.
And it would make the definition cleaner: so far, we are writing that something 'observable' is 'observable', not much value added.
+1 on the suggestion -> thus reopening

What does the rest of the group think about it ?
Do we have other defs to adjust accordingly ?
If Yes, we'll have to update the def in the UML.
