### ISSUE TITLE
Insert all UML Diagrams to Doc

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#158]

**Comment by ilkkarinne** [comment]
@KathiSchleidt : I'm still missing EMFs for Figures 36 and 37 in GitHub from Examples package. Not critical as the Figures as OK in Word.

Adding pngs for these in todays submission package

**Comment by ilkkarinne** [comment]
Fixed the captions for Figures 32, 33 and 43, were still copy-paste from the old requirements dependency diagrams. Updated all Figure fields, the ones in Annexes were not up-to-date.

All figure updated now cross-checked OK!

**Comment by ilkkarinne** [comment]
Not exactly about UML Diagrams, but also missing the Figure 2 pptx(?) in GitHub, added as png for now
