### ISSUE TITLE
OMXML: Correct cardinality for 'sampledFeature' property

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#16]
Simon:

In the XML Schema implementation of SamplingFeatures ﷒0﷓ the cardinality of the sampledFeature property is given as 1..1 which is inconsistent with the Abstract Specification (Topic 20)

In ﷒0﷓ change the line 
<element name="sampledFeature" type="gml:FeaturePropertyType" nillable="true" block="#all">
to
<element name="sampledFeature" type="gml:FeaturePropertyType" maxOccurs="unbounded" nillable="true" block="#all">
and increment the schema&#64;version attribute to 2.0.2. 

**NOTE: this was incorrectly submitted as maxOccurs="2" and version 2.0.1.  Was corrected according to abstract spec topic 20, figure 9. 

Inconsistent with abstract specification. 
None in document. 
Change only needed in schema repository. 

Source: http://ogc.standardstracker.org/show_request.cgi?id=334
http://ogc.standardstracker.org/show_request.cgi?id=118

**Comment by ilkkarinne** [comment]
Change has been made to the schema repository (before our work started). Agreed to close in 18th Dec SWG meeting
