### ISSUE TITLE
Figure References in Text

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#166]
At times, we refer the "the diagram below" instead of directly referencing the figure number, should be adjusted.
Pertains to comments:
- **-035
- **-040

**-035 The diagram below
Please refer to a specific figure number, rather than using a more general reference.

**-040 (7.3.1) The figure below shows
Please refer to the specific figure number, rather than saying "the figure below".

**Comment by sgrellet** [comment]
Agreed. Now that we have our figures numbers properly set up. We can sanely refer to them

**Comment by sgrellet** [comment]
@ilkkarinne  : in the document 
- Figure 33— Context diagram for Basic Samples — SamplingProcedure 

Image from EA still states **32**: Contexte diagram: Sampler (should be numbered 33)

**Comment by sgrellet** [comment]
Looking at the latest image https://github.com/opengeospatial/om-swg/blob/master/oms-abstract-spec/figures/final-iso-19156/19156_ed2fig33.pdf this was corrected in the latest images generation

**Comment by sgrellet** [comment]
moving to cross-checked

**Comment by ilkkarinne** [comment]
Whoops, I just noticed that Figures D.4 and D.5 are the same (D.5 duplicated as D.4). Will generate the correct D.4 and replace it
