### ISSUE TITLE
Normative reference vs. Bibliography

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#167]
**-004 ISO 19109:2015, Geographic information — Rules for application schema**	
In order to be considered a normative reference, a document has to be the subject of a requirement. ISO 19109 does not seem to be the subject of any requirements within this document. Please move it to the Bibliography as an informative reference.

**Comment by KathiSchleidt** [comment]
We need info from @cportele on this issue

**Comment by cportele** [comment]
The comment makes sense to me, 19109 is not a normative reference. 19109 has been used to develop the OMS schema, but implementers of OMS do not have to buy and read 19109 to implement OMS. So, yes, the 19109 reference should be moved to the bibliography.

**Comment by ilkkarinne** [comment]
19109 referenced in Clause 6.2.2 UML Package dependencies both in the Table 7 and Figure 1, in Clause 4.2 and many other places but indeed there is not requirement statement where it is referenced.

If moved to bibliography, the entire document needs to be scanned for textual references to 19109 to be replaced with the bib. ref.

**Comment by KathiSchleidt** [comment]
Same as #185 
Delete 19109 from Normative References, move to Bibliography without date, add Bib reference to all mentions in doc

**Comment by sgrellet** [comment]
@KathiSchleidt  - We do have a Ref in Bib : [2] ISO 19109, Geographic information — Rules for application schema
but we are not using it throughout the document when 19109 is mentionned
Same comment as for #185

**Comment by KathiSchleidt** [comment]
See comment under #185

**Comment by sgrellet** [comment]
Same answer as under #185 :)
