### ISSUE TITLE
JOINT COMMITTEE FOR GUIDES IN METROLOGY Terms

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#169]
Pertains to:
- DK1-006
- DK5-011
- DK6-012
- DK9-020
- DK9-021

**DK1-006 ISO/TC 211 standards should aim to reuse other standards **
instead of crafting new definitions when the subject is not geospatial-specific and already standardized in other committees or organisations. For the science of measurement and its application, [JCGM 200:2012] is probably the reference document that should be used.
JOINT COMMITTEE FOR GUIDES IN METROLOGY. JCGM 200:2012, International vocabulary of metrology – Basic and general concepts and associated terms (VIM) [online]. 3rd edition ed. Joint Committee for Guides in Metrology, 2012. Available from: https://www.bipm.org/en/publications/guides
	See other DK-comments for specific places where [JCGM 200:2012] could be used.
Note: as far as we can see, the above standard will be published as ISO/IEC Guide 99, see also https://www.iso.org/standard/82585.html.

**DK5-011 The source is missing at the present definition.** 
However, if one look into the ISO/TC 211 Multi-Lingual Glossary of Terms (MLGT) and look for the term “measurand” then it appears, so we suggest to reuse the definition for the term as given in MLGT to ensure consistent use of terminology across the standards in the ISO 19100 series.
	If the present definition is kept then we suggest adding the source of this definition: [JCGM 200:2012, 2.3].
If the second option in our comment is used (we recommend to do so), the replace the definition with the following “particular quantity subject to measurement
[SOURCE: VIM:1993, 2.6]”. See also https://isotc211.geolexica.org/concepts/559/	

**DK6-012 “measure” is not a term specific to the GML domain.** 
Although reuse is good, the main problem here is probably that measure was not properly defined earlier. Reuse concepts from [JCGM 200:2012] wherever possible.
	”measure” seems to be the same as ”quantity value”, [JCGM 200:2012, 1.19].
Update the term entry accordingly. Keeping ”measure” as preferred term and adding ”quantity value” as accepted term would be ok, given the tradition of using ”measure” in the geospatial domain.

**DK9-020 Update source**	
Change the source to the newer [JCGM 200:2012, 3.8].	

**DK10-021 Consider to use the definition of the term as it is defined in [JCGM 200:2012]** 
which contains an entry “measurement unit”.	
Change 3.25 to reuse  [JCGM 200:2012, 1.9]. Decide what the preferred term should be in 19156 and update the rest of the document consequently.

**Comment by KathiSchleidt** [comment]
**DK5-011** The source is missing at the present definition.
Pertains to "Measurand". As this term is never used in the document, I'd delete

**DK6-012** “measure” is not a term specific to the GML domain. **Won't fix**
As this work is done within OGC/ISO, prefer maintaining consistency, as I don't really like the JCGM version:
```
1.19
quantity value
value of a quantity
value
number and reference together expressing magnitude of a quantity

```


**DK9-020** Update source
Pertains to 3.23 sensor
Update Source to
[SOURCE: JCGM 200:2012, 3.8, modified — EXAMPLES and NOTE deleted.]

**DK10-021**  **Won't fix**
proposes changing "Unit of Measurement" to “measurement unit” from JCGM
I am AGAINST, as UoM is the commonly used term

**Comment by KathiSchleidt** [comment]
DK6-012 “measure” 
Example: frequency of light would be a measure under the GML definition, not a quantity under quantity value

**Comment by KathiSchleidt** [comment]
Adding
**TMG-019**
3.10  measurand	ed	the authoritative source is missing	please add the authoritative source reference as shown below:
[SOURCE: VIM:2007, 2.3]

Same solution as above, remove measurand from terminology as never used in text

**Comment by dr-shorthair** [comment]
Measurand ~= observed-property 
We added it to the glossary earlier so the VIM people would find it. But Maybe it would be better as a NOTE against the definition of ObservedProperty?

**Comment by KathiSchleidt** [comment]
Nice idea. How about the following text under the ObsProp definition:

NOTE: in some communities, the ObservedProperty is referred to as the measurand

**Comment by sgrellet** [comment]
@KathiSchleidt 
on 3.24 sensor
I still read "[SOURCE: ISO/IEC Guide 99:2007, 3.8, modified — Example and Note 1 to entry were deleted.]" for the source
instead of [SOURCE: JCGM 200:2012, 3.8, modified — EXAMPLES and NOTE deleted.]  (see DK9-020 Update source)
Any reason from another issue not to change this ?
