### ISSUE TITLE
Terminology in situ

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#172]
**-009 In Earth Observation (EO) the opposite to ‘in-situ’ would be ‘remote’** 
and the distinction is rather made to describe the relation (distance) between the sensor and the phenomena, which becomes especially useful if this distance has an influence on the observation result.
The definition given here, however, would render most ‘remote’ observations in EO at the same time ‘in-situ’, as most of the Earth’s surface could be considered being in its ‘natural surrounding’.	Remove Note 1 and define ‘In-situ’ as:
observations performed close to where a phenomenon occurs. The main characteristic of such observations is that distance has no or only negligible (within uncertainty) influence on the value of the property observed. 
Note 1 to entry: The effect of the distance on the acquired data is the main distinction criteria between ‘remote’ and ‘in-situ’ observations.
Note 2 to entry: normally without isolating it from surrounding phenomena (its environment) or altering its pre-observation state.
Note 3 to entry:  In-situ observations often require either direct physical contact or small distances between the sensor and the observed phenomenon.

KS: should be clarified by the renaming of the German version of OMS

**Comment by KathiSchleidt** [comment]
Won't fix, clarified by renaming DE version

**Comment by strobpr** [comment]
Not sure what is meant by 'renaming DE version'. I see no language or country elements in this.

**Comment by KathiSchleidt** [comment]
won't fix, adding in-situ, #202.

German title of OMS (currently Erdbeobachtung und Erdmessung, translates to earth observation and earth measurement) is confusing, will be modified to Beobachtung, Messung und Proben (translates to OMS). This has been agreed by DIN and Austrian Standards

**Comment by strobpr** [comment]
Are both spellings "in situ" and in-situ" considered valid, or will this be harmonised?

**Comment by KathiSchleidt** [comment]
"in situ" and "in-situ" should be harmonized
To my view, use of the - is wrong, should be _in situ_ and _ex situ_

**Comment by strobpr** [comment]
From a linguistic perspective I understand that 'in-situ' might not be ideal. What I would however weigh in, is that using a hyphen makes a term continuous and as such more unique, consistent and easily searchable. E.g. can such terms be used in naming files without the very odd practice of having blanks in filenames.
I would therefore favour 'in-situ'.

**Comment by ilkkarinne** [comment]
The term "ex-situ" was corrected to "ex situ" in Clause 3 by the ISO Central Secretariat, but in the text such correction were not made.

I'm not native enough really to choose one over the other grammatically, but a style guide I randomly found in the Internet (Society of Petroleum Engineers Style Guide, 2019) seem to make a distinction on whether the words are used as adverbs or as adjectives directly preceding a noun: https://oilpatchwriting.wordpress.com/2010/07/09/in-situ-in-real-time/

The style guide mentioned is available at https://www.spe.org/authors/docs/SPE_Style_Guide_2019.pdf

**Comment by KathiSchleidt** [comment]
Based on a) the ISO CS edit and b) common usage, should be without the '-' as we're dealing with a terminology, not a data model field

**Comment by KathiSchleidt** [comment]
Italic stated by TMG 

-106 ex situ

Note that Latin text shall be written in italic font.

#187
