### ISSUE TITLE
Definition FoI

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#173]
**-010 This definition sounds rather circular** 
and does not clarify what a ‘subject’ is (in respect to the ‘object’ other definitions mention, which are defined neither).	
Replace ‘feature’ by ‘phenomenon’ (after proper definition, see above)	

KS: Don't think changing FoI to Phenomenon-of-Interest makes anything better

**Comment by KathiSchleidt** [comment]
Won't fix, as reduces clarity in the standard.

**Comment by sgrellet** [comment]
Agreed. 
And Feature already brings along the notion of Phenomenon (19101 : "A feature is an abstraction of a real world phenomenon”)
