### ISSUE TITLE
Definitions Observation and Observer

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#175]
Issues with definitions for Observation & Observer
- DK7-014
- -015
- DK8-016

**DK7-014 The definitions seems to be circular:**
observation
act carried out by an observer […]
observer
identifiable entity that can generate observations […]
	Consider whether the definitions should be changed.

KS: text taken out of context, works for me

**-015 The definition given here extends the meaning of the terms ‘observer’ and ‘observation’ also to models and their results.** 
This is in stark contrast to the use of these terms in practical communities like CEOS. In Earth Sciences it is crucial to be able to distinguish between the results of observations (acquired of real world phenomena) and results of models (based on algorithms and assumptions), as one are facts and the other fiction.
Speaking of ‘objects’ is likewise a possible source of confusion as some phenomena, such as e.g. gravity or precipitation, are not easily tied to specific ‘objects’ (which also lack a definition).	
Observation (the process) is the act of determining the value of a property by interacting with the phenomenon using a sensor. The obtained values are factual (observational) data and are often themselves referred to as observations (the result of the process).
Note 1 to entry: the observed value is usually complemented by an uncertainty
Note 2 to entry: an observation (result) by definition represents a sample of a phenomenon (otherwise it would be identical with the phenomenon) but is not necessarily representative of the phenomenon
[Source: ISO 19156:2011, 4.11, modified and extended, Notes added]

KS: again, works for me, we DO provide modelling results as observations!

**DK8-016 This definition seems to be a little lengthy and with some overlap to 3.13 (see previous Danish comment).**
In order to make the definition, short and to the point as well as reducing the overlap to 3.13 we suggest deleting the second half of the definition. The result will the following definition: “identifiable entity that can generate observations”.

**Comment by KathiSchleidt** [comment]
Won't fix, stem from lack of understanding of the standard

**Comment by strobpr** [comment]
Why not add a a few words that allow to understand the standard?
I talked to dozens of experts in the field and while we all agree that results (data?) of simulating a phenomenon (through an algorithm) technically look equivalent to results of observing it (by means of a sensor), every single one strongly recommended NOT to call both 'observation result'.

**Comment by joergklausen** [comment]
> Why not add a a few words that allow to understand the standard? I talked to dozens of experts in the field and while we all agree that results (data?) of simulating a phenomenon (through an algorithm) technically look equivalent to results of observing it (by means of a sensor), every single one strongly recommended NOT to call both 'observation result'.

Full support! Observation and model should not be confounded. The word 'result' on its own can cover both, observation and model, but if it is explicitly constrained by adding 'observation', then, well it is an 'observation result' = result of an observation (and not a model).

BTW: I personally make no distinction anymore between observation and measurement.

**Comment by ilkkarinne** [comment]
Link to the separate issue regarding the definition of Observation #203

**Comment by KathiSchleidt** [comment]
On the issues with "observation result", unclear what this pertains to. To my reading, the **Observation** definition also works for models, observer becomes the running model instance, procedure the model itself.

There is a grammatical issue in the "Observation" definition, either "with" or "is" must go from the last part of following definition

act carried out by an observer to determine the value of an observable property of an object (feature-of-interest) by using a procedure, _with_ the value _is_ provided as the result

**Comment by KathiSchleidt** [comment]
Add Note to Observation
NOTE 1: the observation concept defined here can also pertain to simulations.

**Comment by KathiSchleidt** [comment]
The additions to the definition of Observation from the 2011 version are due to extensions of the underlying data model. Also pertains to #203

**Comment by dr-shorthair** [comment]
Probably the key factor that distinguishes a sensor-observation from a model-estimation or forecast, is that a sensor-observation is initiated by a physical (or chemical (or biological)) stimulus, which is than converted to a number. A model-estimation is initiated computationally, not physically.

**Comment by joergklausen** [comment]
This is a very useful distinction and I think it would be helpful to include this in the document.

**Comment by ilkkarinne** [comment]
Is still see no clear distinction between an Observation captured using a Sensor which contains complex information processing and one created using a model-estimation based on real world input and the set of processing rules for deriving the Observation result from those inputs.

**Comment by KathiSchleidt** [comment]
I think we're all clear on the fact that **Observations** can be used to provide simulation results. Open question is if the proposed NOTE to the definition above together with the following NOTE already provided for the Observation-sem req suffices, or if further clarification is required. Moving back to "in-discussion" pending further feedback

`NOTE	It is important to note that the terms ‘observation’, ‘interpretation’, ‘forecast’, ‘simulation’ do correspond to this definition. This aspect is further clarified in Clause 7.`

**Comment by sgrellet** [comment]
Several points here 

- Grammatical issue in the "Observation" definition -> I'd remove the '_is_' from the current definition => "act carried out by an observer to determine the value of an observable property of an object (feature-of-interest) by using a procedure, with the value  provided as the result"

- +1 to adding a note -> do feel the content already provided for _/req/obs-cpt/Observation/Observation-sem_ contains what was proposed to be added above (NOTE 1: the observation concept defined here can also pertain to simulations.). So I'd only add what @KathiSchleidt quoted right above (_It is important to note that the terms ..._)

**Comment by joergklausen** [comment]
> Note on the use of the term "phenomenon" - the reason we did not use this term as proposed above has to do with the core "feature" definition from 19101: **feature** abstraction of real world phenomena Note to entry: A feature may occur as a type or an instance. Feature type or feature instance shall be used when only one is meant. [SOURCE: [ISO 19101-1:2014](https://www.iso.org/standard/59164.html), 4.1.11]
> 
> Reusing "phenomenon" with a divergent meaning would not increase readability of the text

I can't find a definition of 'phenomenon' in the current draft, but also no reference to another document.

**Comment by joergklausen** [comment]
> NOTE 1: the observation concept defined here can also pertain to simulations.

My last 5 cents:
I like this NOTE 1, more so than the 'NOTE It is important to note that the terms ‘observation’, ‘interpretation’, ‘forecast’, ‘simulation’ do correspond to this definition. This aspect is further clarified in Clause 7.' I agree that the cocepts here could be applied to models/simulations, but the distinction between observation ('fact') and simulation ('fiction') must be clear whenever a 'result' is described. I am concerned that this distinction is not appreciated if the terms are used as almost synonyms. The issue may be not so  much the act of observing, but the nature of the object ('real' vs 'virtual').

So, rather than to add 'NOTE It is important [...]' I propose to expand NOTE 1

NOTE 1: The observation concept defined here can also pertain to interpretation, forecast, simulations where the object (feature of interest) is a fictitious* representation of a real-world object.

*instead of fictitious: artificial, synthetic, virtual

**Comment by sgrellet** [comment]
> I can't find a definition of 'phenomenon' in the current draft, but also no reference to another document.

It's in section 3.7
`3.7
feature
abstraction of real-world phenomena`

**Comment by sgrellet** [comment]
>  is a fictitious* representation of a real-world object. *instead of fictitious: artificial, synthetic, virtual

I'd rather not add this as, as mentionned in #173, using the term "Feature" already brings the notion that is an abstraction of a real-world object/phenomenon (abstraction -> artificial, synthetic, virtual).

I guess the essence of the Note we want is that the concept of Observation encompasses  ‘observation’, ‘interpretation’, ‘forecast’, ‘simulation’

**Comment by strobpr** [comment]
3.7 defines 'feature' as an 'abstraction of a phenomenon'. But 'phenomenon' remains undefined (leaving it in the end open what a feature is).
The 'feature definition goes back to ISO 19101 which as well has no definition for 'phenomenon' but several mentions of 'phenomena' as e.g. in:
4.1.18 geographic information
_information concerning phenomena implicitly or explicitly associated with a location relative to the Earth_
In the intro it speaks about 'real world phenomena' which implies that there are also other types.
As said, Geolexica doesn't help, the closest (and most fundamental) it provides is a definition for 'entity' (ISO 19119) and the main question I ask myself is why was that not used instead of 'phenomena' when defining 'feature'? Does ISO see a difference between an 'entity' and a 'phenomenon' and if so which exactly? (I do have an opinion on this but don't want to bias the audience.)

**Comment by strobpr** [comment]
Regarding the note to be added, I would recommend to rephrase to:

_Note 1: The observation concept defined here can also pertain to acts such as modelling, interpretation, forecasting, or simulation where the observer, the observed property, or the feature of interest do not have objective reality._

The concept of 'objective reality' is used in the definition of 'entity' (ISO19119) in contrast to 'conceptual reality', which I assume is what is meant above by 'fictitious, artificial, synthetic, or virtual'. So it would solve finding the right word and remain consistent with established ISO definitions.

**Comment by KathiSchleidt** [comment]
**OMS SWG Meeting June 8th 2022**
We decide to leave phenomenon out of the discussion as nailed down too hard in the core feature definition. We cannot change such core definitions (feature defined as an abstraction of a phenomenon comes from 19101) in this standard. 

No Note, as we do not want to equate the semantic concept of "Observation" with "Simulation". Necessary clarification is provided within the model under Observation-sem

**Comment by strobpr** [comment]
I thought we agreed on a note and don't understand what you mean by _we do not want to equate the semantic concept of "Observation" with "Simulation"_

Isn't it the core of the discussion, that in ISO's world "observation" includes "simulation"? If so, and from the current definition this is only very indirectly evident, a respective note is necessary to warn communities who desire a distinction that they would need to make it explicit.

**Comment by strobpr** [comment]
On "phenomenon": I understand if you don't want to touch it, but as 19156 makes use of it in several definitions, it would be good to have an idea of what is meant by it. Is there a defintion anywhere in the ISO world? If not, is there any passage in 19101 or elsewhere (I don't have access to ISO texts) that could help in understanding what is meant by the term?

**Comment by KathiSchleidt** [comment]
@strobpr 
There is a difference between a class definition (where we have a note explaining that one can also provide simulation data vs. a definition of the term Observation equating Observation with Simulation. To my understanding, stating in the definitions that an Observation is a Simulation would be wrong

Phenomonon and other ISOs, the definitions clauses of the other ISO standards are available via the preview functionality. For access to the full standard, please contact your CEN or ISO representative (we have to do the same)

**Comment by strobpr** [comment]
Now you find me really confused! Wasn't it all about the ambiguity of the current definitions:
_3.13
**observation**
act carried out by an observer to determine the value of an observable property of an object (feature-of-interest) by using a procedure, with the value is provided as the result
3.14
**observer**
identifiable entity that can generate observations pertaining to an observable property by implementing a procedure
Note 1 to entry: An observer is an instance of a sensor, instrument, implementation of an algorithm or a being such as a person._
From the latter, and in particular from _"implementation of an algorithm"_ it follows implicitly that a model or simulation would fall under the (semantic) definition of "observer' and hence "observation". (I guess others in this chat shared this impression. @joergklausen @sgrellet) 

Please correct me if this is a misinterpretation, as it caused my intervention in the first place. I never had any objections declaring a (functional) 'class definition' for 'observation result' applicable also to results of 'forecasts', 'simulations' and alike. 
But if the current (semantic) definition of 'observation' is meant to exclude 'simulation' (which is exactly what I'm after) it should be changed!

**Comment by dr-shorthair** [comment]
On 'sensor observation' vs 'model estimation' @ilkkarinne wrote
> I still see no clear distinction between an Observation captured using a Sensor which contains complex information processing and one created using a model-estimation based on real world input and the set of processing rules for deriving the Observation result from those inputs.

Hmm. I thought I was clear about that. A sensor observation involves a physical stimulus. A model estimation does not. 
You may or may not think the physical stimulus is important, but it is a clear, objective, differentiator. 

On 'factual' vs 'simulated' - I find this classification unhelpful. In particular, 'factual' is potentially a value-laden term. 
They are all estimates, with potentially quantifiable uncertainty. From the dawn of classical philosophy we have been grappling with the meaning of facts and truth, and I don't see us clearing that up in a sentence here. 

We agree that all of these processes involve  algorithms, models and computation, so I don't think they can be usefully separated on those grounds. The only objective differentiator mentioned in this thread is the presence or not of a physical stimulus.

**Comment by ilkkarinne** [comment]
@dr-shorthair : I do get your point regarding sensor observations when the sensor is just idly waiting for a stimulus to trigger the observation act. It should be noted that we also want to have observations is the scope of OMS that are primarily initiated by a particular action of an observer to observer some characteristic of the FoI. In this case the observer has a capability to create observations of one of more observable properties of the FoI using one or more observing procedures, but some action of the observer is required to actually capture these observation at a time. One such case would be a human observer observing the vicinity of a friend on the street: the pure capability of seeing and recognising another person is not not enough, one has to pay attention also at the right moment. There is of course still a physical stimulus present too in this case.

One important class of observations are observations made of FoIs that only exist in the digital realm, such as characteristics of pieces of software or digital simulated worlds. A particular case I have in mind is counting and recording the number of lines-of-code in of a software program, or creating statistical observations on characteristics of a digital dataset. In these cases I see no direct physical stimulus, but these observations intend to capture truthful estimates of a their digital FoIs, and do not really involve simulations or models either, as their native realm is already a digital one.

The concrete problem that we are trying to solve here is that for some communities the terminological distinction between observations that "are intended to capture truthful information about a happened phenomenon" and results of simulations of such phenomena carried out in a digital environment is important. Some simulations (or model estimations) are predictions while some provide information of a past state of the FoI, which maybe verifiable against results of sensor observations, at least in principle.

I'm not entirely certain if the issue is more in distinguishing the sensor observations from predictions (regarding a future state of the FoI) or from any simulation based information which is produced by an algorithm and model rules without any direct input from the real-world sensors.

**Comment by KathiSchleidt** [comment]
I worry about adding the additional terms to the Terminology section at this late date without the necessary discussion, to my view, if we really want to sort this issue (not just a quick&dirty fix), we'll have to go for a further commenting round (if nothing else, the terms factual vs. simulated observation are currently not to be found in the further text, thus implies serious rewrites), and postpone publication to 2023 :(

I still don't understand the relevance of adding these terms to the Terminology, as I'd been under the impression that our goal was to create an updated model, document this as required. I nowhere see the goal of providing additional terminological concepts to Geolexica. The way this is going, it may just be easier to dump the Oxford Dictionary into the Terminology section! ;)

Within the model (Observation-sem), the topic is clarified.

**Comment by dr-shorthair** [comment]
I did not say that the observation was *triggered* by a physical stimulus - the vain proceed can be triggered by all sorts of business rules or ancillary observations. But a physical stimulus is involved in a sensor observation. 

This may not be the critical differentiator in applications, but it is a differentiator nevertheless.

**Comment by ilkkarinne** [comment]
Agree with @KathiSchleidt: we should not add any new terms at the last moment, especially if we do not use those in the text.

Also as mentioned by Peter Parslow in one of our SWG sessions: the terms defined in a standard are to be interpreted in the context of that standard. In the context of OMS, ```observation``` is a concept used for describing both the "sensor observations" and model estimations.

**Comment by strobpr** [comment]
"_observation is a concept used for describing both the "sensor observations" and model estimations_"

Which brings us back to the start. Why not simply make this important point clear and explicit to implementers of the standard and users of the Geolexica (which is probably the larger group) by adding a simple "Note" as suggested earlier? Maybe shorten it by leaving the explanation out and it becomes:

"_Note x: The observation concept defined here can also pertain to acts such as modelling, interpretation, forecasting, or simulation._"

This is almost identical to @ilkkarinne 's statement above. It doesn't matter whether you add it to 3.13 or 3.14 (which already has a Note 1), in either case it fulfills its purpose.
Who would object to that or whom does it hurt?

**Comment by sgrellet** [comment]
Agree with @KathiSchleidt  and @ilkkarinne. No need to rewrite what they say.
That's too sensitive an edit in Terminology, in a rush and not having time to assess the various side effects of it.
This specific topic was the subject of a SWG webconf decision (see OMS SWG Meeting June 8th 2022 above).
I suggest we stick to the decision

**Comment by strobpr** [comment]
Unfortunately, I could not attend the meeting on the 8th. I thought the week before it was decided to put a 'Note' for more clarity (no change in meaning, no new terms, not sensitive) and hence the discussion here. Seems I got it wrong. Sorry for wasting everyone's time.

**Comment by ilkkarinne** [comment]
Thank you for your time and bringing this issue to discussion @strobpr. We tried to agree on the note in meeting of 8th, but could not come up with a formulation that would not cause additional difficulties by equating sensor observations with model estimation on the terminology level. Unfortunately we have to stick to resolutions made in the meetings or will not be able to finish in time.
