### ISSUE TITLE
Definition Property

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#176]
**-017 Not all phenomena that have properties are objects (e.g. the ‘big bang’).**	
property
attribute which is observable
[SOURCE: ISO 19143:2010, modified] 

To be complemented by defining 
phenomenon
A phenomenon is an entity that has at least one property and is referenced by an identifier

KS: nice if you can redefine phenomenon, but goes out of line with wider ISO definitions

**Comment by KathiSchleidt** [comment]
Think the issue is that the commenter cannot abstract, not capable of modelling "the big bang" as an electronic object
Won't fix

**Comment by strobpr** [comment]
Maybe the misunderstanding is in what exactly is an object. there is no definition in 19156 and in Geolexica one reads: "entity with a well defined boundary and identity that encapsulates state and behaviour". That obviously stems from programming and leaves a lot of room for interpretation (what is a 'well defined boundary'? In which sense or dimension?)
Are gravity or a dream both objects?
The reason to add a definition for 'phenomenon' is that Geolexica doesn't have one and going into 'wider ISO definitions' is asked a bit much for someone who is 'only' interested in Earth Sciences.
BTW the definition of 'property' in ISO refers to 'attribute' and vice versa. Not very helpful in understanding why we would need two separate terms.

**Comment by joergklausen** [comment]
I-ADOPT conceptual model is pretty clear on what property is. I like the definition given at the top (attribute which is observable).

I would not also not refer to the 'big bang' as an 'object', rather as a 'phenomenon'. The 'object' in this context is the 'universe', isn't it? Although that just started to come into existence from nothing ... thus, the object changed quite a bit as part of the phenomenon.

**Comment by hylkevds** [comment]
Just like in the ontology world, where everything is a Thing (the definition of Thing is the opposite of an empty set), in the O&M world everything can be an Object. This includes events and abstract concepts and phenomenons.

In this discussion we can Observe the concept of Object to be the cause of much discussion: Observed Property: Amount of discussion; FeatureOfInterest: The concept of Object; result value: much.

It only depends on your perspective and system definition. How one chooses their Objects depends on ones goals.

**Comment by KathiSchleidt** [comment]
Can't kill Abby!

Ask Reese if possible

**Comment by KathiSchleidt** [comment]
Abby has been restored, see #201
