### ISSUE TITLE
Definitions sample and sampling

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#178]
**-019 Opposite to the too wide definition of ‘observation’ and ‘measurement’ this definition is too narrow.** 
Samples are often not ‘objects’ (in the sense of the definition in Geolexica which requires a ‘well defined boundary’)
In many cases in EO nomenclature also ‘samples’ (in the sense of ‘pixels’) are not representative for anything but themselves.	
sample and sampling
A spatially, temporally or in any other dimension or attribute limited subset of an entity.
Note 1 to entry: The process of obtaining a sample is called sampling.

KS: think should be fixed with renaming DE version of OMS

**Comment by KathiSchleidt** [comment]
**-049 or is an object created with the intention to sample the real-world object,**	
Please review wording: "is an object created with the intention of acting as a sample of the real-world obkect" or "is an object created with the intention of sampling the real-world object"?	

Pertains to 8.2.6

**Comment by KathiSchleidt** [comment]
**-019** Won't fix to align with EO Pixels

**-049**
Refers to 
`NOTE 2 This object is the real-world object whose properties are under observation, or is an object created with the intention to sample the real-world object, as described in the Sampling part of section 7. An observation instance serves as a propertyValueProvider for its feature-of-interest.`

May be a bit clearer by adding "it" as follows:
... object whose properties are under observation, or **it** is an object created ...

**Comment by sgrellet** [comment]
**-019** : agreed

**-049** : Both proposed sentences seem to cover the notion of 'proxy' to the ultimate FoI.
Do we have proxies than are not type 'Sample' ? Sample in the sense of the conceptual Sample schema 'A Sample is an object that is representative of a concept, real-world object or phenomenon.'

If not I'd suggest rephrasing like this : "....or is an object created with the intention of acting as a sample of the real-world object, in the sense of section 11.2.2 and as described in the Sampling part of section 7.2".

**Comment by KathiSchleidt** [comment]
Non-sample proximate FoI: To measure the brightness of the sun, instead of burning your retina/instrument by looking at the sun directly, you measure the reflectance off of a white sheet of paper.
PFoI: the sheet of paper
UFoI: the sun
Sheet of paper is not a sample of the sun (if so, would at the most be a pile of ash ;) )

**Comment by ilkkarinne** [comment]
I'm ok with adding back the reference to Clause 7.2, as it does not only discuss Samples, but also pFoIs in general

**Comment by sgrellet** [comment]
Ok with the 'My Merge' above with one slight question
- Do we go for "observable" or "observed" in bold + italic below ? 
It may look like splitting hairs but, In the 'sun' example above, the sun can be directly observed under some conditions. 'observable' alone sounds too 'generalist' to me. I'd suggest either we go for 'observed' (alone) or we add some more elements next to 'observable' such as '_...not directly observable for the observedProperty / featureOfInterest / observingProcedure considered_'

NOTE 2 This object is the real-world object whose properties are under observation, or is an object used as a proxy for a real-world object that is not directly **_observable_**, as described in clause 7.2 Sample Schema. An observation instance serves as a propertyValueProvider for its feature-of-interest.

**Comment by ilkkarinne** [comment]
I get your point @sgrellet. I guess we can use "..as a proxy for a real-world object that is not directly observed,..", but it seems a bit and circular. What if we say "..as a proxy for a real-world object that is not directly observable by the observer,.."?

**Comment by KathiSchleidt** [comment]
To my view, the directly observable by the observer doesn't really make it better. I'm fine with observable.

**Comment by sgrellet** [comment]
ok, it may just be me. Let's proceed with your suggestion

**Comment by hylkevds** [comment]
_directly observed_ versus _directly observable_ does make a difference. In Kathis sun case, it is directly observable, it just hurts a bit ;) 
But I'm fine with both of those options. _observable by the observer_ is redundant.

**Comment by KathiSchleidt** [comment]
So are we agreed on my merge? Copied in here for reference:

`NOTE 2 This object is the real-world object whose properties are under observation, or is an object used as a proxy for a real-world object that is not directly observable, as described in clause 7.2 Sample Schema. An observation instance serves as a propertyValueProvider for its feature-of-interest.`

**Comment by ilkkarinne** [comment]
I agree with Kathi's "merge"

**Comment by KathiSchleidt** [comment]
As all 4 of us seem to be in agreement, will push to resolution agreed
