### ISSUE TITLE
Potential Observation

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#18]
Source: http://ogc.standardstracker.org/show_request.cgi?id=575
In various contexts, we've identified a requirement for a description of a potential observation; this is in close alignment with the O&M Observation, and could be modeled via a common abstract Observation type carrying the observation associations Domain, Phenomenon and ProcessUsed (but not requiring a mandatory Result or Phenomenon Time)

This requirement has come up in the following contexts:
* INSPIRE: for the INSPIRE Environmental Monitoring Facility Data Specification there was a requirement to provide information on what types of observations can be expected from a facility. For this purpose, we defined the ObservingCapabilities FT
* Coverage: Within coverage models, O&M Observations are often utilized to provide relevant measurement metadata. In these cases, the Result is set to nil, as the actual result is the container carrying the O&M Observation. While this is a pragmatic approach, it is formally wrong
* Alignment with SensorThings API (STA): In STA, the O&M Concept has been subtly modified, whereby the O&M Observation has been split into a DataStream (Potential observation) and a set of Observations (what is seen as the Result in classic O&M). Introducing a Potential Observation in O&M would allow for better alignment between these related OGC Standards

**Comment by KathiSchleidt** [comment]
Opposite, but strangely related is a recommendation from the SoilIE:
1.	Create feature or data type to support attributed property values, either by defining an XML implementation of OM_Observation where all properties except result are optional, or a new datatype that uses OM_Observation as the pattern for structure.

**Comment by ilkkarinne** [comment]
If we had a concept of an Observation template, with all properties allowed to be missing, we could use the same thing to all the following:

- the observing capabilities (what is available),
- the soilIE issue on the attributed property values, and
- the optimization of the common properties in a homogenous Observation collection (#2)

**Comment by KathiSchleidt** [comment]
Is there a UML modelling mechanism that allows us to up the cardinalities on associations? Think this could work via derivation through restriction in XSD, but unclear how to define this in UML

**Comment by ilkkarinne** [comment]
I think the class could be the same in all of the cases (UML and XML), the different semantics would be carried by the association (property) name linking it the container (facility, collection etc.)

**Comment by KathiSchleidt** [comment]
to my view, all the associations from the core observation should be covered; only change is upping the cardinality on them (usually just the lower bound)
thus, in the primal abstract observation, all associations would be there but optional, depending on the requirements these could then be individually incremented (so the INSPIRE ObsCaps would have the same cardinalities as in the current O&M observation EXCEPT for the result, this would stay at 0)

**Comment by ilkkarinne** [comment]
@KathiSchleidt: I think we agree (as often), it would make a lot of sense to have an abstract observation class with relaxed cardinality of all properties. I think requiring property cardinality of 1 or more instead of 0 or more in a derivative UML class should not be a problem (just need to check the details of doing this the right way with Enterprise Architect to keep the UML->GML generators happy.

What I meant in my earlier comment was that the same ObservationTemplate (extending the AbstractObservation) class could be used also for expressing the repeated/template property values within an ObservationCollection.

**Comment by KathiSchleidt** [comment]
@ilkkarinne agreed! (as so often :) ) And fairly convinced that we'll find quite a few potential usages of such an abstract observation (I much like the observation collection addition to this list :) )

**Comment by dr-shorthair** [comment]
I am focusing more on the OWL/RDF view these days. The open-world assumption means that while the ontology can express _expectations_ around cardinalities, there is no corresponding notion of 'validity' of a data instance. So a missing result merely means 'we don't know what it is yet ... which is largely consistent with your requirement. 

In the RDF world we use 'shapes' (in ShEX or SHACL) for validation, You could have different shapes based on the same vocabulary for the different use-cases. 

But I guess that ISO 19103 UML is still the expectation for modeling?

**Comment by KathiSchleidt** [comment]
Unfortunately yes, we're still in the old UML school of modeling. @dr-shorthair as I do know you've done very interesting UML modelling bits in your previous life - any tips on how to do this type of modelling by restriction in the clunky UML/XML world?

Also, realized that a further usage for such an abstract observation pertains to the SWE Offering concept

**Comment by sgrellet** [comment]
"Also, realized that a further usage for such an abstract observation pertains to the SWE Offering concept" -> yes. Was a point discussed in INSPIRE D2.9. Was also mapped in INSPIRE D2.9 against SOS hydro profile GetDataAvailability.

**Comment by KathiSchleidt** [comment]
ok, found the reference I was looking for on derivation by restriction in UML vs XML:
https://www.seegrid.csiro.au/wiki/AppSchemas/UmL2GMLAS#Derivation_by_restriction

**Comment by dr-shorthair** [comment]
The SEEGrid Wiki got migrated here https://confluence.csiro.au/display/seegrid/Converting+a+UML+model+to+a+GML+Application+Schema#ConvertingaUMLmodeltoaGMLApplicationSchema-Derivationbyrestriction but the tree didn’t get rebuilt properly.

**Comment by denevers** [comment]
A quick google around returns 

"Although it is never mentioned explicitly on 640 pages, UML 2.0 introduces a covariant overriding rule for operations and properties. Hence, a subclass over- riding a superclass operation may replace the parameter types by subtypes of them."

But all mentions seems to go back to the same paper.

**Comment by hylkevds** [comment]
This is very closely related to #2

**Comment by KathiSchleidt** [comment]
I've been through the CSIRO docs, 2 problems:
1. While various restriction options are mentioned, all pertain to data types, not cardinality, which is what we'd need here (it's really more of a hack to transition the fine line between UML/XML vs. RDF/OWL)
2. I can't open the example URL (pwd protected), and my request for a user hasn't been successful. What's available at: https://www.seegrid.csiro.au/wiki/bin/edit/AppSchemas/XmlSchemaXmlSchemaDerivationByRestriction?topicparent=AppSchemas.UmL2GMLAS

**Comment by KathiSchleidt** [comment]
@dr-shorthair what's the background to modeling the result as UML Composition? Does this really provide added value, or could this be simplified to a normal association?
Apart from my not understanding how I can do derived Composition in EA (I can do association and attributes :) ), I see this causing formal issues when linking to a coverage, maybe served by a WCS

**Comment by KathiSchleidt** [comment]
I've done a short UML sketch (whereby one doesn't see much in the UML :( ), in the following google doc together with a description of what I think I've done in EA - happy for any and all comments insights!
I admit I'd be happier just shifting this all off to an RDF world where we wouldn't have this issue, but until we can, this could prove an interesting workaround.

https://docs.google.com/document/d/1x9xB942MZwjEplOLjk2nohbb8OL2w2375k4UhyI4rFA/edit?usp=sharing

**Comment by dr-shorthair** [comment]
The reason it is modelled as a composition is that a result does not exist in the absence of the observation that generated it.

**Comment by sgrellet** [comment]
Sorry, if I missed something
I was surprized, at first, looking at the proposed modelling diagram. And, I think, my reading of the Derivation by Restriction discussion on the Seegrid link confirmed that feeling.
Most of the Seegrid link discussion is driven by XML processing software implementation

But the page also states "For example, in UML this concept typically requires use of an OCL constraint, rather than a core UML mechanism."
And actually, here, we are discussing O&M conceptual model (10-004r3) revision now, not its XML implementation (revision of 10-025r1).
So why not just having a classical subtyping process and use constraints (OCL) to restrict cardinalities ?

**Comment by dr-shorthair** [comment]
1. I do like 'Observer' to replace 'Sensor' - it is more general and captures the intent

2. I don't like 'Observing' to replace 'Procedure'. It is _not_ symmetrical with 'Sampling' and doesn't carry the right meaning. The general class is similar to prov:Plan. You could conceivably specialize to 'ObservingProcedure' and 'SamplingProcedure' but the suffix '-Procedure' is pretty important IMO.

**Comment by ilkkarinne** [comment]
Thanks for comments @dr-shorthair, renamed Observing into ObservingProcedure. Did not change the Sampling for now, as Sampling might not end up being a procedure in some case, but a feature or something else.

Also noted that I had not thought the restriction idea through completely: with the template association we now want to ensure that observedProperty, madeBy and usedProcedure associations and the resultTime and PhenomenonTime attributes are defined either in directly or by the template association. Thus the XML style derivation by restriction does not work. I've refactored the diagram into using constraints instead (in the fashion suggested by @sgrellet). In time these should probably be formulated as OCL expressions.

https://gist.github.com/ilkkarinne/fd9b76ec12ff5d8c6bf2172f34fe85dc

**Comment by dr-shorthair** [comment]
Note that in SSN `Sampling` is 'act of Sampling' - i.e. it is an event or `prov:Activity` like `Observation`. 
See https://www.w3.org/TR/vocab-ssn/#PROV_Alignment and https://www.w3.org/TR/vocab-ssn/#overview-of-classes-and-properties

**Comment by cportele** [comment]
Some comments after looking at the UML:

* +1 on Observing and ObservingProcedure. 
* In general I would prefer Sample over Sampling, but I guess that depends on the definition. Are there definitions of the types somewhere?
* Could we use Any instead of MD_Metadata as the type of the metadata property? That supports the use of MD_Metadata where it fits, but I don't have to invent another "metadata" property, if I want to use another type of metadata. 
* Instead of a stereotype "Type" it should be "interface". See ISO 19103.

**Comment by ilkkarinne** [comment]
Thanks for the comments @cportele. I'm in favour of relaxing the target of the metadata association to Any.

I too think that we more discussion on what we want to semantics we want to convey about the sampling-related stuff on the O&M core level. SSN defines concepts Sample and Sampling, the current 19156 describes SamplingFeatures and Specimen.

What I think we need to define in the core is an abstract extension point for more detailed information about the sampling strategy **to be defined in extending conformance classes**, possibly including stuff like the sampling feature (geometry), the sample entities (of which specimen is one specialization), and details about the process used for the sampling.

Personally I would like to leave room for Observation models where the process of sampling in order to get a sample can be described separately from the process of observing the properties of a sample to come up with the result, but I would not want to restrict the information about the sampling stuff into just the process description. Not entirely sure whether the "sampling strategy" term has the right level of abstraction and either.

**Comment by ilkkarinne** [comment]
Modified version of the UML now updated to https://gist.github.com/ilkkarinne/01d309bcda52d5d18815b2cc5707388f

Changed Sampling into SamplingStrategy (please suggest a better name if you come up with one), and also removed the Proxy association between the SamplingStrategy and the domain feature target. My initial idea is to introduce this association in the Sampling extension requirements class when specialising the SamplingStrategy to include a SamplingFeature

**Comment by dr-shorthair** [comment]
@cportele [wrote](https://github.com/opengeospatial/om-swg/issues/18#issuecomment-556962239):
> In general I would prefer Sample over Sampling, but I guess that depends on the definition. Are there definitions of the types somewhere?

In [SSN/SOSA](https://www.w3.org/TR/vocab-ssn/#Sampling-specification) 'Sample' is the result of a (act of) 'Sampling' so these concepts are quite different - in process-flow terms 'Sample' is an Entity, Continuant or Endurant, while 'Sampling' is an Activity, Process, Occurrent or Perdurant. 

@ilkkarinne [wrote](https://github.com/opengeospatial/om-swg/issues/18#issuecomment-557012288):
> Changed Sampling into SamplingStrategy

Do you intend for this to be a re-usable thing, like a Plan or Protocol? What's wrong with 'SamplingProcedure'?

**Comment by cportele** [comment]
> In SSN/SOSA 'Sample' is the result of a (act of) 'Sampling' so these concepts are quite different - in process-flow terms 'Sample' is an Entity, Continuant or Endurant, while 'Sampling' is an Activity, Process, Occurrent or Perdurant.

Yes, I thought the entity is meant, but obviously not (I was missing the entity=sample in the diagram). I will wait with further comments until the picture is more complete :)

**Comment by KathiSchleidt** [comment]
Very happy with the metadata relaxation, Any is far better and closer to reality :)
Observer is good (finally rid of the sensor onus :) ), not sure we need ObservingProcedure as to my linguistic view, Process covered the concept nicely (and can also be followed by a human)

I very much worry about dropping the featureOfInterest term as this has become well established in the community to refer to the object being observed or measured on, did I miss the discussion/agreement on changing this? And I miss the planned addition of the ultimateFeatureOfInterest

To the new sampling bit I fear I'm a bit lost, where did this come from? From my experience, information on the sampling strategy is best provided by the featureOfInterest of the Observation - whereby this feature is a Sample that provides the Sampling it isResultOf - further info on the strategy should go there. 
I would much like to add the SOSA additions to sampling to the Sampling part of O&M, is it does much to clarify the old ambiguity on sampled vs. sampling features!

**Comment by dr-shorthair** [comment]
@KathiSchleidt the treatment of sampling was one of the key improvements in W3C/OGC SOSA/SSN compared with the original SSN that came out of the W3C Incubator Group. Perhaps the quickest introduction is in the [PROV alignment](https://www.w3.org/TR/vocab-ssn/#PROV_Alignment) section of the Rec. which emphasizes the common patterns - 

- an act-of-observation generates a result which is a piece of information describing the state of some property of the feature-of-interest
- an act-of-sampling generates a result which is an entity that is representative of a feature-of-interest
- an act-of-actuation generates a result which is a change of state of some property of the feature-of-interest

They each follow a procedure and use an instrument or entity (an observer/sensor, a sampler, and actuator).

**Comment by KathiSchleidt** [comment]
@dr-shorthair I totally get (and adore) what you've done with SOSA (if nothing else, my own abstractable core much appreciates the common pattern across Observation, Sampling & Actuation :)

What I still cannot find though is the link that Ilkka put between the Observation and the SamplingStrategy, as to my view this is available from the domain feature acting as the FoI

I could imagine a link to the SOSA Sampling being used for the creation of the FoI, whereby I would then see it as a pragmatic (and formally redundant) helper association similar to the ultimateFoI

I have added another issue on including the new SOSA Sampling as a replacement for the current Sampling Features part of the standard

**Comment by KathiSchleidt** [comment]
Dear all - as this issue was becoming EVERYTHING and ANYTHING, I've now mostly disaggregated, whereby all new issues mention this one, so easy to follow.

Also, inspired by the request on Alignment of terminology with other observation models #26, I've created a google sheet aligning O&M 2.0, SOSA, and the current status of O&M 3.0

If folks have other ideas on naming, please grab some columns to the right and show you're version
But, please try and do examples based on the current agreement (I've been retaining the O&M 2.0 names wherever we have not reached agreement on changes)

Comment link: https://docs.google.com/spreadsheets/d/1RbZtW8rDRk7n7oDoNH0SONPm1uZ29dkAPByXwddOvOY/edit?usp=sharing
If you want edit rights, please request

**Comment by ilkkarinne** [comment]
@KathiSchleidt: I guess you used https://www.w3.org/TR/vocab-ssn/#OM_Alignment as the basis for the SOSA - O&M 2.0 relations?

**Comment by KathiSchleidt** [comment]
For the moment the mapping is based on experience and common sense, please tell me where I've done something not aligned

**Comment by ilkkarinne** [comment]
I did not check the mappings @KathiSchleidt, you probably have much better knowledge in this than me. I just remembered that the SSN/SOSA spec contained this O&M alignment module and thought that it might save some time.

**Comment by KathiSchleidt** [comment]
Interesting application - use as a request for subsequent tasking.
Observing Capability can be requested to see who can perform this

**Comment by KathiSchleidt** [comment]
Attributes from the INSPIRE ObservingCapability for reference:
* ObservingTime (TM_Object): Describes the time period that observations can be expected from this AbstractMonitoringObject. Can be only a start time for running measurements or an interval.
* onlineResource (URL): A link to an external document providing further information about an ISO 19156 'Observations and Measurements' compliant data model used to store or exchange Observations and Measurements acquired. 
_KS: could be provided via metadata or parameter_
* processType (ProcessTypeValue: process, sensorML): The type of object used for describing the process.
* resultNature (resultNatureValue: primary, processed, simulated): State of the provided result.

**Comment by sgrellet** [comment]
To me our PotentialObservation -> ObservingCapability is indeed an Collection.
Question is  : do we need some 'soft-typing' in the Collection to state : my collection is a 'ObservingCapability'

**Comment by KathiSchleidt** [comment]
Reached agreement on ObservingCapability as a Collection

**Comment by KathiSchleidt** [comment]
Attributes from the INSPIRE ObservingCapability for reference:

* ObservingTime (TM_Object): devolves to PhenonemonTime
* onlineResource (URL): Use the metadata of type Any
* processType (ProcessTypeValue: process, sensorML): Implicit in the data
* resultNature (resultNatureValue: primary, processed, simulated): Add

**Comment by ilkkarinne** [comment]
Could you please provide your rationale presented on 1st July SWG meeting decision for defining ObservingCapability as a specialization of ObservationCollection rather than specialization of ObservationCharacteristics?

I still feel that is is not semantically correct to state that an ObservingCapability "is an" ObservationCollection. I liked the idea of having the ObservationCapability defined as a special kind of ObservationCharacteristics, which then could or could not be used as the value of memberCharacteristics association of an ObservationCollection.

**Comment by KathiSchleidt** [comment]
Unclear as to why we shifted this to collection. @sgrellet @hylkevds : what was the argumentation, no notes other than should be done, no reasoning

**Comment by hylkevds** [comment]
An ObservingCapability is the SummarizingObservationCollection of (a subset of) all potential Observations.
