### ISSUE TITLE
Definition of FeatureType (19109 vs. 19136)

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#181]
**DK11-024 The FeatureType is defined in ISO 19109, not in ISO 19136** 
(ISO 19136 defines the UML-to-GML encoding rules for an application schema according to ISO 19109). 
See also Table 17 in ISO 19109:2015.	Update the text so that the source of the FeatureType stereotype is correct.	

4.2 2nd paragraph

**Comment by ilkkarinne** [comment]
This text is unchanged from the 2011 version. It does not say that the FeatureType metaclass is defined 19136, but that the stereotype FeatureType is, and there is also a reference to 19109:

> The UML in Abstract Core and Basic packages is conformant with the profile described in ISO 19136-1:2020, Annex E. Use of this restricted idiom supports direct transformation into a GML Application Schema. ISO 19136 [28] introduces some additional stereotypes. In particular «FeatureType» implies that a class is an instance of the «metaclass» GF_FeatureType (ISO 19109), and therefore represents a feature type.

However, the reference to ```GF_FeatureType``` should be replaced by ```FeatureType```, as this is updated in 19109:2015.

Proposal: no change in text

**Comment by KathiSchleidt** [comment]
Confused!!! Assuming "no change in text" means leaving the reference to 10109, but updating the «metaclass» GF_FeatureType to FeatureType as done in the following text:

The UML in Abstract Core and Basic packages is conformant with the profile described in ISO 19136 1:2020, Annex E. Use of this restricted idiom supports direct transformation into a GML Application Schema. ISO 19136 introduces some additional stereotypes. In particular «FeatureType» implies that a class is an instance of the «metaclass» **FeatureType** (ISO 19109), and therefore represents a feature type.

**Comment by ilkkarinne** [comment]
Thanks @KathiSchleidt, your interpretation of my confusing comment is correct :-)

**Comment by KathiSchleidt** [comment]
@cportele Is our logic correct here?

**Comment by cportele** [comment]
@KathiSchleidt

When GML 3.2 / 19136 was written, 19109 did not define a stereotype FeatureType, so originally it was defined in GML 3.2 / 19136. In the 2015 revision 19109 added the stereotype FeatureType to identify classes that are feature types (instances of the metaclass FeatureType in the GFM. 

The proposed text is fine, but we could also simplify it to something like:

> The UML in Abstract Core and Basic packages is conformant with the profile described in ISO 19136-1:2020, Annex E. Use of this restricted idiom supports direct transformation into a GML Application Schema. The stereotype «FeatureType» states that a class is an instance of the «metaclass» FeatureType (ISO 19109), and therefore represents a feature type.

**Comment by cportele** [comment]
I think that would also be consistent with the discussion about this in the EC meeting.

**Comment by ilkkarinne** [comment]
I agree with changing the text to @cportele's suggestion. I think that in this case we can also change the status from "Accepted in principle" to "Accepted". I'll update the comment resolution table accordingly and notify rest of the EC members.
