### ISSUE TITLE
Model conformance rules from 19109

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#185]
**-028 The conformance rules for Models in general are described in ISO 19109:2015.** 	
Unless there is an intention to remove conformance rules for Models in general from the future revision of ISO 19109, there is no reason for it to be dated.

**Comment by KathiSchleidt** [comment]
We need info from @cportele on this issue

**Comment by cportele** [comment]
This is even less relevant, if 19109 is moved to the bibliography (see #167), but in any case an undated reference should be fine.

**Comment by KathiSchleidt** [comment]
Delete 19109 from Normative References, move to Bibliography without date

**Comment by sgrellet** [comment]
@KathiSchleidt  - We do have a Ref in Bib : [2]	ISO 19109, Geographic information — Rules for application schema
but we are not using it throughout the document when 19109 is mentionned
Same comment as for #167

**Comment by KathiSchleidt** [comment]
Added citation to bib under 4.2 Schema language (first mention of 19109 after terminology citations) - to my view, don't have to cite each time we mention 19109

**Comment by sgrellet** [comment]
Makes sense to me
