### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#187]
**ZA-001-030 Rephrase- This structureenables users to selectively**	
This allow structureenables users to selectively

KS: add missing blank

**Comment by KathiSchleidt** [comment]
**-060 If information on the type of Observation is provided, the constraints defined in the referenced codelist SHALL be used.**	
Should the word "observation" be written in bold font here?	

KS: agreed

**Comment by KathiSchleidt** [comment]
**-065 If the reason for the Deployment is provided, the property deploymentReason:CharacterString SHALL be used.**	
It is not clear why the section of text "deploxmentReason:CharacterString" is written in italic font here. Please review.

**-066 If the time of the Deployment is provided, property deploymentTime:TM_Period SHALL be used.**	
The previous comment concerning the use of italic font also applies here.

**Comment by KathiSchleidt** [comment]
**-111 (ex : forecast)**
"e.g." ?

**Comment by KathiSchleidt** [comment]
**AFNOR-001 Abstract Observation core**	
Abstract Observation Core	

KS: capitalize Core

**Comment by sgrellet** [comment]
* ZA-001-030 Rephrase- This structureenables users to selectively -> "KS: add missing blank" -> agreed
* -048 in the Sampling part of section 7 -> "KS: change reference to 7.2 Sample schema" -> agreed
* -060 If information on the type of Observation is provided, the constraints defined in the referenced codelist SHALL be used. -> "KS: agreed" -> agreed 
* -065 If the reason for the Deployment is provided, the property deploymentReason:CharacterString SHALL be used. -> "SG : remove italic"
* -066 If the time of the Deployment is provided, property deploymentTime:TM_Period SHALL be used. -> "SG : remove italic"
* -106 ex situ : -> "SG : indeed in 19156:2011 the term ex situ is written in italic -> make 'ex situ' italic again"
* -111 (ex : forecast) -> "SG : the rest of that chapter uses a lot of e.g -> write "**_(e.g: forecast)_**""
* AFNOR-001 Abstract Observation core -> "KS: capitalize Core" -> agreed

**Comment by KathiSchleidt** [comment]
Short note on e.g., based on the feedback I've received over the years, there should be a comma after

`proper English style usually requires commas to follow e.g. to delimit the beginning of that list`

Otherwise agreed

**Comment by ilkkarinne** [comment]
-106: quoting the ISO House Style:

> Do not italicize commonly used Latin expressions, e.g. a priori, in situ, in vitro.

now I’m confused, italics or not?

**Comment by ilkkarinne** [comment]
Oh, now I see: maybe ex situ is not considered ”commonly used”, but in situ is, thus ex situ would fall under ”words used for scientific terms”:

> Italicize Latin words used for scientific terms, e.g. species, bacteria, plants. For example, “This document describes a horizontal method for the detection of Salmonella spp. in food.

Proposing to keep both in situ and ex situ in the same type (either italic or not).

**Comment by KathiSchleidt** [comment]
If we didn't have _in situ_, I might be OK with having **ex situ** not italic, but especially as they're a pair, I'm for including _ex situ_ under the _Latin words_

**Comment by sgrellet** [comment]
@KathiSchleidt regarding (e.g., forecast)  and your quote above "proper English style usually requires commas to follow e.g. to delimit the beginning of that list"
it turns out that in the rest of the doc we have e.g. without comma (for example "(e.g. surface/ground water level, rainfall)" ) right after in the paragraph

-> we need to be consistent on this throughout the document

**Comment by KathiSchleidt** [comment]
OK, will do this when I do the AbstractCollection update

**Comment by KathiSchleidt** [comment]
Did a search and replace between "e.g. " to "e.g., "

**Comment by sgrellet** [comment]
completed with adding one "e.g.," in "7.1.2 Observation", "7.3.1	Model consistency" , '8.6.2	Interface Observer' sections
