### ISSUE TITLE
This International Standard

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#188]
**-031 This International Standard**	
I think it would be clearer to write the document number here. If this table were to be cross-referenced in another document, for example, it could become confusing or unclear.	

**-118 This new version of the Observations and Measurements Standard** 	
Is this a reference to the current and previous edition of ISO 19156? If so, please use the specific ISO document numbers, i.e. This second edition of ISO 19156 (now renamed...)
Section: Introduction

**-119 This International Standard**
Please refer to this document as "this document" throughout, rather than "this International Standard".
Section: Introduction	

KS: always name OMS in the text

**Comment by sgrellet** [comment]
Agreed. But using the 'developped form' : Observation, measurement & samples (question with capital letters or no. Just re-discovering looking at the cover page that only Obs has a capital letter)

**Comment by KathiSchleidt** [comment]
Also agreed.

I did a scan of various 191XX standards, seems to be quite an eclectic mix out there. Most just capitalize the first letter, but other use capital for all words, e.g., ISO 19136-1:2020 Geographic information — Geography Markup Language
I'd feel better with **Observations, Measurements and Samples** (also all plural, at least that's already on the cover page)

**Comment by KathiSchleidt** [comment]
Official Name: Observation, measurement & samples
