### ISSUE TITLE
EXAMPLES

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#189]
**-033 EXAMPLES:**
There are a lot of example links contained within this one example. Is it necessary to include this many examples? 	

KS: don't think removing examples increases clarity!

**Comment by KathiSchleidt** [comment]
**-047 phenomenonTime Notes**
NOTE 1	The phenomenonTime is often the time at which the Sample has been taken.
NOTE 2	This is often the time of interaction by a sampling Procedure or observation Procedure with a real-world feature.	
Suggest combining these two notes.	

KS: reflect different concepts, thus should remain separate

**Comment by KathiSchleidt** [comment]
Won't fix, other comments wanted more examples

**Comment by ilkkarinne** [comment]
What is the difference between "the time at which the Sample has been taken" and "time of interaction by a sampling Procedure"?

**Comment by KathiSchleidt** [comment]
Makes sense to me (though did have to read it 3 times to be sure).
General context note: this one pertains to 8.2.3, conceptual Observation

**Comment by KathiSchleidt** [comment]
NOTE 1 The phenomenonTime is often the time of interaction with a real-world feature either by a SamplingProcedure (time at which a Sample has been taken) or by an ObservingProcedure.
