### ISSUE TITLE
Incorporate SOSA/SSN Concepts

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#19]
Source: http://ogc.standardstracker.org/show_request.cgi?id=579

Various concepts from SOSA/SSN would be valuable additions to O&M. Some of these have already been mentioned in OGC/ISO CRs, foremost:
* Observation Collection #2 
* Ultimate Feature of Interest #3 
Other concepts should be evaluated for inclusion

**Comment by dr-shorthair** [comment]
Note that ObservationCollection is not (yet) in SOSA/SSN, but in a proposed _extension_. https://www.w3.org/TR/vocab-ssn-ext/#ssn-ext:ObservationCollection
