### ISSUE TITLE
Unclear Quotes

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#190]
**-039 the “world in the vicinity of the observer/sampler**	
Is this a direct quotation from another source? If so, please provide the Bibliographical reference for it.	
Pertains to 7.2.3

Interesting is that they didn't catch a parallel formulation under 
13.3.2	Feature type SpatialSample
-	Typically an Observation ‘site’ or 'station' connotes the 'world in the vicinity of the site (or station)', ...

**Comment by sgrellet** [comment]
* 039 the “world in the vicinity of the observer/sampler : 
agreed with KS
but if we follow that brain path where do we stop the logic ? still in 7.2.3 we also wrote : _In various countries/domains, terms like “site” and station” are encountered._ 
it's obvious (I guess) that's not a quote from some source.
-> what's the ISO rule around this ?

* -080 (although ‘specimen preservation could be considered a specific activity per se’)
I don't remember this being the quote of some source. Re-reading the sentence I think the quotes are misplaced. It should have been written _(although ‘specimen preservation' could be considered a specific activity per se);_
-> this brings the same question as above regarding the ISO rule on that point
-> are we allowed to put in quote terms to give an example without this being considered a quote of some source ?

**Comment by KathiSchleidt** [comment]
- 039: I think we can leave the "" out as the logical grouping is clear from the text
- 080: also don't understand why we even have quotes here, wrong

on individual quoted words, I've found a place where Alison put such quotes in (see NOTE 2 under 8.4.2	Interface Procedure), so we're definitely good there.
