### ISSUE TITLE
http://qudt.org/vocab/unit/UNITLESS

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#191]
**-044 http://qudt.org/vocab/unit/UNITLESS**
Please move this link to the Bibliography, either to replace the link already present in entry [28] or to be included as a new entry, as appropriate.	

KS: think there's confusion here. In the Bib, we reference QUDT, in section 8.2.16, we reference a specific concept from this vocab.

**Comment by sgrellet** [comment]
Agreed.
Should we ajust the text to reduce the risk of confusion ?  Proposal : 

NOTE	In the case where the result of the Observation is a classification, for which no unit exists, the UoM should be declared as unitless (e.g., referencing QUDT[28] _entry_ http://qudt.org/vocab/unit/UNITLESS or UCUM[20] _entry_ for “no units”).

**Comment by sgrellet** [comment]
**OMS SWG Meeting June 8th 2022**
Above mentionned proposal agreed in session (without italic to avoid infringing some rules)

**Comment by KathiSchleidt** [comment]
**OMS SWG Meeting June 8th 2022**
Agreed adding entry.
Provide clarification to comment stating that the URI listed is an identifier for a specific object, not a reference to an external resource
