### ISSUE TITLE
Req without Shall

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#192]
**-046 Interface Observation**	
The requirement in this section does not contain the verbal form "shall". Instead, it is written as statement of fact. Please verify that this is correct.

**Comment by KathiSchleidt** [comment]
**-059 Set of common characteristics used for describing an Observation or a collection of Observations.**	
This section of text is labelled "requirement" but it does not contain the verbal form "shall". Please review.

**Comment by KathiSchleidt** [comment]
**-098 A location identified by its name, address, spatial geometry or a combination of any of these three.**
This text is marked as a requirement, but the verbal form "shall" is not used. Please check.

**Comment by KathiSchleidt** [comment]
**-046 8.2.2 Interface Observation
An **observation** is an act carried out by an **Observer** to determine the value of an **ObservableProperty** of an object (**featureOfInterest**) by using an **ObservingProcedure**; the value is provided as the **result**. 

How about rephrasing An **Observation** _shall be_ an act...

While there isn't a comment, there are other reqs without a shall, e.g.
8.3.2	Interface ObservableProperty
A quality (property, characteristic) of the **feature-of-interest** that can be observed.

Based on the logic above, this should be modified to read:
An ObservableProperty _shall be_ a quality ...

**Comment by KathiSchleidt** [comment]
Also applies to:
- 8.4.2	Interface Procedure: A description of steps performed. 
- 8.5.2	Interface ObservingProcedure: The description of steps performed in order to determine the value of an observableProperty by an Observer.
- 8.6.2	Interface Observer: An identifiable entity that can generate **Observations** pertaining to an **observableProperty** by implementing an **ObservingProcedure**.
- 8.7.2	Interface Host: A grouping of Observers for a specific reason.
- 8.8.2	Interface Deployment: Information on the assignment of an Observer to a Host.
- 9.2.2	Feature type AbstractObservationCharacteristics: Set of common characteristics used for describing an Observation or a collection of Observations.
- 10.4.2	Feature type ObservationCollection: A collection of similar Observations
- 10.5.2	Feature type ObservingCapability: Information on Observation(s) that could potentially be provided.
- 11.2.2	Interface Sample: A Sample is an object that is representative of a concept, real-world object or phenomenon.
- 11.3.2	Interface Sampling: Sampling is an act applying a SamplingProcedure to create or transform one or more Sample(s).
- 11.4.2	Interface Sampler: A Sampler is a device or entity (including humans) that is used by, or implements, a SamplingProcedure to create or transform one or more Sample(s).
- 11.5.2	Interface PreparationStep: A PreparationStep is an individual step pertaining to a PreparationProcedure.
- 11.6.2	Interface PreparationProcedure: The description of preparation steps performed on a Sample. 
- 11.7.2	Interface SamplingProcedure: The description of steps performed by a Sampler in order to extract a Sample from its sampledFeature in the frame of a Sampling.
- 13.3.2	Feature type SpatialSample: A SpatialSample is a geospatial Sample.
- 13.4.2	Feature type MaterialSample: A MaterialSample is a physical, tangible Sample.
- 13.5.2	Feature type StatisticalSample: A StatisticalSample is a statistical subset of a feature-of-interest, defined for the purpose of creating Observation(s).
- 13.11.2	Feature type SampleCollection: A collection of Samples.
- 13.12.2	Data type PhysicalDimension: A dataType for the provision of various size quantities.
- 13.13.2	Data type NamedLocation: A location identified by its name, address, spatial geometry or a combination of any of these three.
- 13.14.2	Data type StatisticalClassification: A dataType for the provision of information on statistical classifications.

Modify all described above

**Comment by KathiSchleidt** [comment]
An Observation is shall be defined as: 
blablabla

use pattern for all

**Comment by sgrellet** [comment]
had to fix twice a weird structure '115orrespo' in place of dataType... and found 2 other occurences of that pattern in section C.3. Don't know how they got in the doc. Hopefully is ok now.
