### ISSUE TITLE
Depersonalization

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#193]
**-051 On a groundwater well we:**	
In accordance with the ISO House Style, an impersonal tone is to be adopted in ISO documents in which person pronouns ( I, we, you) are to be avoided. Please rephrase this Example accordingly.

**Comment by sgrellet** [comment]
Agreed. We tried to do this as much as possible. 
This one dodged the "depersonalization scan" apparentrly.

**Comment by KathiSchleidt** [comment]
scan document for usage of "I, we, you", modify accordingly
