### ISSUE TITLE
Interface Procedure Req

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#194]
**-052 A description of steps performed.	
There is no verbal form used in this sentence. It therefore appears incomplete and cannot be considered a requirement. Please review.

**Comment by sgrellet** [comment]
The issue is that this super class is further down specialized (Observing, Preparation, Sampling). So we tried to be as generic as possible (and avoid the terms used in the specializations).
Would the following help solve the issue ?

-> "A description of steps performed to carry out an act"

**Comment by KathiSchleidt** [comment]
Modify as follows, in alignment with #192 
A Procedure shall be defined as 
a description of steps performed
