### ISSUE TITLE
Number Notes

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#195]
**Notes need a dedicated Notes Number**

**-053 NOTES:** 
1)	Depending on the complexity of the use case, the procedure will be more or less explicitly described. Especially pertaining to historical data, there may be very little or no information available - this information should also be provided;
2)	The recipe that the observer (cook) follows to generate the observation;
3)	The procedure is often referred to as the method;
4)	Different observers can follow the same (reusable) procedure for the creation of different observations;
5)	The procedure is a workflow, protocol, plan, algorithm, or computational method specifying how to make an observation;
6)	The observing procedure cannot describe a sensor instance, but it can describe the sensor type.
NOTE	The term process that was used in ISO 19156:2011 has been purposely dropped in this version to avoid unnecessary confusion between the terms procedure and process.	
Please list these notes as NOTE 1, NOTE 2, NOTE 3, or else combine to form one single NOTE.	

**-055 NOTES:**
a)	In many use cases, the Host is the environmental monitoring facility;
b)	The Host can be a platform that hosts a set of sensors;
c)	An alternative usage could pertain to a biodiversity survey campaign. In this scenario, the team performing the survey would be modelled as observers whereas the entire survey campaign can be represented as a Host.	Please see previous comment on the regrouping of NOTEs.	

**-056 NOTE	Examples of deployment are:**
Please see previous comment on the regrouping of NOTEs.

**Comment by KathiSchleidt** [comment]
8.5.2	Interface ObservingProcedure
8.7.2	Interface Host
8.8.2	Interface Deployment
Number notes individually, e.g., NOTE 1, NOTE 2...

Also applies to 
8.4.2	Interface Procedure
8.6.2	Interface Observer
9.2.3	Attribute observationType
9.2.4	Attribute parameter
9.2.7	Association ultimateFeatureOfInterest (also fix EXAMPLE, EXAMPLE1...)
11.2.2	Interface Sample
13.4.5	Attribute sourceLocation

EXAMPLES
9.2.7	Association ultimateFeatureOfInterest (also fix EXAMPLE, EXAMPLE1...)
9.8.2	Attribute deploymentReason
9.8.3	Attribute deploymentTime
11.3.2	Interface Sampling
11.4.2	Interface Sampler
12.4.2	Attribute samplerType
13.3.2	Feature type SpatialSample

**Comment by KathiSchleidt** [comment]
8.8.2 Interface Deployment: NOTEs shall be EXAMPLEs

**Comment by KathiSchleidt** [comment]
Also pertains to 
**TMG-027**
3.18 property type	ed	
the order of "EXAMPLE" in the entry is incorrect;	
move the EXAMPLE to come after the definition but before the start of the Notes to entry

KS: Description is clear, will be done!

**Comment by sgrellet** [comment]
also corrected while cross-checking

- 8.2.5	Attribute validTime => NOTE 1 (alone thus no need for numbering) -> NOTE

- 8.2.9	Association observingProcedure => EXAMPLE 1 (alone thus no need for numbering) -> EXAMPLE

**Comment by KathiSchleidt** [comment]
Thanks! Fear I got a bit confused between the different ISO formatting rules. For the Terminology my understanding is that the order of EXAMPLE and Note are mandatory, in the clauses seems to be more flexible. In addition, seems that under Terminology, the Notes are always numbered. I ended up using the stricter Terminology requirements further down.
