### ISSUE TITLE
Observation Type Semantics

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#196]
**-069 to firm up semantics of observation types**	
This phrasing seems quite informal. Please review and consider replacing with more appropriate phrasing, e.g. to clarify, to confirm, etc.	
Section 9.10.1

**-079 to firm up**
Please see previous comment in subclause 9.10.1 on this phrasing.	
Section 10.12.1

**-088 to firm up**
Please see previous comments on this phrasing, e.g. in subclause 9.10.1.
12.8.1

**-089 to firm up**
See previous comment.
12.8.2

KS: think we already found an alternative formulation in the May 4th SWG

**Comment by sgrellet** [comment]
"KS: think we already found an alternative formulation in the May 4th SWG"

I remember we did, but looking at the meeting not I just find _"Notes for Kathy’s brain :)
“to firm up semantics of observation types” -> This phrasing seems quite informal. Please review and consider replacing with more appropriate phrasing, e.g. to clarify, to confirm, etc."_
I remember writing this but that does not give us the alternative formulation -> does one want to reopen the recording ? ^^

extra idea from my side. all the locations where this structure is used is to say that  "The code list AbstractFooType can be specialized as required to _**firm up**_ semantics of foo types.

proposal replacement terms
- enforce ?
- precise ?

**Comment by KathiSchleidt** [comment]
further clarify?

**Comment by ilkkarinne** [comment]
What about "..to more precisely define the semantics of.."

**Comment by KathiSchleidt** [comment]
Nice! Summarizing:

**9.10.1	AbstractObservationType**
The code list AbstractObservationType can be specialized as required to **more precisely define the** semantics of observation types , as done in the derived codelist ObservationTypeByResultType below.

**10.12.1	AbstractObservationCollectionType**
The code list AbstractObservationCollectionType can be specialized as required to **more precisely define the** semantics of collection types, as done in the derived codelist ObservationCollectionType below.

**12.8.1	AbstractSampleType**
The code list AbstractSampleType can be specialized as required to **more precisely define the** semantics of sample types.

**12.8.2	AbstractSamplerType**
The code list AbstractSamplerType can be specialized as required to **more precisely define the** semantics of sampler types.

**Comment by sgrellet** [comment]
Agreed
