### ISSUE TITLE
Bibliography References for Citations in Table B.1

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#197]
**-101 Table B.1 — Earth Observations (EO)**	
Please ensure that references to external webpages or documents in the "Example" column of this table shall be added to the Bibliography. The corresponding bibliographical callout (the bibliography entry number in superscript+square brackets) shall be inserted in the corresponding table cells after the text.

**Comment by ilkkarinne** [comment]
This comment seems to deal with the two reference to the PlanetarySurface concept of SWEET Ontology:
(http://sweetontology.net/realm/PlanetarySurface). This an identifier of the concept, which also happens to work as a web resource link.

Proposal: keep as-is, and not add a reference to the bibliography

**Comment by KathiSchleidt** [comment]
Agreed, same argumentation as taken on http://qudt.org/vocab/unit/UNITLESS under #191
