### ISSUE TITLE
Bibliography 

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#198]
**-102  [32] 	https://www.w3.org/TR/sdw-bp/**
Please complete this Bibliographical entry.

**-103 [2]	ISO 19105:2000, Geographic information — Conformance and testing**
[3]	ISO/DIS 19105, Geographic information — Conformance and testing	
Is it necessary to cite both of these documents in the Bibliography? Neither seem to be cited in the document. Consider removing.

**-104 Bibliography** 
Note that references only need to be dated if they refer to a specific part of a document (e.g. specific subclause, table, etc.)

**Comment by ilkkarinne** [comment]
Reference to 19105 was added to the Bibliography based on the CD Ballot comment requesting it (see #92). It is not used in the text, so I would be fine to remove both versions of it ([2] ISO 19105:2000  and [3] ISO/DIS 19105)  from the Bibliography

**Comment by ilkkarinne** [comment]
Ok, took a bit of detective work to figure out the first comment: We did not have a bib. entry 32 in the submitted DIS version. We used the link to https://www.w3.org/TR/sdw-bp/ in the Introduction, which was replaced by the reference to a new bib. entry [32] (created as incomplete by Alison?).

Proposal: complete the new bib. entry 32 as follows:

[32] Spatial Data on the Web Best Practices, W3C Working Group Note, 28 September 2017. Also published as OGC Best Practice 15-107, https://www.w3.org/TR/sdw-bp/

**Comment by KathiSchleidt** [comment]
-102 [32] https://www.w3.org/TR/sdw-bp/
Take version proposed by Ilkka

-103 [2] ISO 19105:2000, Geographic information — Conformance and testing
Remove from Bib as not cited in doc

-104 Bibliography
I'm for leaving the dates as they stand, as different versions of ISO standards tend to have quite different content
