### ISSUE TITLE
Distinguish between the sensor and observing procedure

### ISSUE THREAD

**Issue by ilkkarinne** [opengeospatial/om-swg#20]
In 10-004r3 the "procedure" attribute of the Observation is used for capturing either or both the method or recipe and the device or estimator implementation used for creating the particular Observation result.

Adding a dedicated Observation attribute for the sensor or other estimator used would make it possible to filter of a collection of Observations based on either the observation procedure or the sensor instrument used depending on the use case.

Examples of the used cases would be discovering Observations created using the same procedure (specification) but captured using different sensing instruments. On the other hand it may be convenient sometimes to filter out Observations created using a particular instrument (due to known data quality issues etc.)

This distinction between the procedure and the sensor is implemented in the W3C-OGC SSN/SOSA Ontology as sosa:madeBySensor and sosa:usedProcedure

Source: http://ogc.standardstracker.org/show_request.cgi?id=609

**Comment by KathiSchleidt** [comment]
Updated in Toulouse 
- Sensor has been renamed Observer, as this is a more generic term (easier to explain human sensors)
- Procedure has been renamed ObservingProcedure, as better aligned with Observer

**Comment by ilkkarinne** [comment]
Update: The [draft UML model](https://github.com/opengeospatial/om-swg/blob/50fd1d16d7de82e02712a42706fdeae65059d7f7/iso_19156_issues/ea/Edition2_playground_snapshot.png)  has ```AbstractEvent.usedProcedure``` association pointing to ```Procedure```, and ```AbstractObservation.madeBy``` association pointing to ```Observer```

**Comment by ilkkarinne** [comment]
Regarding Procedure: sosa.Procedure has two potentially useful properties that are missing in our draft the O&M model: hasInput restricted to sosa:Input and hasOutput restricted to sosa:Output. Both sosa:Input and sosa:Output are blank (no properties).

Should we also have the input(s) and output(s) defined as associations of Procedure in O&M? Note that as far as I understand the Procedure input and output describes the "static" input & output binding for the process used, rather than the "dynamic" ones for realising the particular Observation instance.

**Comment by ilkkarinne** [comment]
In #30 we decided to use the name "Observer" instead of "Sensor". Do we have a need to an abstract Sensor class as subclass of Observer or should we just state in the specification text that sensors fall under a more generic term of an Observer?

**Comment by ilkkarinne** [comment]
The SWG position is that there is not need for a specific Sensor class in the O&M model in addition to the abstract Observer

**Comment by sgrellet** [comment]
Given work on Observer and latest version of the model I guess we can label it 'Final decision' and close this no ?
