### ISSUE TITLE
Changes in Standard

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#200]
**-116 The main changes are as follows:**
Note that the information provided in the list of main changes compared to the previous version is quite vague. It could be helpful to the user to give a clearer indication of what has been improved/how improvements have been made, i.e. has the text been restructured? has additional detail been added? has the wording been clarified? etc.
Adding a cross-reference to Annex C could perhaps help with this.	
Section: Foreword

**Comment by sgrellet** [comment]
We can reuse the sentence that is already at the end of the Introduction : **_"A technical note describing the changes from the earlier version is available as Annex C_**." and add it right after this sentence in the Foreword '_The Sample model has also been refined. Given the integral nature of the Sample model, is has been decided to include that term in the name of the standard._ '

**Comment by KathiSchleidt** [comment]
Agreed on both points
