### ISSUE TITLE
WATERMARKED Version!!!

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#201]
**-117 ISOCS has provided an edited, tracked changes (watermarked) Word file**
 for this document to align the content with the drafting rules in ISO/IEC Directives Part 2. The comments provided summarize the main editorial changes required but may not be exhaustive. Additional changes and comments may be contained in the edited Word file.	
The watermarked Word file shall be used when preparing the next submission of this document. For questions about the drafting rules or the editing provided, contact Alison Reid-Jamond: reid-jamond@iso.org  

@ilkkarinne do you have this version?

**Comment by ilkkarinne** [comment]
No idea, but I'm sure Mats will be able to provide this

**Comment by KathiSchleidt** [comment]
Sent by Mats, stored to
https://github.com/opengeospatial/om-swg/blob/master/oms-abstract-spec/ISO%20DIS/ISO_DIS%2019156%20ed.2%20-%20id.82463%20Enquiry%20Trackchange%20Word%20(en).docx

**Comment by KathiSchleidt** [comment]
Note on the Abby's Car issue - has been sorted by Reese, following text:
```
the issue with ISO/CS and the terminology gender-based edit has been
solved. the ISO/CS will roll-back the edit, and we can use the
original example as-is. you will need to make that up as a comment and
reference discussion with the iso editor Alison and she will change it
back... so you will not accept the edit and request the original to be
used, but you have to write that on the comment sheet for your DIS
comment resolutions.
```
