### ISSUE TITLE
in situ / ex situ definition

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#202]
**TMG-015**
3.6 off-site	ed	
the term "in-situ (on-site)" is referenced in Note 1 to entry; however, in-situ is not defined in clause 3.
ISO 19159-1 4.11 defines the term "in situ measurement"; consider if that is suitable.
consider if "in situ" is needed in the document;

**TMG-016**
3.6 	off-site	ed	
the admitted term (off-site) should not be in bold-typeface
un-bold the admitted term

KS:
Unbold off-site.

Add definition of in situ, proposal:
referring to the study, maintenance or conservation of a specimen or population within its natural surroundings

aligns with 
**in situ measurement**
direct measurement of the measurand in its original place
[SOURCE: ISO/TS 19159-1:2014, 4.11]

**Comment by hylkevds** [comment]
For completeness:
- In-Situ / Ex-Situ relates to the location of the FeatureOfInterest or Sample
- Direct / Remote relates to the location of the Sensor

Related to #172

**Comment by joergklausen** [comment]
I am not familiar with the term ex-situ, although it is the logical complement to in-situ. In-situ is used in the sense of in situ measurement as defined above by everybody ... except satellite folks (and GCOS). They prefer to use in situ for everything Earth-based as opposed to satellite/space-based. This has created confusion for more than 20 yrs. A note in #172 to explain this might be useful.

I am not sure 'direct' is related to 'remote'. At least to me, 'direct' is more the opposite of 'proxy' when we speak about observation/measurement.

**Comment by KathiSchleidt** [comment]
in-situ: is added
referring to the study, maintenance or conservation of a specimen or population without removing it from its natural surroundings

ex-situ: remains as is
referring to the study, maintenance or conservation of a specimen or population away from its natural surroundings

**Comment by KathiSchleidt** [comment]
Add notes to the definitions from:

    in-situ & direct (mercury thermometer in a patients butt)
    in-situ & remote (infra-red thermometer at a distance)
    ex-situ & direct (mercury thermometer in a blood-sample)
    ex-situ & remote (infra-red thermometer pointed at the blood sample)

Also add opposite note to in-situ that opposite of ex-situ

**Comment by ilkkarinne** [comment]
@KathiSchleidt To which Clause did we decide to add the notes regarding in/ex situ and remote/direct observation combinations?

**Comment by KathiSchleidt** [comment]
Sorry, adding to a Clause was my mistake yesterday while speaking, should be as stated above with the _in situ_ & _ex situ_ definitions themselves

**Comment by PeterParslow** [comment]
Perhaps this issue should be closed as the specification & ISO standard have been published.

But as it is still open, see also https://github.com/ISO-TC211/StandardsTracker/issues/495 - the term "in situ" appears to have distinctly different meanings in different domains. This definition appears to work for geology, biology & healthcare, but not for "EO in general" or oceanology (raised at OGC ARD SWG)
