### ISSUE TITLE
Definition Observation

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#203]
**TMG-022**
3.13 observation ed
"observation" was defined in ISO 19156:2011, 4.11; observation was not in the CD; now the  term has been reinstated but the definition is different from that in ISO 19156:2011, 4.11; presently ISO 19170-1 uses observation from 19156:2011 as a defined term;
consider if the definition for observation needs to be revised or if it is possible to retain the original definition from ISO 19156; 

KS: the definition was removed from the first balloting draft due to potential overlaps between terminology and reqs. Definition was extended from the 19156:2011 version to reflect the updated semantics
Won't fix

**Comment by sgrellet** [comment]
just one extra not on the 'extension'.

Definition was extended from the 19156:2011 version to reflect the content of the UML model (most of which was already in 2011 version of the UML but not in the text) and the updated semantics
