### ISSUE TITLE
Fix the caption of Table C.1

### ISSUE THREAD

**Issue by ilkkarinne** [opengeospatial/om-swg#206]
After ISO/CS changes the caption is "Table C.1 — Observation mapping from ISO 19156:2011 to ISO 19156:2011" which makes no sense.

Proposal to change to "Table C.1 — Observation mapping from ISO 19156:2022 to ISO 19156:2011" as "Edition 1" and "Edition 2" are not allowed.

**Comment by KathiSchleidt** [comment]
Agreed!
