### ISSUE TITLE
Break Figure 13 into three separate context diagrams

### ISSUE THREAD

**Issue by ilkkarinne** [opengeospatial/om-swg#207]
Context diagram in Figure 13 describes three classes: AbstractObserver, AbstractDeployment and AbstractHost while the Figure 14 describes AbstractHost only. This is also noted in [Issue 157](https://github.com/opengeospatial/om-swg/issues/157#issuecomment-953104654)

To harmonize with the Basic Observation package, I would like to
* Describe only the AbstractObserver in Figure 13
* Add a new context diagram for the AbstactHost as the new Figure 14
* Describe only the AbstractDeployment as the new Figure 15
* Renumber the Figures 15-35 by shifting by one (15->16, 16->17 etc.)

**Comment by KathiSchleidt** [comment]
Agreed at OMS SWG 27.02.22
