### ISSUE TITLE
Add new subclause 4.8 Association hiding in UML context diagrams

### ISSUE THREAD

**Issue by ilkkarinne** [opengeospatial/om-swg#209]
The new context diagrams only contain direct associations of the class in context to keep the context diagrams clear and readable embedded to the specification A4 page size. All transitive associations are included in Annex E diagrams with links to full-size (zoomable & downloadable) PDFs of the diagrams.

Hidden associations in context diagrams can create confusion, so I'm proposing to add a subclause under clause 7 to explain this.

Proposed content:

> 4.8 Association hiding in UML context diagrams
> 
> The context UML diagrams in this document provide full detail of the attributes and direct associations of the class in context. However the associations of the associated interfaces and classes have been hidden to keep the diagram textual content large enough to be readable when printed. To discover the full association details of a particular associated class, please see the context diagram of that class.

> Full details of all the classes and their associations in packages Abstract Observation core, Basic Observations, Abstract Sample core, Basic Samples are provided in package overview UML diagrams in Annex E. The diagrams in Annex E are intended for providing the complete model details when electronic document formats where the document reader allows for zooming in to the diagram details. The annex E also contains permanent links to downloadable PDF versions the provided overview diagrams that can be used to reading and printing the diagrams in high resolution.

Related to #164

**Comment by ilkkarinne** [comment]
The text included in the current draft version:

> 4.8	Associations in UML context diagrams
The UML model described in this document is rather complex. To keep the text size readable in the UML context diagrams of this document only the associations of each class are guaranteed to be visible in their context diagrams. Please refer to the context diagram of a particular class to see all associations of that class. All associations of the classes in each package are also shown in the detailed  package overview diagrams in Annex E.

**Comment by sgrellet** [comment]
07/09/2022 webconf resolution agreed
