### ISSUE TITLE
ObservationCharacteristics collection association backwards

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#211]
Requirement: /req/obs-basic/ObservationCharacteristics/collection-sem

An **ObservationCollection** that is described by these **ObservationCharacteristics**.
If a reference to a collection **ObservationCharacteristics** is provided, the association with the role **collection** shall be used.

Jörg rightly noted that 2nd ObservationCharacteristics (in bold) should be ObservationCollection

**Comment by KathiSchleidt** [comment]
role should be memberCharacteristics

**Comment by KathiSchleidt** [comment]
If a reference to a _**ObservationCollection** from the_ **ObservationCharacteristics** is provided, the association with the role **collection** shall be used.

**Comment by sgrellet** [comment]
07/09/2022 webconf resolution agreed
