### ISSUE TITLE
Final Check Glitches

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#215]
my mistake, OK

**Comment by KathiSchleidt** [comment]
**10.1.1	Basic Observations Package Requirements Class**

/req/obs-basic/ObservationCollectionType/ObservationCollectionType-sem listed twice

**Comment by KathiSchleidt** [comment]
No conformance classes for

- /req/obs-basic/ObservationTypeByResultType/ObservationTypeByResultType-sem
- /req/obs-basic/ObservationTypeByResultType/ObservationTypeByResultType-con
- /req/obs-basic/ObservationCollectionType/ObservationCollectionType-sem
- /req/obs-basic/ObservationCollectionType/homogeneous-con
- /req/obs-basic/ObservationCollectionType/summarizing-con

**Comment by KathiSchleidt** [comment]
**5	Conformance**

Describes Clauses 7-13, should be 8-13 (7 is informative)

**Comment by KathiSchleidt** [comment]
Adding comma after i.e.

**Comment by KathiSchleidt** [comment]
**Bibliography References are off :(**

Noticed p29, reference to INSPIRE image, was 30, changed to 29 in line with bib.

Looking at other references, I **cannot** confirm that it's just a matter of subtracting 1 :(

**Comment by KathiSchleidt** [comment]
**11.3.4	Association featureOfInterest**

**/req/sam-cpt/Sampling/featureOfInterest-sem**

Missing shall. I modified as follows (_italic_ is the addition)

_A feature-of-interest shall be defined as_ the concept, real-world object or phenomenon (feature-of-interest) the Sample(s) of the Sampling represent

**Comment by KathiSchleidt** [comment]
**9.9.1	AbstractObservationCollection Requirements Class**

Fixed /req/obs-core/AbstractObservationCollection/ObservationCollection-sem 

to /req/obs-core/AbstractObservationCollection/AbstractObservationCollection-sem

**Comment by KathiSchleidt** [comment]
Made some figure references more exact (from each class, not bundled at one class)

**Comment by KathiSchleidt** [comment]
**10.4.1	ObservationCollection Requirements Class**

Changed "Requirement" to "Imports" for /req/obs-core/AbstractObservationCollection

**Comment by KathiSchleidt** [comment]
Added citation of the tables in Annex B

**Comment by KathiSchleidt** [comment]
**C.2	Interfaces in the conceptual schema packages**

The following were missing from the list of new concepts added:
f)	SampleCollection (a collection of similar Samples);
g)	ObservationCharacteristics (common characteristics of Observations);
h)	ObservingCapability (potentially Observations).

**Comment by ilkkarinne** [comment]
> No conformance classes for
> 
> * /req/obs-basic/ObservationTypeByResultType/ObservationTypeByResultType-sem
> * /req/obs-basic/ObservationTypeByResultType/ObservationTypeByResultType-con
> * /req/obs-basic/ObservationCollectionType/ObservationCollectionType-sem
> * /req/obs-basic/ObservationCollectionType/homogeneous-con
> * /req/obs-basic/ObservationCollectionType/summarizing-con

I don't think we need tests for the codelists, as there are no corresponding Requirements Classes either

**Comment by ilkkarinne** [comment]
Cross-checked the changes in the PreFINAL versio pushed in commit 6230ec7693ad07048cba7f3e5eff7a78cb03e2bb, all OK by me!

**Comment by KathiSchleidt** [comment]
Works for me! Never quite got the sense of the conformance copy&paste clause ;)

**Comment by KathiSchleidt** [comment]
Whoops - think should be (potential Observations), but (potential to create Observations) also works nicely

**Comment by ilkkarinne** [comment]
This has now been fixed as "potential to create Observations"

**Comment by ilkkarinne** [comment]
Whoops, I just noticed that Figures D.4 and D.5 are the same (D.5 duplicated as D.4). Will generate the correct D.4 and replace it

**Comment by ilkkarinne** [comment]
The Figure D.4 now has the correct image, and the separate figure EMF and PDF files have also been corrected.

**Comment by ilkkarinne** [comment]
Fixes needed for wording in Clause C.6 Observation and Sample collections since the Observation collections have been moved to Abstract Observation Core

**Comment by ilkkarinne** [comment]
Old text:
> ISO 19156 ISO 19156:2011 did not include a concept of an Observation collection. In ISO 19156:2022 it is added as class ObservationCollection in package Basic Observations with the following attributes, associations and cardinalities:
> 
> a)	member: Conceptual Observation schema: Observation [0..*];
b)	memberCharacteristics: ObservationCharacteristics [0..1];
c)	collectionType: AbstractObservationCollectionType [0..*];
d)	relatedCollection: ObservationCollection [0..*];
e)	metadata: Any [0..*].
> 
> One concrete specialization of the AbstractObservationCollectionType class is provided in the Basic Observations package: ObservationCollectionType with an initial set of two values: ‘homogeneous’ and ‘summarizing’, which define how the properties of the ObservationCharacteristics instances associated with the ObservationCollection instance relate to the corresponding properties of the collection members (see clause Attribute collectionType). Other Observation collection classifications may be added by specializing the AbstractObservationCollectionType as required.

New text:

> ISO 19156 ISO 19156:2011 did not include a concept of an Observation collection. In ISO 19156:2022 it is added as class AbstractObservationCollection in package Abstract Observation Core with the following attributes, associations and cardinalities:
> 
> a)	member: Conceptual Observation schema: Observation [0..*];
b)	memberCharacteristics: AbstractObservationCharacteristics [0..1];
c)	collectionType: AbstractObservationCollectionType [0..*];
d)	relatedCollection: AbstractObservationCollection [0..*];
e)	metadata: Any [0..*].
> 
> A concrete specialization of the AbstractObservationCollection class is provided in the Basic Observations package as the ObservationCollection class. The same package also contains one concrete specialization of the AbstractObservationCollectionType codelist, the ObservationCollectionType class, which has an initial set of two values: ‘homogeneous’ and ‘summarizing’, defining how the properties of the ObservationCharacteristics instances associated with the ObservationCollection instance relate to the corresponding properties of the collection members (see Clause 10.12.1 ObservationCollectionType). Other Observation collection classifications may be added by specializing the AbstractObservationCollectionType as required.

**Comment by KathiSchleidt** [comment]
Thanks for catching! I DID look at every figure and number and clause several times, but guess by the time I was at the bitter end, was pretty blind!

**Comment by ilkkarinne** [comment]
Found one more wrong bib. citation to UCUM on page 33, will fix
