### ISSUE TITLE
UoM expression object 

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#22]
Created http://ogc.standardstracker.org/attachment.cgi?id=49
sketch to explain the need around UoM expression object

In some cases a result + UoM is not sufficient as an extra conversion is made
ex: mass concentration of NO3- = 10 microgram per liter of N
As a result using 10-004r3, 'N' being the objectOfInterest would be done using om:parameter (or pending CRPs to have object of interest)
But the 'per liter of N' aspect would either be exposed in 'observedProperty' registries (resulting in long lists of Observed properties) or using om:parameter
To avoid this, dedicated property would be useful; this would also allow APIs to filter on it

This would at least concern timeseries and simplemeasure

Example of such entries in observedProperties registries in CSIRO registry
ammonium_as_N_concentration and ammonium_concentration (in fact in as NH4 concentration)

The term 'UoM expression object' is a placeholder to support the CRP

Source: http://ogc.standardstracker.org/show_request.cgi?id=610

**Comment by dr-shorthair** [comment]
The object might be indicated as part of the description of the observed-property, or of the observation procedure. But definitely not as part of the UoM.

**Comment by afeliachi** [comment]
The placeholder term 'UoM expression object' is a bit misleading, but I think what @KathiSchleidt means, as showed in the sketch, is for the object to be indicated as part of the (simple)measure description and not as part UoM.

**Comment by KathiSchleidt** [comment]
@afeliachi It wasn't me saying this, came from your dear colleague at BRGM ;)
Personally would appreciate clarification on this as well as #21 as seems a related complex, still a bit lost :(

**Comment by sgrellet** [comment]
@ilkkarinne  : ok to also be assigned to that issue

**Comment by afeliachi** [comment]
@KathiSchleidt sorry, I was actually involved in naming it like this and am still looking for better terms ;).
The example you present here is quite representative of many cases we're facing.
is there any needed details?

**Comment by sgrellet** [comment]
After discussions in Toulouse and webconfs, there is a concensus from a a domain point of view to have this information.
The question that remains is how to model this. Various approaches are on the table. We have to choose the best way to do it

**Comment by sgrellet** [comment]
Along with #21 , topic of dicussion with RDA I-ADOPT work
