### ISSUE TITLE
Out of band result 

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#23]
In Inspire D2.9 (V3.0) document, Annex K: Discussion paper on Out-Of-Band Results (informative) explored how to expose results that are either too big to be provided in the result property and/or available in binary/proprietary formats. This annex initially focused on gridded data by the rationale can be extended to other types of data

Source: http://ogc.standardstracker.org/show_request.cgi?id=611

**Comment by dr-shorthair** [comment]
This appears to an implementation issue, not a question for the fundamental conceptual model.

**Comment by sgrellet** [comment]
Rescanning issues with regards to our delivrables, I agree.
We had long discussions around the "in/out of band" terminology in OGC SELFIE. It is indeed with regards to a given technical architecture, not semantics.
