### ISSUE TITLE
Requirement/conformance classes, specification parts

### ISSUE THREAD

**Issue by ilkkarinne** [opengeospatial/om-swg#25]
What are your views on splitting the upcoming ISO 19156 requirements into requirement/conformance classes, possibly even defined in separate documents (common core and a selection of pick-and-mix extensions/parts)?

The main benefit I see would be for the implementations to be able to use only the bits they feel are necessary while providing additional context for particular needs (such as more complex observable property model, specialized Observation types, or managing event/result oriented perspectives with observations and coverages). Based on the discussion within the O&M SWG there is pull towards extending the basic O&M model in various ways, so of which are already a common practice in particular domains. At the same time we should make sure that implementing an O&M conformant data model does not get more unnecessarily complicated.

A secondary point in bringing this out is the schedule: If we decide to propose a multi-part spec, and can also get a go from the ISO/TC 211 in doing so, reaching a committee draft level readiness for the new O&M core would probably be much faster that getting all the aspects handled.

Below is a very quick sketch of possible grouping from O&M related possible standardisable aspects:

**Observation core**:
* Core Observation model
* Observation templates
* Observation collections
* Abstract classes for process, observed property, result, FoI

**Specialized observations**:
* Static result value Observation extensions: category, count, truth, complex, temporal, geometry
* Varying result value Observation extensions: coverage observations including timeseries observation
* Relationship between the sampling feature geometry and result domain in coverage observations
* Observation events as instance level coverage metadata

**Sampling and specimens**:
* Sampling features and spatial sampling features
* The use of featureOfInterest property to indicate both the sampling feature and the ultimate feature of interest
* Specimens

**Observable properties and measurements**:
* Observable property model including linking between base quantities and derived quantities (similar to INSPIRE OMOP)
* Use of O&M concepts for declaring observing capabilities
* Using FoI, phenomenon time, procedure, observable properties and parameters for observation acquisition planning and tasking
* Multi-property observations and providing their results
* Simple and complex measurements as Observation sub-types, units of measure

**Observing processes and sensors**
* The use of procedure property to indicate both the recipe (process) and the sensor type used for creating or planning Observations
* Simple observing process model (including description of process parameters similar to the INSPIRE OMPR), cases using ISO 19115-2 MI_Instrument, LE_Processing, LE_Algorithm and OGC SensorML
* Concept of a stimulus event triggering a sensor resulting in an Observation (stimulus time).
* The concept of nominal "anchor time" for a periodic observations (12:00 numerical weather model run, which provides data to a time period up to 6 hours after the nominal run time, triggered at 12:05 and made available at 12:35).
* Relation between process parameters and Observation parameters
* Guidance on referring to particular sensor types
* Instance level Observation chaining

**Comment by ilkkarinne** [comment]
A spin-off issue regarding the content of the core requirements class is added as #29

**Comment by ilkkarinne** [comment]
It was suggested in the O&M SWG meeting on 3rd June that we proposed a very fine-grained split of the requirements classes for the ISO 19156 UML model in order for the conforming systems to be able pick and mix and explicitly declare the O&M concepts they support in order to ensure lossless system-to-system data exchange. Thus the proposed requirements classes would as followed:

- Abstract Observation schema (interface level O&M concepts, not bound to features)
- Observation core (application schema)
   - Containing just the Observation and AbstractObservationCharacteristics feature types
   - redefined objectOfInterest (Any) to featureOfInterest (AnyFeature) associations
- Observation collections (application schema)
- Observing capabilities (application schema)
- Basic ObservingProcess (application schema)
- Basic ObservableProperty (application schema)
- Basic Observer (application schema)
- Basic Platform (application schema)
- Basic FeatureOfInterest (application schema)

Thus if two systems would declare conformance to at least both the Observation core and Basic Observer, they could safely assume exchanging O&M data using the ```core:Observation``` and ```basic-obs:Observer``` feature types, but would be be guaranteed to provide the compatible models for platform, ObservedProperty or ObservingProcess for example.

The practical issue I see here is actually the one @KathiSchleidt warned about earlier: At least for GML we would end up with separate namespaces (and their prefixes) for each application schema requirement class, totalling to eight with the list above.

If we combine all the "basic" feature types in a single requirements class that would ease the namespace pain, but conforming to this combined requirements class would require support for all the basic feature types, even though additional/alternative ones could of course also be defined at the domain / system level.

Can we somehow balance between the two extremes:

- two requirements classes: core + all the basic features combined, and
- eight requirements classes with each basic feature type on its own?

**Comment by lvdbrink** [comment]
I was thinking about what should be in the core after our meeting yesterday. Going back to what is the essence of O&M, and forgetting for a moment what our current model looks like, it would make sense for the core to have observation, process, observed property and result, and probably feature of interest as well. This to me is the basis and I think (without having checked actually) these things are all mentioned in the definition of Observation. For me it would not make sense to even use O&M in cases where any of these elements are not needed. E.g. if a community is not interested in exchanging any information about the process (be it a procedure description, a sensor or whatever) I would tell them not to use O&M at all. 

Of course, we have no class Process in our current draft model... And it seems a bit much to add ObservingProcess, Observer and Platform.

**Comment by dr-shorthair** [comment]
> observation, process, observed property and result

Maybe observation, *observer*, observed property and result

**Comment by KathiSchleidt** [comment]
What I've never been clear on here is just how much adding these types to a conformance classes requires the user to use exactly those classes.

While the constellations of types proposed above all make sense, would this mandate referencing an ObservableProperty from within the model or would it be valid to also reference an external codelist?

Note: the reason we've made ObservableProperty more concrete is to provide the hooks for a later ObservableProperty model as to our understanding doing this from the V2 GF_PropertyType causes issues. An ideal solution would allow for both ways forward, ObsProps either by reference to some codelist somewhere, or if you have the time and resources, to a nicely structured model (great potential there, hierarchies of all ObsProps containing a substance, e.g. NO2 has a parent N. But still a bit on the horizon)

**Comment by ilkkarinne** [comment]
Do you think it would make sense to break the one-to-one mapping between the requirements classes and the UML packages? I do like the idea suggested by @cportele in some of our meetings that an abstract (conceptual level) specification is a toolbox for shared concepts that applications may want to use. On the other hand I also would like to able to define named sets of minimum requirements to help exchanging O&M data between systems and encodings without data loss.

For example the Basic Observations package provides this kind of convenient toolbox of concrete classes, but it does not make sense to require everyone to support all of them. It should be possible to cherry-pick one or two of these Basic Observations classes and not support the rest of them. For this kind of usage, I think we do not really need explicit requirements in the spec, we just need to introduce these concepts. Or maybe a recommendation to use the basicobs:Process class as the value of the process association of Observation unless there is a strong reason to us some other realization of abstractobs:Process.  

Additionally requirements classes stating that compliant systems shall support all the concrete classes of the Core or the Basic Observations could be useful too for interoperability: If two systems support all the the Basic Observations, they should be able to communicate about the Observations, Processes, Observers, Platforms, FeatureOfInterests and ObservationCollections preserving all the attributes and associations defined for these concepts on the Core and the the Basic Observations packages.
