### ISSUE TITLE
Observation Specialization

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#27]
Shall we continue to provide specialized observations, or should we shift to soft typing (would need observation types available via a common register)

**Comment by KathiSchleidt** [comment]
related to #18

**Comment by dr-shorthair** [comment]
I lean towards soft typing since the specialisations don't add any properties and only introduce a constraint. Of course in SOSA there are no specialised observations, but there is also less distinction between soft and hard typing in RDF.

**Comment by KathiSchleidt** [comment]
Is it possible to provide possible soft types for Observations within the OGC Registry? Would allow for soft typing of observation types
What is the current status of governance pertaining to the OGC Registry?

**Comment by dr-shorthair** [comment]
Aren't they already there? 
Gobe and RobA are running it now.

**Comment by KathiSchleidt** [comment]
Also related to #14

**Comment by KathiSchleidt** [comment]
The O&M 2.0 Observation Types are available here: http://www.opengis.net/def/observationType/OGC-OM/2.0/

**Comment by ilkkarinne** [comment]
As discussed in #47, the "type" attribute is now included in the proposed AbstractObservation UML class, see https://github.com/opengeospatial/om-swg/blob/master/iso_19156_issues/ea/2020-04-07_Observation.png

**Comment by dr-shorthair** [comment]
Implement with `dcterms:type` if it is just a tag or annotation, or `rdf:type` if it is an actual `rdfs:Class`

**Comment by KathiSchleidt** [comment]
Essential to provide good examples of soft typing, also how to transition from hard to soft typing

**Comment by KathiSchleidt** [comment]
Also need the references for the types, need by result type, nice-to-have by FoI type as example
