### ISSUE TITLE
O&M Core requirements

### ISSUE THREAD

**Issue by ilkkarinne** [opengeospatial/om-swg#29]
Which requirements and data structures to include in the ISO 19156 O&M Core requirements class, and how to define extension points in the core data model for the extensions?

The O&M core should be the minimum implementable O&M model by itself, but also a solid base for the more comprehensive O&M Observation data models.

**Comment by KathiSchleidt** [comment]
Maybe add a note to the carrierOfCharacteristics for those who prefer not to read the specification that this association is informative

**Comment by ilkkarinne** [comment]
Hi a draft Observation core UML class diagram for discussion now available at https://github.com/opengeospatial/om-swg/blob/master/iso_19156_issues/om_core_uml_draft.png

**Comment by ilkkarinne** [comment]
It was suggested by @sgrellet and agreed in the SWG meeting held on 4 December 2019 that the group would first try to get a complete picture of all the requirements, and only then, if deemed necessary, consider splitting the model into a core and extensions.
