### ISSUE TITLE
Ultimate Feature of Interest

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#3]
An explicit property on observations to link to a description of the sampling   strategy (perhaps a sampling-feature) alongside the feature-ofinterest – this clarifies some semantic confusion around the relationship between observed properties and feature-of-interest type

Source: TC211 Comments AU001,   PMG0010

**Comment by KathiSchleidt** [comment]
Same as http://isotc211.standardstracker.org/show_request.cgi?id=111

**Comment by KathiSchleidt** [comment]
Same as http://ogc.standardstracker.org/show_request.cgi?id=246
Simon:
The Observation class has a single property (feature of interest) whose value may be either a domain feature or sampling feature. This creates challenges in satisfying the basic integrity constraint (that the observed property must be consistent with the foi) and also in determining what the ultimate feature of interest is. 
Introduce an additional (optional) property to link to the sampling strategy or feature; reserve the feature-of-interest property to refer to only the ultimate domain feature whose property is being observed. 
Continuing confusion around the use of sampling features. 
Locations: 7.2.2, 7.2.2.7, 7.2.2.12, 9.1.1, 9.2.2.4, Figure 10.

**Comment by KathiSchleidt** [comment]
Further confirmed by SoilIE Implementation Results:

8.	There were conceptual difficulties implementing O&M observations. The ‘featureOfInterest’ as used in the O&M Abstract Specification is inconsistently applied in implementations, representing either the immediate sampling feature or the ultimate domain specific sampled feature.

**Comment by KathiSchleidt** [comment]
SoilIE Recommendation helps clarify/constrain (p 64):

4.	Change the O&M abstract specification to add ‘samplingStrategy’ to O&M Observation and restrict ‘featureOfInterest’ for the feature with the observed property (as per [9], Table 13).

**Comment by dr-shorthair** [comment]
Proposed in https://www.w3.org/TR/vocab-ssn-ext/#ultimate-feature-of-interest 
Implemented by TERN in https://bitbucket.org/terndatateam/ternplotdata-ontology/src/master/

**Comment by KathiSchleidt** [comment]
Source: http://ogc.standardstracker.org/show_request.cgi?id=602
 Sylvain Grellet 2019-09-09 13:38:42 UTC

The observation pointing to a proximate/ultimate fOI is always an important discussion point when implementing OM on a new domain/system
Evolutions already explored by om-lite and ssn-ext should be brought back to the conceptual model
Adaptate extract from ssn-ext on the topic : In some cases the fOI provided is is not ultimate thing that the observation, act of sampling is concerned with, but is an intermediate thing, often a sample of the ultimate feature of interest, or perhaps a sample of a sample, etc. Nevertheless, particularly for discovery purposes, it is usually the ultimate feature of interest that really matters to the data user. More details here: ﷒0﷓

Potential overlap with a previous CRPs from Alex Robin (2018-02-21, assigned OGC document 09-180) : ﷒1﷓

**Comment by sgrellet** [comment]
@ilkkarinne  : ok to also be assigned to that issue

**Comment by ilkkarinne** [comment]
Thanks @sgrellet !

**Comment by sgrellet** [comment]
Issue to keep track and clarify our common understanding of Toulouse TC Monday discussions (Nov.18th). 
Are we all clear that the current (O&M v2) featureOfInterest (fOI) association role is to be split in two associations ?
- one to what was called ultimate fOI in many OM related discussions (and renamed in the latest om-swg discussions)
- and one to what was used as the '1st level' fOI often (not always) sampling related and pointing in turn to the 'domain' Feature that was monitored.

If yes, I'm going to close that issue and we'll have dedicated issues to refine the semantics of the two new associations.

**Comment by sgrellet** [comment]
In the light of #35, 'Sample' (SF_Specimen) are not meant to be concerned by the fOI role anymore.
Currently wondering whether we could still have a 'what is my fOI/ultimateFOI' discussion without them as most of the examples of such discussions (ex : see https://www.w3.org/TR/vocab-ssn-ext/#ultimate-feature-of-interest) do involve a 'Sample'

From a datadiscovery point of view I think yes, but prefer checking I'm not overthinking this
One example: surface water quantity monitoring
- an hydrometric station generates observation about water level at a given location (often pointing to a river segment identifier) -> river segment = uFOI
- but one may want to also attach that observation to the watershed to support other search for data (esp if the segment is the furthest downstream the watershed) -> watershed = fOI ?

If yes we may then need
- A/
	- 2 associations to GFI_Feature : a fOI (0..*) and a uFoI (1)
	- AND to agree on the semantics of the word 'ultimate' : the finer or coarser grain of information? In my example above, I chose it to be the finer grain of information 
- or B/ : don't rename fOI, just relax its cardinality but from the observation there won't be a way to know about the hierarchy of its fOIs

**Comment by dr-shorthair** [comment]
SSN-Ext is about to go to next Public Working Draft. Editor's draft is here: https://w3c.github.io/sdw/ssn-extensions/ Note that I modified some property names to be less disruptive to you guys - https://w3c.github.io/sdw/ssn-extensions/#fig-sample-chain-geology shows an example.

**Comment by sgrellet** [comment]
@dr-shorthair: thanks for this. We are exactly discussing this part of the model right now in the SWG meetings (see  https://github.com/opengeospatial/om-swg/issues/35#issuecomment-574606145)

**Comment by sgrellet** [comment]
@KathiSchleidt , @ilkkarinne : #35 being closed, I think we can close this one as well.
