### ISSUE TITLE
Rename Sensor to Observer

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#30]
As proposed in Toulouse, by renaming the SOSA Sensor to Observer, we finally get rid of the eternal question of what to do if you don't have a sensor

Spun off of #18

**Comment by ilkkarinne** [comment]
Any objection to using the ```Observer``` name class in the model instead of ```Sensor```?

[A related question](https://github.com/opengeospatial/om-swg/issues/20#issuecomment-585095300) in #20: Do we additionally want to have an abstract ```Sensor``` subclass of ```Observer``` there as an easry-to-find placeholder for the people looking for a place to plug in their sensor domain model or does it complicate the conceptual model needlessly?

**Comment by dr-shorthair** [comment]
I like Observer - it is a much better name than Sensor. It allows us to make 'sensor' a true sub-class. Good improvement.

**Comment by dr-shorthair** [comment]
Maybe submit an issue here too: https://github.com/w3c/sdw/issues 
At the very least the documentation of `sosa:Sensor` could also include the term 'Observer'. 
But maybe propose a super-class `sosa:Observer`. I'll let you guys do it though.

**Comment by sgrellet** [comment]
Will do it

**Comment by sgrellet** [comment]
Notes from 11/03 telco : the definition of OM V3 Observer class should include the following "_Device (sensor), agent (including humans), or software (simulation) ...._'. Which a really slightly adjusted definition from sosa:Sensor.

The OM group agrees that, so far, we feel we don't need further modelling like subtyping Observer into Sensor and other classes.
I will reflect this as well in the SOSA GitHub Issue.

Note : discussions on OM V3 Platform may trigger other aspects

**Comment by dr-shorthair** [comment]
> Note : discussions on OM V3 Platform may trigger other aspects

Indeed. Where there are potential adjustments to SSN/SOSA it would be helpful to have these reflected over to the /w3c/ GitHub repo, with cross-references to the /opengeospatial/ issues.
