### ISSUE TITLE
Concrete ObservableProperty

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#31]
Modify observed property class from metaclass GF_PropertyType to featureType in order to allow for specialization of observable properties
Related to the Object of Interest discussion #21

**Comment by KathiSchleidt** [comment]
As all requirements for ObservableProperties (Object of Interest etc) can be packed behind the ObservableProperty, we will postpone such discussions until the core ISO O&M Standard has been finalized

**Comment by KathiSchleidt** [comment]
Can be left as a metaclass

**Comment by sgrellet** [comment]
+1 we'll document  #21 according to 2020/01/15 webconf
