### ISSUE TITLE
Any for Metadata and Result

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#34]
Again spinning off of Potential Observation #18 
I'm very happy with doing a true ANY for both Metadata and Result, question is if the interface approach is correct

**Comment by KathiSchleidt** [comment]
Description of metadata clause must be updated in accordance with type any. related to #12 
Add informative note that we do not wish to restrict the type; however, within domain specific profiles, this may be restricted as required.

**Comment by ilkkarinne** [comment]
Any class is currently used as the target of both the associations ```result``` and ```metadata```. Any objections to making this an initial decision?

**Comment by ilkkarinne** [comment]
The metadata role description should say that the it should point to a well-know metadata desription

**Comment by ilkkarinne** [comment]
Conforming implementations should consider restricting this according to the community / use case needs
