### ISSUE TITLE
Abstract Observation

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#36]
We've been developing the idea of remodelling the observation, creating an abstract observation from which we can then derive an OM Observation, Potential Observation, Observation Template, Observation Collection, etc.
To date mostly discussed under #18 modelling the Potential Observation.

**Comment by ilkkarinne** [comment]
At the SWG meeting on 29 Jan 2020 we agreed that we need to go through the upper limits of the cardinalities of each of the associations and attributes of the AbstractObservation. There does not seem to a  case for allowing more than one ```result```, but what about the rest? The current [draft UML class ](https://github.com/opengeospatial/om-swg/blob/1485219fe65d91b158fd5064f0f1eefb223e6ac5/iso_19156_issues/ea/Edition2_playground_snapshot.png) has the following properties:

Inherited from ```AbstractEvent```
- ultimateFeatureOfInterest: AnyFeature[0..*]
- proximateFeatureOfInterest: AnyFeature[0..*]
- usedProcedure: Procedure[0..*]
- parameter: NamedValue[0..*]
- resultTime: TM_Instant[0..1]
- stimulusTime: TM_Instant[0..1]

Defined in ```AbstractObservation```:

- phenomenonTime: TM_Object[0..1]
- resultQuality: DQ_Element[0..*]
- validTime: TM_Period[0..1]
- observedProperty: ObservableProperty[0..*]
- madeBy: Observer[0..*]
- metadata: Any[0..*]
- relatedObservation: AbstractObservation[0..*]
- result: Any[0..1]

**Comment by ilkkarinne** [comment]
Related to this: I extracted a few properties of ```AbstractObservation``` into class ```AbstractEvent``` (not entirely happy with the name) to support the need for a common ancestor to both Observation and SOSA style Sampling.

Both the sosa:Sampling and the sosa:Observation have ```featureOfInterest```, ```usedProcedure```, and ```resultTime``` properties, so it made sense to try and extract the common things into a shared abstract parent class. Both also share the ```hasResult``` property, but for sosa:Observation it points to generic sosa:Result and for sosa:Sampling into sosa:Sample, so it maybe better to have the ```result``` property defined separately for the two cases.

I also moved to ```parameter``` association into the ```AbstractEvent``` to keep it together with the ```usedProcedure```.

**Comment by ilkkarinne** [comment]
Rolled back the AbstractEvent( issue #40) for now until properly discussed among the SWG members as decided in the 5 Feb 2020 SWG meeting.

**Comment by dr-shorthair** [comment]
Need to be a bit careful about the word 'Event'. In ISO 19108 or 19103 or somewhere quite low in the stack, event=instantaneous. 

In the ontology space the terminology more often used is 'Activity' (`prov:Activity`) or 'Occurrent' (`bfo:Occurrent`) (and perhaps 'perdurant').
