### ISSUE TITLE
Split into a Multipart Standard?

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#37]
Looking at the timeline and our ambition, it could make sense to split O&M into a multipart standard:

- Part 1: Observation
- Part 2: Sampling
- Part 3: Observable Properties?

Ideal would be if we would only have to provide part 1 for the current deadline, could then properly adjust sampling to SOSA deliver a few months later, then have time for the ObservableProperties

**Comment by sgrellet** [comment]
+1 : seems more realistic to me.
One could add.
- Part 4 : Process (see "Lineage of observations" discussion)

**Comment by ilkkarinne** [comment]
I have requested Mats' comments and information on this by email today, let's see how practical this approach would be following the ISO process

**Comment by ilkkarinne** [comment]
Based on Mats' reply, splitting 19156 into multiple specification parts would not be easy: 

- first the ISO WG9 convenors should be convinced that this is a better idea than keeping the 19156 content in a single specification.
- if they would agree, have an ISO/TC 211  resolution or ballot to stop the project and restarted as two projects (-1 and -2).
- have an agreement on if the parts would be done one after by the same project team / lead or if there should be separate call for the part 2 (or the other parts).

We maybe able to get one more extension on the CD ballot, and I would personally prefer using that to include the core observation, sampling and observable properties as separate requirements classes, but let's discuss this in the SWG meeting.

**Comment by KathiSchleidt** [comment]
Better to leave as a 1-part std but request one more extension.
Try and get the Observation part sorted by end of March, then focus on Sampling
@ilkkarinne to check postponement

**Comment by ilkkarinne** [comment]
The decision on this issue was postponed while waiting for confirmation on whether we could get an extension to the deadline for submitting the CD version of the revised ISO 19156. The current deadline is on 4th September 2020, so we should now have enough time to cover all the issues without a need to split the document.

**Comment by ilkkarinne** [comment]
It was decided to in the 11th March 2020 SWG meeting that splitting of the 19156 would not be proposed.
