### ISSUE TITLE
has or has not?

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#38]
Do we adjust all relations to the semantic world (align with SOSA) with has/is prefixes or do we leave them as is?
Advantages: Alignment with SOSA, clear semantics
Disadvantages: change of all relations, difficulty in upgrade to V3

**Comment by cportele** [comment]
ISO 19103 has a related recommendation:

> Recommendation 13. UML elements should keep names as short as practical. Use standard abbreviations if understandable, skip prepositions and drop verbs when they do not significantly add to the meaning of the name.

Using verbs is a matter of taste or community practice. In ISO/TC 211 properties have typically been called xxxx instead of hasXxxx or isXxxx and that is reflected in the recommendation. In case of a preference to align with SOSA, I would suggest to discuss this first with the HMMG before editing everything.

**Comment by dr-shorthair** [comment]
Indeed. The semantics community often (but not always) adds 'has/is' and 'of' to the relation name, as it often clarifies the directionality of the relation. But this is less common in UML.

**Comment by ilkkarinne** [comment]
Comment from John Herring on Fri 24 Jan:

> In general, most of the models in the ISO UML Harmonized model use
> "nouns" to describe attributes and associations. Probably to minimize
> the length.
> 
> Attributes tend to nouns, usually associated to the value's object
> class. Associations name can be simple verb clauses but role names tend
> to nouns.
> 
> It is probably okay either way. But keeping things short tend to be a
> good idea.
> 
> You might ask Knut Jetland, as he is now, officially, the ultimate
> repository on arcane knowledge of the harmonized model. See
> https://committee.iso.org/sites/tc211/home/re.html which lists ISO/TC
> 211 Resources.
> 
> Personally, I've always used nouns, both in models and in code.

**Comment by KathiSchleidt** [comment]
something is not properly aligned in the role names on the associations
Insight from Linda: check what's verb vs noun
I'll do a table with all associations and roles to allow us to reflect this.
In addition, we should clarify which associations are unidirectional, which should be raised to bidirectional

**Comment by ilkkarinne** [comment]
SWG members seem to agree that the intention to keep the SOSA and O&M models harmonized is not reason enough to bring the "is/has" prefixes currently used in SOSA associations as-is into the O&M class association role names.

**Comment by dr-shorthair** [comment]
I find is/has useful to indicate the direction of the association, which is not always clear without.
