### ISSUE TITLE
Maintain Domain & Range

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#39]
Does the inclusion of Domain and Range as names for these two associations really help or could we drop this.
Upside: to my view it nicely aligns the O&M Observation with semantic relations (to my view, Obs is an n-ary relation, Domain and Range provide the core relation, other associations are information on the relation)
Downside: unclear if Domain pertains to proximate or ultimate FoI 

@dr-shorthair what do you think?

**Comment by ilkkarinne** [comment]
In the latest UML model draft the ultimateFeatureOfInterest association has tentatively been named ```Domain``` and the proximateFeatureOfInterest association ```DomainProxy```.

Personally I think that for consistency neither the Domain nor the Range names should be used or both of them. For the second option I'm open for suggestions for a better name for the proximateFoI association, or leaving it out completely.

**Comment by KathiSchleidt** [comment]
Agreed, awaiting final decision
logic also to do with maintaining alignment with the coverage world

**Comment by lvdbrink** [comment]
> Would prefer to maintain as provides alignment to the semantic world.
> logic also to do with maintaining alignment with the coverage world

+1

**Comment by sgrellet** [comment]
> Would prefer to maintain

+1
 -> Should we label this 'Final decision' ? The latest version of the model (2020-08-21_Observation_Core_overview.png) already have it.
