### ISSUE TITLE
Stimulus-time

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#4]
An   additional temporal property ‘stimulus-time’ alongside phenomenon-, result-   and valid-time – this further clarifies the understanding of some   observational strategies where this does not correspond with either the   result- or phenomenon-time

Source: TC211 Comments AU001, PMG011

**Comment by KathiSchleidt** [comment]
Same as http://isotc211.standardstracker.org/show_request.cgi?id=111

**Comment by KathiSchleidt** [comment]
We need a clear use case
Medical, inject contrast stuff
Geosciences, a stimulus is set (bang), various measurements measure the propagation
Radar - ping goes out (stimulus Time), reading the blip back is phenomenon time

**Comment by KathiSchleidt** [comment]
Further example - cloud seeding?

**Comment by KathiSchleidt** [comment]
Maybe add a further temporal attribute towards modelling, start of modelling

**Comment by ilkkarinne** [comment]
From the  [OGC Best Practice for using Web Map Services (WMS) with TimeDependent or Elevation-Dependent Data](https://portal.opengeospatial.org/files/?artifact_id=56394) (OGC  12-111r1) by the MetOcean DWG):

> The most pervasive temporal dependency comes from data values having different chronological times: observations may have been recorded at different moments, models may be predicting conditions for different days, alerts may refer to conditions expected at certain moments in the future, and warnings may apply to the entire duration of a time interval or part of it. This document adopts the phrase 'validity time' in reference to this type of temporal dependency despite the potentially misleading natural language association of the root 'validity.' This concept is essentially identical to the concept of 'phenomenonTime' from the standard ISO 19156:2011, Geographic information -- Observations and measurements.

And further:

> 6.2.2 REFERENCE_TIME axis
Data providers may wish to offer data that have a second temporal dependency other than the 'validity time'. Examples are the start times of numerical weather calculations or the sending times of warnings.
The semantic meaning of a second temporal dependency may differ for different types of data, but the usage pattern has broad application. This Best Practice document recommends the use of a dimension called REFERENCE_TIME if the domain values of this dimension can be restricted to timestamps.

**Comment by soreslaszlo** [comment]
In exploration geophysics recording against time is very typical.  
However, in the cases mentioned by Kathi exact positioning in a time frame is not so important.
What really matters is the elapsed time after the trigger pulse. That is measured by the system and recorded together with other physical attributes changing with time (e.g in a swe:DataRecord). In this scenario elapsed time is rather an observedProperty and stored as part of the result.
Usually elapsed time is in the range of microseconds, miliseconds, and the measuring process is repeted many times to get statistically robust results. Trigger time my be recorded as a processParameter, but phenomenonTime is usually enough for documenting the date of measurement. 
I do not see an urgent need to extend the data model with stimulus-time here.

**Comment by ilkkarinne** [comment]
@dr-shorthair: could you please provide further justification for adding the stimulusTime attribute and if possible point us to examples of cases where this is needed? We may have to drop this attribute if we do not find solid justification for adding it.

**Comment by dr-shorthair** [comment]
Understood. I've never seen it used directly myself, but wrote it in 
(a) as part of a general consideration of all the possible 'times' involved in an observation
(b) in order to align (close the loop with) with the [stimulus-sensor-observation](https://www.w3.org/2005/Incubator/ssn/XGR-ssn-20110628/#The_Stimulus-Sensor-Observation_Ontology_Design_Pattern) design pattern that was developed during the design of the original SSN ontology. 

It did seem to me that there was a potential value in calling out the sensor-stimulus-time as a discrete piece of the puzzle. But I also understand that the art-and-science of information modelling involves making choices among all the potential elements that might be included.

**Comment by KathiSchleidt** [comment]
Agreed that we do not require this. Thus closing
