### ISSUE TITLE
Observed property and the observed phenomenon

### ISSUE THREAD

**Issue by ilkkarinne** [opengeospatial/om-swg#43]
I was figuring out the stereotypes for the "upper part" of the UML diagram classes, that is Procedure, Observer, Platform and ObservableProperty today. The Observer and Platform feel easy: they are obviously of feature types. The Procedure was also smells to me like a feature type, although as a description of a method it may not have a real-world spatial or temporal counterpart counterpart.

The ObservableProperty feels a bit different to me: it's basically just a name for the particular aspect of the FoI that we can or have observed. Would it thus make sense to define the ObservableProperty as a DataType?

One of the  constraints of the OM_Observation class in O&M 2.0 states that "observedProperty shall be a phenomenon associated with the featureOfInterest". I find this wording interesting, as it touches a concept that we have not yet explicitly modelled: a phenomenon. The statement that "observedProperty is (or shall be) a phenomenon" seemed right at first, but then I started doubting myself: does the observed property really equal the observed phenomenon?

If we observe the color of a (surface of a) bridge for example: 
* A small part of the the surface layer is the proximateFoi,
* the bridge as a whole is the ultimateFoi,
* the color determination by analysing the wavelength of the reflected white light would be the usedProcedure,
* a color would be the observedProperty,
* a colorimeter combined with a standard white light source would be the Observer, and
* the color value (as a RGB values, a category or name) would the the result.

To me observed phenomenon in this case would be one in which the wavelength of the reflected light is affected by the properties of the observed surface in a particular way. We observe this phenomenon happening on a particular FoI at a particular time using a particular method of sampling and analysing the reflected radiation and mapping the analysis results into a color definition. The observed property color would be the same for cases where a color of a light source would be observed, but the observed phenomenon would not be the related to change of the color in reflection but the one in which the light source emits radiation with a particular spectrum. 

Do you think that separating the observed phenomenon from the observed property would be useful in the O&M conceptual model?

**Comment by cportele** [comment]
> Would it thus make sense to define the ObservableProperty as a DataType?

No, a data type has no identity (and you cannot reference it, it always is an embedded value). I should be a class and I would assign no stereotype - or we specify a new one, but I don't think any of the stereotypes from ISO 19103 or ISO 19109 apply.

> "observedProperty shall be a phenomenon associated with the featureOfInterest"

What this means is that the feature of interest could have a property with the same semantics as the observed property. E.g., a bridge feature could have a property "color". There is some more discussion about this in sections 7.2.3 "Properties and observations" and  7.4.10 "Value assignment" in ISO 19109.

For me the current wording is correct as it is.

**Comment by dr-shorthair** [comment]
Observable Property is tricky, because in terms of a normal application schema it is on a different meta-level. We had to have a story about this in the ISO 19109:2015 revision where we introduced O&M into the General Feature Model. 

> 8.9	Rules for the use of observations
> An observation is an act in which a procedure is used to estimate the value of a property. The properties of an observation provide metadata for the value assigned to a feature property, for example: the description of the procedure and the time that the observation of the value was made. Observation is an important instantiation of the ValueAssignment metaclass (7.4.10). The relationships between observations, and the features and properties whose value assignment they document, are shown in Figure 36.
>  
> Figure 36 — Key elements of the observation schema (ISO 19156:2011) related to General Feature Model (Clause 7)
>
> It is unusual to have relationships other than dependency or realization that cross metalevels. However, they are included in the model shown in Figure 36 because this expresses requirements of property-value metadata. Without a common mechanism every application schema with this requirement is likely to model it differently. This model was introduced in ISO 19156:2011 to provide a common pattern, and is included here to support a rule for application schemas. 
>

**Comment by cportele** [comment]
@dr-shorthair - Didn't we say in the 19109 discussion that ObservableProperty is a "proxy class" for the GFM metaclass PropertyType and that it is ok to keep it in 19156 as it is? Also because the application schema that has the PropertyType will often not have been formalized even though it implicitly exists. Or did we agree that in a future 19156 revision this should be changed to an association to the metaclass PropertyType as shown in figure 36? 

(Sorry, don't really remember, this is too long ago.)

**Comment by ilkkarinne** [comment]
@dr-shorthair: We discussed the ```carrierOfCharacteristics``` relation between ```GF_PropertyType``` metaclass (pointed to via observedProperty) and the ```GF_FeatureType``` metaclass in O&M 2.0 in the Toulouse TC meeting last September, and decided not to include this relation in the O&M 3.0 model as it was not really used in any of the known applications. Also there was a string argument expressed that the observedProperty needed not be one explicitly included in the FoI model object as a named property, but it could be more vaguely related to it: the application domain model class for a Bridge did not have to contain a property named "color" in order to be able to say that and Observation had been made for observedProperty "color" with an instance of the Bridge class as the FoI.

**Comment by ilkkarinne** [comment]
The requirement ```/req/observation/property``` in the ISO 19109:2015 IMHO seems to require that the observed property shall be one that's explicitly defined for the FoI as it's property:

> The value of observed-property in data conforming to the application schema shall be constrained to be a property-type from the feature catalogue for the
> application schema, and shall be a characteristic property-type for the fea- ture-type of the feature-of-interest.

**Comment by ilkkarinne** [comment]
I'm closing this, it seems to me that it's just about different levels abstraction for choosing the observed property in different cases. Sometimes it makes sense to describe the wavelength of the light as the observed property, sometimes the color interpretation of it is a more sensible choice.

I believe the relations between can be best solved by leveraging observed property ontologies.

**Comment by KathiSchleidt** [comment]
Agreed by Quorum

**Comment by dr-shorthair** [comment]
Not every property is 'observable'. For example, names and ownership. Similarly, not every feature is 'of interest'.

**Comment by KathiSchleidt** [comment]
We wanted to avoid the ```carrierOfCharacteristics``` relation as this has only caused confusion

As the class is named ObservableProperty, I do not see issues as described above (we're only dealing with the Observable ones, names and ownership are rarely provided via an Observation)

Does this clarify?

**Comment by dr-shorthair** [comment]
OK
