### ISSUE TITLE
Abstract classes in the UML model

### ISSUE THREAD

**Issue by ilkkarinne** [opengeospatial/om-swg#45]
There has been discussion on which classes in the draft O&M UML model should be left abstract and which not. Especially SWG members have requested to make the Platform, the Observer and the Procedure concrete rather than abstract. The general feeling I sense in the SWG is that what ever the minimal [O&M core requirements class](#29) would contain, it should be possible to implement it without the need to create new concrete classes. Thus for all the abstract classes there should be at least one concrete subclass available in the core able to provide the minimal required information for O&M dataset interoperability.

**Comment by ilkkarinne** [comment]
The ```Platform```, ```Observer```, ```ObservableProperty``` and ```Process``` are now concrete classes in the [latest UML diagram](https://github.com/opengeospatial/om-swg/blob/master/iso_19156_issues/ea/Edition2_playground_2020-03-16_Observation.png).

Both the ```ObservableProperty``` and ```Process``` now have stereotype ```Type```. This may be incorrect, I remember @cportele [commenting before](https://github.com/opengeospatial/om-swg/issues/43#issuecomment-592399215) that there is really no fitting stereotype in either ISO 19103 or ISO 19109 to apply for the ObservableProperty. What I wanted to achieve were concrete classes with the very basic attributes similar to ones in AbstractGMLType (identifier, name and description). Should we explicitly add these attributes in these classes instead of using the stereotype "Type"?

**Comment by ilkkarinne** [comment]
Based on the SWG discussion on 1 April 2020 I have now changed the stereotype of Procedure back to FeatureType, it was felt that it provided better compatibility with existing Process description models such as SensorML.

ObservableProperty now has no stereotype again.

**Comment by KathiSchleidt** [comment]
If ObservableProperty is not FT, then same should apply to Procedure, both are non-concrete things
Procedure was FT in V2, partially due to use of SensorML
We need to be able to provide both of these classes, whereby the ObservableProperty  may also be a reference to an external codelist.
Keep in mind cases where ObservableProperty could actually be linked to each other, hierarchy/ontology

**Comment by KathiSchleidt** [comment]
@cportele What type can we use for non-spatial objects that are first-class citizens? 
featureType seems strange as non-spatial
is just type allowed in GML?

**Comment by cportele** [comment]
@KathiSchleidt - When you say "is type allowed in GML" I assume you mean "is «type» supported in the GML encoding rule for application schemas modelled according to ISO 19109"? In that case the answer would be "yes".

**Comment by KathiSchleidt** [comment]
@cportele But to my memory, while «type» can be encoded, it cannot be provided via a WFS
Also - what's the difference between «type» and «dataType»?

**Comment by cportele** [comment]
> But to my memory, while «type» can be encoded, it cannot be provided via a WFS

Sure, WFS is a Web *Feature* Service.

> Also - what's the difference between «type» and «dataType»?

Instances of type are objects, instances of dataType are values.

**Comment by KathiSchleidt** [comment]
@cportele Now I'm thoroughly confused!
In all the models I've seen to date in INSPIRE, OGC, ISO «dataType» is used to define object types
Example from O&M V2:
![dataType](https://raw.githubusercontent.com/DataCoveEU/INSPIRE-STA-Good-Practice/master/datatype.png)

**Comment by cportele** [comment]
@KathiSchleidt - I assume "object type" = "class"? Then the answer is "no". A classifier with «dataType» is not a class. "NamedValue" as shown in your diagram is not a class, it is a data type, which is a different kind of classifier in UML.

Have a look at the UML standard or, e.g., at https://www.uml-diagrams.org/data-type.html.

**Comment by ilkkarinne** [comment]
I'm not sure what would be the benefit of using the ```Type``` stereotype in 19156. The only definition I have managed to find for it is in GML:

> \<\<Type\>\> is a set of abstract attributes and associations. Abstract means that their specification does not
imply that they have to be concretely implemented as instance variables.

I agree that it's not semantically consistent to define the Process as a feature but ObservableProperty not. The difference I do see between these two is that while the process association sometimes refers to a feature (like when using SensorML), the observed/observableProperty association is not likely to do so. Even if it would not be defined as a code list value reference, but a more dynamic resolvable entity (RDF concept with links to other related concepts etc.), it should not be too difficult to server it in outside the WFS functionality.

It's not 100% clear to me if ObservedProperty could or could not be defined as a feature as defined in 19109: "A feature is an abstraction of real-world phenomena." A "color" or "temperature" properties could be seen as abstractions of real world phenomena, right? However, would like to leave the door open to applications defining their observedProperties as non-features too. Would it be valid to define the AbstractObservableProperty (in the core) without any stereotype and the concrete ObservableProperty in the Basic Observations with the FeatureType stereotype? And if ok, would that be any better solution than leaving both without the stereotype of have both defined as FeatureType?

**Comment by ilkkarinne** [comment]
I tentatively removed the empty classes AbstractProcedure and AbstractObservableProperty from the Core package, linked the ```Observation.procedure``` directly to the Observation interface and the ```Observation.observedProperty``` as well as the ```AbstractObserver.observableProperty``` directly to the ObservableProperty interface. To me these empty abstract classes did not add any value to the model, and made in less flexible to use existing domain model classes for Procedure and ObservableProperty.

And comments more than welcome.

Snapshot images for comparison:

- Observation core: [2020-07-01](https://github.com/opengeospatial/om-swg/blob/master/iso_19156_issues/ea/2020-07-01_Observation_Core_overview.png) vs. [2020-07-23](https://github.com/opengeospatial/om-swg/blob/master/iso_19156_issues/ea/2020-07-23_Observation_Core_overview.png)
- Basic Observations: [2020-07-01](https://github.com/opengeospatial/om-swg/blob/master/iso_19156_issues/ea/2020-07-01_Basic_Observations_overview.png) vs. [2020-07-23](https://github.com/opengeospatial/om-swg/blob/master/iso_19156_issues/ea/2020-07-23_Basic_Observations_overview.png)

**Comment by ilkkarinne** [comment]
I kept the ``AbstractObserver``` and the ```AbstractPlatform``` in the Core, as they have associations to other classifiers (so not empty), as well their association class Deployment.
