### ISSUE TITLE
Provide textual description for the UML classes

### ISSUE THREAD

**Issue by ilkkarinne** [opengeospatial/om-swg#46]
This issue is an umbrella one for putting the drafting of the [textual descriptions for the proposed UML classes and associations](https://github.com/opengeospatial/om-swg/blob/master/iso_19156_issues/Class%20Definitions.md) on the table. 

Specific parts of the text drafting will be spawed out of this issue as needed.

**Comment by KathiSchleidt** [comment]
Hi all,
took a bit longer than planned, but all definitions are now in the following google doc:
https://docs.google.com/document/d/1rbtyRuJV56qZfo_YOhcNYi-VQ9Giyt7A-9vuuo01qLI/edit?usp=sharing

I've also added definitions from SOSA, will start proposing definitions for V3

The link above only gives you comment rights, for edit, please request

**Comment by ilkkarinne** [comment]
Hi all, I've now added the constraints from the draft UML model to the Google doc

**Comment by rhaener** [comment]
Added an image of an UML diagram modelling Observation and ObservationCollection
