### ISSUE TITLE
Soft Typing

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#47]
How do we define soft typing? Can this be specified within the UML conceptual model, or is this only expressed in the XML encoding?

In O&M V2 it was introduced on the XML level, but not in the UML. This has led to confusion (I focused on the UML and didn't really notice until recently!)

We'd like to explicitly add it to the UML, is this OK?

Also, we'd like to apply it to the Observation Collection concept as a way of bridging the continuum between Homogeneous and Summarizing Collection Characteristics

**Comment by KathiSchleidt** [comment]
Collection Characteristics Types identified (to date):
* Homogeneous 
* Summarizing 
* STA-like (Homogeneous but including spatio-temporal envelopes)

**Comment by afeliachi** [comment]
IMHO from an ontological point of view  (and it may apply to UML also) there is no problem of having a mix of soft typing and hard typing in the same model, whether these typings are repetitive or not.
How ever, for the sake of consistency, constraints must be added on the soft typing (on the values of the soft typing property) for the subclasses, so they correspond logically

**Comment by KathiSchleidt** [comment]
Good point - how do we provide constraints under a soft-typing paradigm?
As we plan to reference the soft types, would be really cool if the constraint information where somehow available from the external registry being referenced, but missing some good practice here - are you aware of anything?

**Comment by dr-shorthair** [comment]
‘constraints’ under OWL semantics are really entailments.
You can say what you want, but there may be implications that you don’t like, based on the OWL Restrictions and RDFS global constraints.

Validation is not really a thing under RDFS or OWL semantics.
If you want validation, then SHACL or ShEX is what you are after …

**Comment by afeliachi** [comment]
totally agree with @dr-shorthair 's statement.
Plain OWL/RDFS constrains/restrictions have a meaning when working in a semantic reasoning fashion. 
Shape constraints is the way to go. Will provide you an example of how.

**Comment by ilkkarinne** [comment]
What we had in mind at our last SWG meeting on 1 April was adding explicit "type" attributes pointing to code lists to the AbstractObservation and ObservationCollection UML classes. An initial set of the code list values would be provided within the O&M 3.0 spec (perhaps using the OGC NA definitions service?) and the lists would be defined as open for extending with new values later.

This would probably mean describing the constraints for the soft-typed features with the code list value definitions and providing encoding specific validation rules with the encoding specs (such as schematron, JSONSchema, SHACL etc.).

The most recent UML model aligned with this thought is available at https://github.com/opengeospatial/om-swg/blob/master/iso_19156_issues/ea/2020-04-07_Observation.png

**Comment by KathiSchleidt** [comment]
In O&M V2, the following result types are foreseen:
* Result-types for specialized observations (Table 3)
  * OM_Measurement
  * OM_CategoryObservation
  * OM_CountObservation
  * OM_TruthObservation
  * OM_TemporalObservation
  * OM_GeometryObservation
  * OM_ComplexObservation
* Result-types for specialized observations
  * OM_DiscreteCoverageObservation
  * OM_DiscretePointCoverageObservation
  * OM_DiscreteTimeSeriesObservation

These are also available from http://www.opengis.net/def/observationType/OGC-OM/2.0/

Currently missing are types for SWE Results:  SWE Array Observation and SWE Scalar Observation, see #15 

Unclear is why we're only specializing observations by result type, why is this association different from the others. It would make just as much sense to specialize by ObsProp or FoI type (would require multiple types as proposed in #48)

**Comment by dr-shorthair** [comment]
Indeed. That's why I don't really want to see these types taken too seriously. There may be business rules that tie particular result types to particular applications, but not sure that these merit named classes. The whole point of the generic O&M model is that the same model or data-structure applies across result-types, features-of-interest, observed-properties ...

**Comment by KathiSchleidt** [comment]
The not taking the observation types too seriously is exactly the reason I've been pushing for soft typing. Part of the background was a customer pushing me towards hard subtyping of Observations based on FoI Type, this got me to really thinking on the typing in general. 
I came to the conclusion that all information is there anyway, reasoners should be able to extract this easily. IMHO the real use of the type information is more on the usage level, a simple way of understanding if this Observation meets my data requirements.
If we allow provision of multiple soft-type references, we can still provide this usability advantage while keeping the generic simplicity of O&M.

ToDo: 
* Assure that the list of ObservationTypes by ResultType is complete #15 
* Remove the constraint that the type MUST reference only one OGC Codelist
* Maybe provide an alternative set of ObservationTypes based on ???

**Comment by ilkkarinne** [comment]
In the SWG meeting on 22 Apr it was decided that we want ```observationType``` attribute used for the soft-typed categorisation of Observations to formally point to a generic code list instead of the particular instance of a more-or-less fixed (or slow-to-change) values. Additionally we wanted to define the specialization-by-result-type types used on O&M 2.0 (possible amended with the SWE results as mentioned by @KathiSchleidt above) as a drop-in substitution for the generic code list for people that are happy with them.

Do you see any issues with defining an ```AbstractObservationTypeCodeListValue``` class and a ```SpecializationByResultTypeCodeListValue``` sub-class for solving this on the conceptual level? The ```AbstractObservationBase.observationType``` attribute would them be of type ```AbstractObservationTypeCodeListValue```.

See https://github.com/opengeospatial/om-swg/blob/master/iso_19156_issues/ea/2020-04-28_Observation.png

**Comment by KathiSchleidt** [comment]
Agreed, awaiting final decision
