### ISSUE TITLE
Multiple Categorization Types?

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#48]
Pertaining to soft typing of observations we're running into the requirement for multiple categorization types on an Observation.
Background is the question of why are observations only specialized by result type, not by the other observation associations, a recent customer request pertained to specializing observations by FoI type, a further use case could pertain to observable properties (singular or grouped) being observed.
Is there some good practice for this type of multiple typing?
related to #47 Soft Typing

**Comment by dr-shorthair** [comment]
Multiple types fine by me. Class intersection.

**Comment by sgrellet** [comment]
So a hint of websem rationale in our UML model. fine with me. would then make sense to keep our AbstractObservation:type attribute named type to refer to rdfs:type property

**Comment by KathiSchleidt** [comment]
Is the Observation Type really the same as being referred to by the rdf:type property?
Just checking as not that knowledgeable of the RDF details, if it does would be perfect :)

**Comment by dr-shorthair** [comment]
RDFS semantics implies that individuals whose `rdf:type` are related to other resources `hrough `rdfs:subClassOf` axiomns are also members of those super-classes. And resources which can be the object of `rdf:type` properties can also be the object of `rdfs:domain` and `rdfs:range` axioms. So in those senses it is a special type. But in general `rdf:type` is just another property.

**Comment by KathiSchleidt** [comment]
Agreed that multiple (Non-conflicting) categories are useful both on Observations and collections
