### ISSUE TITLE
Generic please update

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#5]
Revise to include technical revisions based on implementation experiences.
Often mentions "resolution 802   from the 43 rd ISO/TC 211 plenary meeting in Redlands"

Source: TC211 Comments CN002, ES005, JP006, NZ007, NO008, SE012, US013

**Comment by KathiSchleidt** [comment]
As no further detail has been provided, I propose interpreting including "technical revisions based on implementation experiences" as exactly what we're doing on working on the details of observation relations as well as modelling
No other actions required

**Comment by ilkkarinne** [comment]
Agreed to close in 18th Dec SWG meeting
