### ISSUE TITLE
O&M 2.0 Early Implementors invited to test & certify their software

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/om-swg#53]
Revision 0.4 of the O&M 2.0 executable test suite is now available on the [Beta TEAM Engine validator](https://cite.opengeospatial.org/te2/).

As stated in Section 5.5 of the OGC Compliance policy ([OGC 08-134r10](https://portal.opengeospatial.org/files/?artifact_id=55234)), “[The] first three implementations (can be reference implementations or not) to pass 100% of the compliance procedure, while the test is in beta, will have their Trademark License Fee waived through the annual licensing period for the product”.

You are invited to submit your implementations of O&M 2.0 for testing and certification. 

Once you have tested your implementation, go to the  [OGC online certification system](http://www.opengeospatial.org/resource/products/registration) to provide information about your product.

If you encounter any problems, please let us know at compliance@opengeospatial.org

Please keep this issue open until 2020-10-29, unless if three early implementors are found sooner.

**Comment by cportele** [comment]
@ghobona - I think that calling it the "O&M 2.0" ETS is misleading. O&M is a conceptual model and is not what is being tested. The ETS probably tests XML documents against the OMXML 2.0 standard?  Maybe rename the ETS to "OMXML 2.0"?

**Comment by dr-shorthair** [comment]
Indeed - I did a double-take as well ;-)

**Comment by ghobona** [comment]
@cportele Thanks for the feedback. I have just updated the title of the ETS repo and will update the announcements that are due to go out later on today.

**Comment by ghobona** [comment]
A reminder that we are still looking for early implementers of O&M XML 2.0.

Let us know if you are interested in getting your product certified as OGC Compliant to O&M XML 2.0.

**Comment by ghobona** [comment]
[OpenSensorHub](http://www.opensensorhub.org/) by GeoRobotix, Inc. has been certified as [OGC Compliant](https://www.ogc.org/resource/products/details/?pid=1653) for O&M 2.0 XML.

Two more Early Implementer slots remain. The opportunity to be an Early Implementer closes on 2020-10-29.
