### ISSUE TITLE
Sampling Lumping

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#55]
Trying to grasp lumping
Assumptions:
All preprocessing on samples is done in a previous sampling step; this also pertains to subsamples
Based on this, lumping can be done by one Sampling with one Procedure pertaining to all FoIs being sampled.
The Ultimate FoI should be the same for all samples

Alternative: in some processes, the lumping process also includes subsampling of the individual FoIs. Unclear if this should be lumped together, or modeled explicitly.

**Comment by sgrellet** [comment]
To me if, in the living system we try to describe, it depends whether this yet-an-extra-subsampling-before-mixing is transiant or can be saved for further reuse.
- If transiant, I would say that the fact that their is an extra-sampling before lumping will be described in the Procedure
- If not, I think this would be previous sampling steps
