### ISSUE TITLE
Maintain spatial sampling types?

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#56]
In O&M V2 there are 4 requirements classes for spatial sampling types as follows:

- samplingPoint
- samplingCurve
- samplingSurface
- samplingSolid

Do we wish to retain these as requirements classes, to enable SW to claim conformance to specific spatial sampling objects, or change this to soft typing in line with where we've taken Observation?

**Comment by dr-shorthair** [comment]
I suspect that these topological types are more useful than the result-type types that we had on the Observations side. 
These sampling strategies lend themselves to some common processing and visualization patterns, across application domains. 
This suite of types came out of met-ocean but also make sense in solid-earth and environmental applications.

**Comment by ilkkarinne** [comment]
The classification of the Samples was implemented using soft-typing based on the ```sampleType``` attribute.
The geometry-based classification codelist for SpatialSamples ```SampleByGeometryType``` was earlier moved from the informative Codelist realizations package into the Basic Samples package.

As per the resolution defined in https://github.com/opengeospatial/om-swg/issues/123#issuecomment-857534640 I have now made the following changes in the UML model considering the codelist related constraints:
- Abstract Sample core: AbstractSample: 
   - added a new constraint "property values shall comply with the constraints defined in the class of the sampleType attribute value"
   - added a new constraint "values of this codelist shall only be used for classifying SpatialSamples"
- Basic Samples: SampleByGeometryType: added a new constraint "/req/sam-basic/SampleByGeometryType-con" with the following note:

> The following constraints shall be applied to the value of the shape attribute of the SpatialSample based on the codelist value used: 
> * If value "point" is used, the value of the shape shall be of type Point.
> * If value "curve" is used, the value of the shape shall be of type Curve.
> * If value "surface" is used, the value of the shape shall be of type Surface.
> * If value "solid" is used, the value of the shape shall be of type Solid.

If the text above seems ok, I can copy it as the value of the new requirement ```/req/sam-basic/SampleByGeometryType-con``` in the specification

**Comment by KathiSchleidt** [comment]
Add note on source of sampling geometries (19107)
