### ISSUE TITLE
Packaging of Observation

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#58]
@ilkkarinne 
why is Observation and Observation collection concrete in core while all other classes are abstract?

**Comment by ilkkarinne** [comment]
The idea was that the systems compliant with the core only would need to use the same concrete Observation class (or a sub-class of it), but would likely want to use their own concrete classes to the other components (process, observed property and observer). Thus the core only provides the latter ones as abstract extension points.

Regarding the ObservationCollection, I don't think we need an abstract class at all.

But this is really part of a bigger question of which classes to put in which package and how should these packages relate to the requirements classes (see #25 and #29).
