### ISSUE TITLE
Revise references to updated ISO

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#6]
Since 19101, 19103, 19109, 19115 have been updated it might be necessary to update this standard as well, due the importance of the updated standards. 
Request #82 in the StandardsTracker, see http://isotc211.standardstracker.org/show_request.cgi?id=82

Details:

> 4.1   application schema - Change reference to ISO 19101-1:2014     
> 4.6 feature - Change reference to ISO 19101-1:2014     
> 4.8 measurand - Change reference from 'ISO 19138:2006' (which has been   retired) to 'International Vocabulary of Basic and General Terms in Metrology   (VIM)'.

Source: TC211 Comments DK003, NZ007, PMG014, PMG015, PMG016

**Comment by KathiSchleidt** [comment]
Same as http://isotc211.standardstracker.org/show_request.cgi?id=82

**Comment by KathiSchleidt** [comment]
I will collect all issues pertaining to updates of other ISO standards in this one

Adding #10  ISO 19103 Reference
> The content of these clauses can be substituted with a reference to ISO 19103
> Pertains to clause 05.02+5.03: Delete the clause and insert a reference to ISO 19103 at the appropriate place.
> Source: TC211 Comments DK018

Adding #13 Coverage Dependency Alignment

> From PMG report in Maribor (N5116)
> - ISO 19123-1 (coverage geometry)
>   - Widely referenced in ISO and IHO standards, currently being revised, revision of 19156 depends on ISO 19123-1 revision
> - ISO 19123-2 (coverage impl spec) – Revise this standard following ISO 19123-1 and include annex that shows differences
> - PMG, JAG, WG6, WG9, HMMG to prepare dependency matrix and plan for coordination of revisions, to be presented at next PMG meeting.
> Source: http://isotc211.standardstracker.org/show_request.cgi?id=153

**Comment by KathiSchleidt** [comment]
How do we deal with the fact that ISO 19123 seems to be between versions? 19123:2005 now under review, to be replaced by ISO/WD 19123-1 (still under development)
ISO 19123-2:2018 Geographic information — Schema for coverage geometry and functions — Part 2: Coverage implementation schema is available, but not referenced

**Comment by KathiSchleidt** [comment]
Do we need to update DQ_Element from 19115 (with references to ISO 19114:2003 and ISO/TS 19138:2006) to 19157?

**Comment by KathiSchleidt** [comment]
Types from the following standards are references, thus the newest versions of these standards must be sighted in order to assure that data and feature types being referenced are still available in these versions. Pertains to:
ISO 19107:2003
ISO 19108:2002
ISO 19109:2005
ISO 19111:2003
ISO 19115:2003
ISO 19123:2005

**Comment by ilkkarinne** [comment]
Additionally from an email from Knut Jetlund:
ISO/TS 19103:2005 -> ISO 19103:2015

**Comment by ilkkarinne** [comment]
I will as Mats if he could provide copies for the ISO 19156 project team to use for this task

**Comment by ilkkarinne** [comment]
The information I got from Mats is that the national standardisation bodies should be the right place for requesting copies of ISO standards for the review work. ISO secretary is unable to provide copies to be circulated even among the ISO 19156 project team.
