### ISSUE TITLE
Sampling - remove samplingMethod and processingDetails

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#61]
Based on the discussions on existing curration and archival standard, we've gained the impression that the provision of information on samplingMethod and processingDetails on SF_Specimen via SF_Process my hurt more than it helps

Proposal: reduce both to type ANY to allow for linking to ProvO (or other provenance/lineage resources), alternatively 19115 (also contains lineage descriptions)

Does this cause problems to existing implementations (probably not, as not much there), does anybody have issues if we drop this?

**Comment by ilkkarinne** [comment]
Based on the SWG discussion on 9th September the UML model for the package Abstract sample core was changed regarding the association between the ```AbstractSample``` and the ```Procedure```.

The association was previously defined with a single-directed association from  ```AbstractSample``` to ```Procedure``` (role ```preparationStep```) with cardinality 0..* having an association class ```ProcessingDetails```.

After the change the association class was changed into an individual feature type class ```AbstractPreparationStep``` to which the ```AbstractSample``` has a single-directed 0..* composite association with role ```preparationStep```. The ```AbstractPreparationStep``` class has a single-directed 0..* association to the ```Procedure``` interface with role ```processingDetails```. This new construct allows for defining zero or more preparation steps for a sample, each with zero or more procedure links. This is semantically backwards compatible with the O&M v2.0 SF_Specimen.processingDetails (with it's PreparationStep association class), but allows for zero or more than one procedure to be linked into a single preparation step.
