### ISSUE TITLE
Package Sprinkles

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#68]
What do we call the package where we provide basic concrete featureTypes for simple instantiation & deployment?
Currently this package is named Basic, but we're not really happy with this. Further proposals include:
- Toolbox
- Modules
- Blocks
- Lego ;)

Please think about this, alternatively I WILL find a way to force the name "**Sprinkles**" ;)

**Comment by jetgeo** [comment]
"Basic FeatureTypes". As simple as that. Or you could use "Sprinkles" as a test for the ballot, to see how well people are studying the model ;).
