### ISSUE TITLE
Keep Examples

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#7]
There are several examples in this text we strongly encourage that they are maintained after an update of the standard. The examples increase the understanding of the text to an extent that cannot be overestimated

Source: TC211 Comments DK004

**Comment by KathiSchleidt** [comment]
Once the modifications have been finalized, the examples shall be checked to assure still aligned, if required updated.
No further decisions required

**Comment by ilkkarinne** [comment]
Agreed to close in 18th Dec SWG meeting
