### ISSUE TITLE
Adding positionalAccuracy to SpatialSample

### ISSUE THREAD

**Issue by sgrellet** [opengeospatial/om-swg#74]
Missing 10.2.1.2 positionalAccuracy fom OM:V2

**Comment by ilkkarinne** [comment]
In v2.0 SF_SpatialSamplingFeature this attribute is of type DQ_PositionalAccuracy [0..2] from ISO 19157

It was proposed in the SWG meeting today to change this attribute into an association pointing to Any of ISO 19103 to align with the similar change for the resultQuality in the Abstract observation core package.

The cardinality of 0..2 is for allowing both vertical and horizontal accuracy to be given. What would be the most appropriate cardinality if we change the type to Any?

**Comment by sgrellet** [comment]
+1 on 19157
on the cardinality. What do you think of pointing twice from SpatialSample  to Any (thinking association instead of attribute) and deal with vertical/horizontal with the association role name ?

**Comment by ilkkarinne** [comment]
@sgrellet I agree, separate properties would probably work best. Would definitely like to use attribute instead of association, but that probably needs to be consistent with the other Any uses we have, especially the metadata
