### ISSUE TITLE
Cardinality of the Observation.observer?

### ISSUE THREAD

**Issue by ilkkarinne** [opengeospatial/om-swg#78]
Should we allow for situations where there may be more than one Observer associated with a single Observation?

The use cases I have in mind are long timeseries implemented as single Observation instances, with the sensor equipment changed during the series. If there may be more than one Observer for one Observation, we could tackle the changed sensor case by having two sensors (Observer) associated with the timeseries Observation, each with a Deployment linking it to the observation station (Platform) for the time periods those sensors produced data for the particular station.

There may also be some edge cases where a single Observation is produced as a combination of tow or more Observers working simultaneously, but I have no concrete examples of use cases like this.

**Comment by KathiSchleidt** [comment]
Yes, please leave all cardinalities open!
As you state, could be multiple generations of observers on long time series, alternatively, some measurements may just require a third hand in lieu of having some sort of grasping tail ;)
