### ISSUE TITLE
Associations with roles and roles?

### ISSUE THREAD

**Issue by hylkevds** [opengeospatial/om-swg#79]
Every were else in the document we have either:
> If a reference to an X is provided, the association with the role Y SHALL be used.

or

> The reference(s) to X SHALL be provided using the association [Domain|Range] with the role Z.

Then suddenly there is:

> If a reference to a related Host (/req/obs-cpt/Host) is provided, the relatedHost association SHALL be used. The role attribute of this association can be used to provide further information as to the nature of the relation.

The "role" in this case is not the same as the "role" in the previous cases, and the "role" from the previous cases has disappeared.

My suggestion to make the start of the sentence the same as everywhere else, and rename that second "role" concept to "context":

> If a reference to a related Host (/req/obs-cpt/Host) is provided, the association with the role relatedHost SHALL be used. The context attribute of this association can be used to provide further information as to the nature of the relation.

**Comment by sgrellet** [comment]
+1 on context

**Comment by ilkkarinne** [comment]
Decided with @KathiSchleidt, @sgrellet and @hylkevds to rename the "role" qualifier to "context" in relatedObservation, relatedHost, relatedSampling, relatedSample, relatedCollection
