### ISSUE TITLE
Linked Data/Semantic Web 

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#8]
The revision should also prepare the standard for use in Linked Data/Semantic Web implementations.

Source: TC211 Comments NZ007

**Comment by KathiSchleidt** [comment]
Foundation for semantic extension has been laid, extensions come with serialization

**Comment by rob-metalinkage** [comment]
Just a quick note - there are a lot of options for serialisation, and the interplay of models, profiles, JSON schemas , JSON-LD framing and JSON-LD contexts is not obvious. Am testing ideas out but will require deeper testing by a wide community to settle on interoperable approaches and create guidance documents or formalised implementation profiles for serialisation patterns.
