### ISSUE TITLE
URI vs URL

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#81]
How do we provide an attribute that should provide an (ideally) resolvable link to an external resource?
URL is not available, URI is too abstract
HELP

**Comment by KathiSchleidt** [comment]
Is GML ReferenceType the way to go, or should this point to a codelist?

**Comment by sgrellet** [comment]
hint : we don't chase Identity here just typing a property to carry a reference to more context on the web (like HTML page)
