### ISSUE TITLE
Codelists: do we provide all our codelists in the spec or not?

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#82]
For collection types we have 2 codelist values referenced by constraints, the other type codelists are currently open, we don't wish to constrain.
Must all codelists referenced in the model be provided in the text
Must we provide values for all codelists, or may we leave these open?

**Comment by dr-shorthair** [comment]
from ISO 19103 a <<codeList>> is open, while a <<enumeration>> is closed.

**Comment by jetgeo** [comment]
Unlike enumerations, codelists are not limited to the provided values. You can also very well provide empty codelists, or codelists that are empty in the model but have a reference to an external source. This last option has been used for INSPIRE and TN-ITS in Europe. 
Not sure if I understand the second sentence, but codelists and codelist values that are described in the model should be provided in the text.

**Comment by akuckartz** [comment]
> from ISO 19103 a <> is open, while a <> is closed.

?!

**Comment by dr-shorthair** [comment]
`<<codeList>>` is open, while a `<<enumeration>>` is closed.

**Comment by heidivanparys** [comment]
FYI: CityGML has also had a discussion regarding code lists, see https://github.com/opengeospatial/CityGML-3.0CM/issues/10

**Comment by ilkkarinne** [comment]
Interesting, thanks for pointing this out @heidivanparys.

I take it that the in CityGML the codelists were defined as classes in the UML model
- with ```<<CodeList>>``` stereotype
- without enumerating codelist values
- with tag ```asDictionary=true```

The codelists (including their values) would be published on the OGC Definitions Server. Were the codelists ever published @heidivanparys, I could not find them with a quick scan of http://defs.opengis.net/?

**Comment by jetgeo** [comment]
@ilkkarinne : Yes, that seems to be the way the codelists are defined in the CityGML Conceptual model (https://github.com/opengeospatial/CityGML-3.0CM/blob/master/Conceptual%20Model/CityGML_3.0_Consolidated_Draft.eap).
The codelists do not seem to be published opengis.net (yet).
