### ISSUE TITLE
The parameter attribute for Sample/Sampling?

### ISSUE THREAD

**Issue by ilkkarinne** [opengeospatial/om-swg#84]
The SF_SamplingFeature of the O&M v2.0 has an attribute ```parameter:NamedValue[0..*]```. In the 19156:2011 UML model it has the following note:

> If present, the attributes parameter:NamedValue shall describe an arbitrary parameter associated with the SF_SamplingFeature. This might be a parameter that qualifies the interaction with the sampled feature, or an environmental parameter associated with the sampling process.

Should we include the ```parameter``` attribute in the ```AbstractSample``` or the ```AbstractSampling``` class?

**Comment by ilkkarinne** [comment]
The parameter is now included in ```AbstractSampling```. Comment if you wish it otherwise.

**Comment by sgrellet** [comment]
AbstractSample is a bare minimum otherwise it's a regression from OM V2

**Comment by KathiSchleidt** [comment]
If present, the attributes parameter:NamedValue shall describe an arbitrary parameter associated with the Sample. This might be a parameter that qualifies the interaction with the sampled feature.

If present, the attributes parameter:NamedValue shall describe an arbitrary parameter associated with the Sampling. This might be an environmental parameter associated with the sampling process.

**Comment by sgrellet** [comment]
for each sentence
- 1st part in the req: SHALL
- 2nd part could be a rec : SHOULD (otherwise we restrict the reuse of this useful property)

**Comment by KathiSchleidt** [comment]
If present, the attributes parameter:NamedValue SHALL describe an arbitrary parameter associated with the Sample. This MAY be a parameter that qualifies the interaction with the sampled feature.

If present, the attributes parameter:NamedValue SHALL describe an arbitrary parameter associated with the Sampling. This MAY be an environmental parameter associated with the sampling process.

**Comment by sgrellet** [comment]
agreed to have each 2nd sentence under the requirement

**Comment by KathiSchleidt** [comment]
req: If present, the attributes parameter:NamedValue SHALL describe an arbitrary parameter associated with the Sample. 
EXAMPLE This MAY be a parameter that qualifies the interaction with the sampled feature.

req: If present, the attributes parameter:NamedValue SHALL describe an arbitrary parameter associated with the Sampling. 
EXAMPLE This MAY be an environmental parameter associated with the sampling process.

**Comment by dr-shorthair** [comment]
Don't forget: this is just a generic extension point. There may be better ways to implement it in specific platforms - e.g. RDF OWA.
