### ISSUE TITLE
ISO def reference for feature type

### ISSUE THREAD

**Issue by sgrellet** [opengeospatial/om-swg#85]
Working on section 4 'Terms and definitions'
in 19156:2011 we had "feature type "class of features having common characteristics"

19101:2014 defines: feature, feature catalogue, feature instance, ...
but point to to 19156:2011 for feature type ... which is surprizing

do we keep with the 'hot fix' from 2011 or is that defined somewhere else ?

**Comment by ReesePlews** [comment]
@sgrellet, thank you for writing about the terminology entries in 19156. 

in the 19101:2002 edition, "feature type" was not defined. later 19156 defined "feature type" and 19156 became the authoritative source reference for that term. when 19101 was revised and became 19101-1:2014 it used "feature type" and that is why the source reference points back to 19156:2011.  i agree this is not so ideal but the status and reference is correct. 

i dont understand what you mean by "hot fix". you are now revising 19156 and you could change that terminology entry (definition) if truly needed but it is important to note that other standards which are not in the update process will still use the old definition. if you do change it i will (should!) catch it and ask why it  is being changed.  there needs to be a very solid reason for revision of these core terminology entries.  it would be good to see the terminology clause (3) before the 19156 document goes to CD.  i spoke to @ilkkarinne by dm recently about 19156 terminology.

also of note, 19101-1 will be revised, and it would be possible to make revisions to those terms also. that work schedule will follow your project, as it is going to start in the coming month. if the experts in both PTs determine the entries should be changed then these proposals will be discussed and some synchronization made.

let me know if you have any other terminology questions. always happy to help if i can.   thank you,

reese plews
convenor, terminology maintenance group (TMG)
iso/tc 211
https://github.com/ISO-TC211/TMG

**Comment by sgrellet** [comment]
@ReesePlews  : the idea is not to review the definition of the term "Feature Type" but to better understand which standard is to host the definition of "Feature Type".
What I meant by 'hot fix' was to express the group feeling that it was highly important, thus added, when 19156:2011 was made but, that it seems to us that it should be hosted 'higher-up' in the 191xx series of standards.

**Comment by cportele** [comment]
The standard that specifies features in ISO 191xx is ISO 19109 (19101-1 introduces the concept and 19109 has the details). 19109 uses "feature type" a lot (and defines a metaclass with that name), but does not define "feature type" as a term, because the term "feature" was considered sufficient as the note to the definition states: "A feature can occur as a type or an instance. Feature type or feature instance should be used when only one is meant."

If 19109 does not need a definition of feature type, does 19156 need one?
