### ISSUE TITLE
Reading Guide

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#88]
MB/NC: NO-001-001
Line number: 
Clause/Subclause: 
Paragraph/Figure/Table: 
Type of comment: Ge
Comments: The document is quite difficult to read.
Proposed change: Add in the instruction that a reader should start reading clause 7 first.

KS: Unclear where we can make this reference as the intro is ISO template

------------------------------------------

MB/NC: DK-019-037
Clause/Subclause: 7
Paragraph/Figure/Table: 
Type of comment: Te
Comments: It is hard to understand what the key concepts are and how they relate to each other. This makes it hard for a potential user to determine whether or not this standard is relevant and useful for him/her.Figure D.2 has some minimal information but contains only roles, whereas verbs are required when relating concepts to each other.Description of  the concepts is mixed with a description of the data model.
Proposed change: Clarify what the key concepts are. Do this by means of (1) a set of diagrams that explain the relations between the key concepts (using verbs! and roles where needed). E.g. like the diagram below. Adjust the text where needed, so the diagram and the accompanying text are synchronized. Add the key concepts to the “Terms and definitions”. Make sure that the standard clearly states what diagrams are illustations of concepts and what diagrams are a view on the data model.

![UML with verby Associations](https://raw.githubusercontent.com/opengeospatial/om-swg/master/iso_19156_issues/Diagrams/DK-019.png)

------------------------------------------

**MB/NC**: DK-021
**Clause/Subclause:** 7.1.2
**Paragraph/Figure/Table:** Para 2
**Type of comment:** Te/ed
**Comments:** The content of   this paragraph seems to a little too much a textbook. So why include this text   in the document?
**Proposed change:** Consider the need   for this text.

------------------------------------------

**MB/NC:** AU04-020
**Clause/Subclause:** 7.1.2 
**Paragraph/Figure/Table:** 1
**Type of comment:** Te 
**Comments:** “It involves application of a specified   procedure, such as a sensor, instrument, algorithm or process chain. The   procedure may be applied in-situ, remotely, or exsitu with respect to the   sampling location.” Reflects conflation of ‘procedure’ and ‘sensor’ from the   previous version. 
**Proposed change:** With the clarification and separation of ‘Observer’   from ‘Procedure’ the text should be updated to match

**Comment by KathiSchleidt** [comment]
NO-001 add a note in the introduction pointing to section 7 and the annexes

**Comment by KathiSchleidt** [comment]
DK-019: create a trivial UML structure for 7.1 in ppt for overview, use material from flyer

**Comment by KathiSchleidt** [comment]
DK-019: related to https://github.com/opengeospatial/om-swg/issues/108 on using verbs for roles

**Comment by KathiSchleidt** [comment]
DK-021 text was from previous version, and is essential for understanding the similarity between observations and measurements

**Comment by KathiSchleidt** [comment]
AU04-020: agreed, should be sorted across document

**Comment by sgrellet** [comment]
DK-021 : we used a lot these texts coming from previous version to introduce people to O&M over the last decade. They proved useful. We deem important to keep them.

**Comment by KathiSchleidt** [comment]
We will revisit Clause 7 and see how this can be made more readable.
