### ISSUE TITLE
Format Issue

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#9]
In the   second line in the note the text does not have the same amount of indent as in the first line of the note

Adjust   the indent so both lines have an equal indent.     

KS: I investigated both the Word and PDF versions of the document and   couldn't find this error. There is a different indent between Example and Note, but this should be maintained

Source: TC211 Comments DK017

**Comment by KathiSchleidt** [comment]
Cannot find, new document must be newly formatted in any case
No further action required

**Comment by ilkkarinne** [comment]
Agreed to close in 18th Dec SWG meeting
