### ISSUE TITLE
Check/Explain Capitalization

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#90]
MB/NC: DK-003-003
Line number: 
Clause/Subclause: 
Paragraph/Figure/Table: 
Type of comment: Ge 
Comments: When reading the text it become apparent that some words are spelled with capital letters even if the word is not in the beginning of a sentence (e.g. second word in clause 7.2.1).
Proposed change: Evaluate the standard and the use of capital letters in the middle of sentences.

**Comment by ilkkarinne** [comment]
Capitalization rules we want to use:

UML classes: Capitals
UML associations: lowerCameCase
Terms that appear in the Terms and definitions: currently in lower case

featureOfInterest or feature-of-interest? consistency?

**Comment by sgrellet** [comment]
I may sound to 'dogmatic' and only use the class/property name as defined in the model all the way through the document.
I have seem too many discussions where people enter aspects like: "ok, but look, in that chapter the word is written differently because this one here refers to the 'layman view on topic xyz'"

**Comment by KathiSchleidt** [comment]
related to #96

**Comment by KathiSchleidt** [comment]
The prose is divergent on capitalization, at times follows proper english, at times capitalizes concepts from the standard.
Still being analysed, if we find an easy way forward, we will follow, alternatively all capitalized class names will be taken down to lower case when not referring to the class itself

**Comment by KathiSchleidt** [comment]
Take down to lower case in Clause 7, use Christine Perrry's correction document (check if necessary to refer to explicit classes, if so capitalize, but clearer if not necessary)
In later clauses, depends on if referring to the class - classes in correct camelCase, others normal prose

**Comment by sgrellet** [comment]
Awaiting Carl's Reed review
