### ISSUE TITLE
Relation to ISO 19105

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#92]
MB/NC: DK-005-005
Line number: 
Clause/Subclause: 
Paragraph/Figure/Table: 
Type of comment: Ge 
Comments: When reading this standard there seems to be an unspoken relation to ISO 19105, but this standard are not referenced anywhere in this document.
Proposed change: Consider the inclusion of ISO 19105 as part of the normative referenced document in this standard.

Note: ISO 19105:2000 Geographic information — Conformance and testing

**Comment by KathiSchleidt** [comment]
Also

MB/NC: NO-008-009
Line number: 
Clause/Subclause: 2 
Paragraph/Figure/Table: 
Type of comment: Te 
Comments: ISO 19105 is not stated as a normative reference.
Proposed change: The revision of ISO 19105 is almost complete and could be added as a normative reference, if the conformance classes, requirement classes is in accordance with ISO 19105. If not, state why it is not intended to be applied in ISO 19156

**Comment by cportele** [comment]
ISO 19105 is not a normative reference. ISO 19156 can be used and implemented without knowledge of ISO 19105. The following statement does not apply for ISO 19105: "The following documents are referred to in the text in such a way that some or all of their content constitutes requirements of this document."

ISO 19105 informs the editors and project teams how to write their standards.

If a reference to ISO 19105 is added, it would be added to the bibliography.

**Comment by sgrellet** [comment]
Moved to Implementation cross-checked  as already covered by issue #134 and aready in the dox shared on the GitHub
