### ISSUE TITLE
Minor Typos

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#94]
MB/NC: AU02-006-007
Line number: 
Clause/Subclause: 
Paragraph/Figure/Table: Table 1
Type of comment: ed 
Comments: The identifier “/conf/ cpt-obs /Deployment” has spaces included 
Proposed change: Remove spaces within Identifiers
**KS: Agreed**

---------------------------------------------------------

MB/NC: TMG-017 
Line number: 
Clause/Subclause: 3.5
Paragraph/Figure/Table: domain feature
Type of comment: ed 
Comments: there is a minor typo in the Note 1 to entry, where the word "observation" should be "observations"
Proposed change: The correct Note 1 to entry is: Note 1 to entry: This may be contrasted with observations and sampling features, which are features of types defined for cross-domain purposes.
**KS: Replace "observation and sample features" with "observations and sampling features"** 

------------------------------------------

MB/NC: TMG-023
Line number: 
Clause/Subclause: 3.11
Paragraph/Figure/Table: measurand 
Type of comment: ed 
Comments: the alphabetical location of this entry is not in the correct order
Proposed change: ISO/TC 211 uses alphabetical order for terminology entries, please reorder this entry to the correct alphabetical location.
**KS: measurand goes before measure in definitions**

------------------------------------------

MB/NC: DK-013-031
Clause/Subclause: 5.5
Paragraph/Figure/Table: Table 
Type of comment: Ed 
Comments: This comment is valid for all the tables in this document. Make sure that all the tables have a table no and that there is a link between the text and the tables via the table no.
Proposed change: Assure that all the tables in this document have a number and that all the tables are referenced in the text.
**KS:!!!**
**A few things to sort with table numbering, also the different numbering scheme between OGC and ISO version (not sure where from, OGC sequential, ISO sequential within Clause)**
**- To my view, table captions make sense for the requirements classes (also for the table in 5.5 mentioned here explaining the structure for these)**
**- I would NOT add table captions to each individual requirement despite the fact that we use a table structure to format this**

------------------------------------------

MB/NC: CN-015-033
Clause/Subclause: 6.1
Paragraph/Figure/Table: 
Type of comment: ed 
Comments: According to the ISO/IEC Directives, Part 2 (2018, 22.3.3) “Hanging paragraphs” shall be avoided.
Proposed change: 
**KS:!!!
New heading structure for Clause 6 as follows:
6 Packaging, requirements and dependencies
6.1 Requirements
6.1.1 Requirement and conformance class structure
6.1.2 Requirements class dependency graphs
6.2 UML 
6.2.1 UML package structure
6.2.2 UML package dependencies**

------------------------------------------

MB/NC: CN-016-034
Clause/Subclause: 6.1.1 
Paragraph/Figure/Table: 
Type of comment: ed 
Comments: According to the ISO/IEC Directives, Part 2 (2018, 22.3.2), 6.1.1 shall not be created unless there is at least one further subclause at the same level.
Proposed change: 
**KS: Same as CN-015**

------------------------------------------

MB/NC: CN-017-035
Clause/Subclause: 6.2
Paragraph/Figure/Table: 
Type of comment: ed 
Comments: According to the ISO/IEC Directives, Part 2 (2018, 22.3.3) “Hanging paragraphs” shall be avoided.
Proposed change: 
**KS: Same as CN-015**

------------------------------------------

MB/NC: CN-018-036
Clause/Subclause: 6.2.1 
Paragraph/Figure/Table: 
Type of comment: ed 
Comments: According to the ISO/IEC Directives, Part 2 (2018, 22.3.2), 6.2.1 shall not be created unless there is at least one further subclause at the same level.
Proposed change: 
**KS: Same as CN-015**

------------------------------------------

MB/NC: DK-022-040
Clause/Subclause: 7.1.2
Paragraph/Figure/Table: Para 3
Type of comment: Ed 
Comments: Typo 
Proposed change: Delete “also”.
**KS: !!!
Contested Sentence:
"The observation itself is also a feature, since it has properties and identity."
Use of the word "also" was deliberate to differentiate from the spatial features the observation pertains to**

------------------------------------------

MB/NC: DK-023-041
Clause/Subclause: 7.1.3 
Paragraph/Figure/Table: Para 1
Type of comment: Te 
Comments: We do not understand the last part of this paragraph, starting from “The key idea is that observation…” to the end of the paragraph. 
Proposed change: Reword the mentioned part of the text, so the message become clear for the non-authors.
**KS: The text "properties of the observation" somehow got doubled, makes very confusing. Rest is the same text as V1**

------------------------------------------

MB/NC: DK-026-044
Clause/Subclause: 7.1.6
Paragraph/Figure/Table: Para 2
Type of comment: Te 
Comments: There is a reference to ISO 19115. This raises the question which version (i.e. 19115-1 or 19115-2), given that 19115 is withdrawn.
Proposed change: Insert the right version of 19115 as well as adding the year of publication and if needed adjust clause 2 accordingly.
**KS:
Will be updated to "ISO 19115-1:2014"
Otherwise 19115 not used in a normative context, thus will be cited in the bibliography
see: https://github.com/opengeospatial/om-swg/issues/95** 

------------------------------------------

MB/NC: DK-029-047
Clause/Subclause: 7.2.2.3
Paragraph/Figure/Table: Para 1
Type of comment: Ed 
Comments: Word missing.
Proposed change: Change to “…may be indirect or relying on….”.
**KS: !!!
"The procedure for obtaining values of the property of interest may be _indirect, relying_ on direct observation of a more convenient parameter which is a proxy for the property of interest." 
to my reading, the statement is correct as it stands, the proposed correction changes the meaning ("indirect" & "relying on" both apply). I put this comment down to a limited understanding of English**

------------------------------------------

MB/NC: AU05-031-049
Clause/Subclause: 7.2.5
Paragraph/Figure/Table: 1
Type of comment: Ed 
Comments: ‘observational science’ is not really a special thing. 
Proposed change: Replace with ‘environmental and earth science’.
**KS: 
"A small number of sampling patterns are common across disciplines in observational science."
Replace ‘observational science’ with ‘environmental and earth science’.**

------------------------------------------

MB/NC: DK-033
Clause/Subclause: 7.3.2
Paragraph/Figure/Table: Para 1
Type of comment: Ed 
Comments: Typo, we think.
Proposed change: Change the   following “…shall link the Sample to the feature…” to “…shall link the class to the feature…”
**KS: !!!
General tricky bit, related to Capitalization of defined types 
https://github.com/opengeospatial/om-swg/issues/90**

------------------------------------------

MB/NC: DK-034
Clause/Subclause: 8.1.1. 
Paragraph/Figure/Table: Para 1
Type of comment: Ed 
Comments: There is a   reference to clause 8.1.2. However, clause 8.2 have as headline the text “Observation”   and in the text in clause 8.1.1 para 1 it is stated that the content of   figure 9 is fully described in clause 8.1.2, but from clause 8.2 and onwards   the content of figure 9 is fully described.
Proposed change: Reconsider the reference.
**KS: !!!
to my reading, correct as stands. The table in 8.1.2. contains the entire model, subsequent sections parts, reference pertains to entire model. More to do with not understanding the req structure**

------------------------------------------

MB/NC: AU07-037
Clause/Subclause: 8.6.2
Paragraph/Figure/Table: EXAMPLE 
Type of comment: Te/ed
Comments: Refers to ‘Sensor’ when the   rest of the sub-clause mentions ‘Observer’ 
Proposed change: Replace ‘Sensor’ with ‘Observer’. Add a note that   ‘Sensor’ is a sub-class of ‘Observer’.
**KS: Replace ‘Sensor’ with ‘Observer’. Add a note that   ‘Sensor’ is a sub-class of ‘Observer’.**

------------------------------------------

MB/NC: DK-040
Clause/Subclause: 5,7
Paragraph/Figure/Table: Bullet points
Type of comment: Ed 
Comments: In the bullet   point the following text appears: “/rec/{pkg}/{classM}/{reqN}”. However, if   one compare with the text in the table on the previous side, it seem like a   typo. In the table on the previous side a recommendation shall have the   following layout: “/rec/{pkg}/{classM}/{recO}”. 
Proposed change: Clarify which text   is correct and adjust accordingly.
**KS: 
In 5.7, correct URI pattern for recommendation to
[base URI]/rec/{pkg}/{classM}/{recO}**

------------------------------------------

MB/NC: AU08-045
Clause/Subclause: Bibliography 
Paragraph/Figure/Table: 
Type of comment: ed 
Comments: Incorrect reference for   UCUM
Proposed change: Use https://ucum.org/ucum.html
**KS:
Use https://ucum.org/ucum.html in Bibliography reference**

**Comment by KathiSchleidt** [comment]
DK-013: to tables - the tables referred to are purely a layout for structuring of the requirements, each has a unique reference. Thus will not add table numbers

**Comment by KathiSchleidt** [comment]
DK-022: text is unchanged from the previous version, to our view, it better expresses the nature of observations, illustrating that while complex attribute descriptions, **also** seen as a feature

**Comment by KathiSchleidt** [comment]
DK-029: the statement is correct as it stands, the proposed correction changes the meaning ("indirect" & "relying on" both apply).

**Comment by KathiSchleidt** [comment]
AU05-031: change to across scientific disciplines

**Comment by KathiSchleidt** [comment]
DK-033
…shall link the Sample to the feature
change to
…shall link the Sample **feature** to the feature

**Comment by KathiSchleidt** [comment]
**OGC PART B 2/35**
1. Requirement: table 1, row 1, Identifier = /conf/cpt-obs
2. Implementation Specification Section number: 4.2 Conformance classes related to models including Observations and Measurements
3. Criticality: Editorial
4. Comments for changes: value should be: /conf/obs-cpt
4. Justifications for changes: typo

KS: Pertains to first 2 rows of table "Conceptual Observation schema conformance classes"
in first row cpt-obs is backwards, in the 2nd row it is backwards with blanks, then ok

**Comment by KathiSchleidt** [comment]
**OGC PART B 3/35**
1. Requirement: table 2, row 5, Conformance class = Abstract Observation core - AbstractObservationObservableProperty
2. Implementation Specification Section number: 4.2 Conformance classes related to models including Observations and Measurements
3. Criticality: Editorial
4. Comments for changes: value should be: Abstract Observation core - AbstractObservation
4. Justifications for changes: typo

KS: AbstractObservationObservableProperty - remove ObservableProperty, should only be AbstractObservation

**Comment by KathiSchleidt** [comment]
**OGC PART B 4/35**
1. Requirement: table 5, row 3, Conformance class = Abstract Sample core - AbstractPreparationStepSample - PreparationStep
2. Implementation Specification Section number: 4.2 Conformance classes related to models including Observations and Measurements
3. Criticality: Editorial
4. Comments for changes: value should be: Abstract Sample core - AbstractPreparationStep
4. Justifications for changes: typo

KS: Cut&Paste error, Delete "Sample - PreparationStep" from end of text under conformance class

**Comment by KathiSchleidt** [comment]
**OGC PART B 5/35**
1. Requirement: In the description of the convention right after the /req/{pkg}/ part has been removed to ease reading.
2. Implementation Specification Section number: 5.4 Requierements and recommendations
3. Criticality: Editorial
4. Comments for changes: Something seems to be missing in the sentence.

KS:
Delete Line "In the description of the convention right after the /req/{pkg}/ part has been removed to ease reading." 

2§ below, add base to descriptive text as follows:
The following base **(/req/{pkg}/)** has been used per package:

Below the list, add the following sentence:
In the lines below, the base (/req/{pkg}/) has been left out for better readability.

**Comment by KathiSchleidt** [comment]
**OGC PART B 6/35**
1. Requirement: The URI for each recommendation has the form: http://www.opengis.net/spec/om/3.0/rec/{pkg}/{classM}/{reqN}
2. Implementation Specification Section number: 5.7     Identifiers
3. Criticality: Editorial
4. Comments for changes: the URI should be: http://www.opengis.net/spec/om/3.0/rec/{pkg}/{classM}/{recN}
4. Justifications for changes: typo

KS:sameAs DK-040, typo (q should be c)

**Comment by KathiSchleidt** [comment]
**OGC PART B 7/35**
1. Requirement: Abstract Core: Within [...] (i.e: realizing the interfaces provided by the Conceptual). A consistent [...] provision introduced. [...] for greater flexibility of implementation.
2. Implementation Specification Section number: 6.2     UML package structure
3. Criticality: Editorial
4. Comments for changes: Abstract Core: Within [...] (i.e: realizing the interfaces provided by the Conceptual **Model Packages**). A consistent [...] provision **has been introduced**. [...] for **greater implementation flexibility**.
4. Justifications for changes: a) correct terminology, b) missing words c) conciseness

KS: All accepted

**Comment by KathiSchleidt** [comment]
**OGC PART B 8/35**
1. Requirement: The key idea [...], and the other properties of the observation properties of the observation provide context [...].
2. Implementation Specification Section number: 7.1.3 Properties of an Observation
3. Criticality: Editorial
4. Comments for changes: The key idea [...], and the other properties of the observation provide context [...].
4. Justifications for changes: typo
The key idea [...], and the other properties of the observation properties of the observation provide context [...].
The key idea [...], and the other properties of the observation provide context [...].

KS:sameAs DK - 023

**Comment by KathiSchleidt** [comment]
**OGC PART B 9/35**
1. Requirement: [...], the result will typically be sampled discreetly  [...].
2. Implementation Specification Section number: 7.1.5 Result types
3. Criticality: Editorial
4. Comments for changes: [...], the result will typically be sampled discretely  [...].
4. Justifications for changes: discreetly == prudently, unobtrusively, modestly; discretely == distinctly, noncontinuously.

KS: not sure how this happened, but somehow e & t got switched
change 'discreetly' back to 'discretely'

**Comment by KathiSchleidt** [comment]
**OGC PART B 10/35**
1. Requirement: EXAMPLE 5 [...]. In some cases, the the [...]
2. Implementation Specification Section number: 7.2.2.2              Proximate feature-of-interest embodies a sample design
3. Criticality: Editorial
4. Comments for changes: EXAMPLE 5 [...]. In some cases, the [...]
4. Justifications for changes: typo

KS: remove double "the" in Clause 7.2.2.2, EXAMPLE 5

**Comment by KathiSchleidt** [comment]
**OGC PART B 11/35**
1. Requirement: archivation 
2. Implementation Specification Section number: 7.2.5 Classification of samples
3. Criticality: Editorial
4. Comments for changes: archiving
4. Justifications for changes: correct English

KS: replace archivation with archiving

**Comment by KathiSchleidt** [comment]
**OGC PART B 16/35**
1. Requirement: In this example, Well, Aquifer and FluidBody are modeled outside t [...]
2. Implementation Specification Section number: 7.3.2 Relationship between Sample and domain features
3. Criticality: Editorial
4. Comments for changes: [...] modelled [...]
4. Justifications for changes: typo.

KS: replace modeled with modelled

**Comment by KathiSchleidt** [comment]
**OGC PART B 20/35**
1. Requirement: NOTE Attention should be given not to reinvent semantic that is explicitly modeled in the O&M model.
2. Implementation Specification Section number: 9.1.2 Association metadata
3. Criticality: Editorial
4. Comments for changes: [...] modelled [...]
4. Justifications for changes: typo.

KS: replace modeled with modelled

**Comment by KathiSchleidt** [comment]
**OGC PART B 25/35**
1. Requirement: If collectionType is specified homogenousObservationCollection as [...]
2. Implementation Specification Section number: 10.4.3 Attribute collectionType
3. Criticality: Editorial
4. Comments for changes: [...] as homogenousObservationCollection [...]
4. Justifications for changes: typo.

KS: Move "as" to before "homogenousObservationCollection"

**Comment by KathiSchleidt** [comment]
**OGC PART B 26/35**
1. Requirement: Code lists has the following [...]
2. Implementation Specification Section number: 10.12.1 CollectionTypeByMemberCharacteristicsSemantics
3. Criticality: Editorial
4. Comments for changes: Code list [...]
4. Justifications for changes: typo.

KS: replace "Code lists has" with "The code list CollectionTypeByMemberCharacteristicsSemantics has"

**Comment by KathiSchleidt** [comment]
**OGC PART B 30/35**
1. Requirement: NOTE Sample are frequently [...]. EXAMPLE [...]; material sample are usually [...]
2. Implementation Specification Section number: 11.2.6 Association relatedSample
3. Criticality: Editorial
4. Comments for changes: NOTE Samples are frequently [...]. EXAMPLE [...]; material samples are usually [...]
4. Justifications for changes: Singular/plural.

KS: make Sample plural

**Comment by KathiSchleidt** [comment]
**OGC PART B 34/35**
1. Requirement: 19156:2011:SF_Specimen.currenLocation
2. Implementation Specification Section number: C.2 Sample Model
3. Criticality: Editorial
4. Comments for changes: 19156:2011:SF_Specimen.currentLocation
4. Justifications for changes: typo.

KS: agreed, add t

**Comment by KathiSchleidt** [comment]
MB/NC: DK-033 - need to rework 7.3.2	Relationship between Sample and domain features, currently reads like the sample feature is created to do the observation, need proper split between physical sample and representation

**Comment by KathiSchleidt** [comment]
MB/NC: AU07-037
While I have a statement to "Add a note that ‘Sensor’ is a sub-class of ‘Observer’.", we don't have a sub-class Sensor, thus don't see a need for this note. There is a note that "Observer is an instance of a sensor, instrument, ..." already

**Comment by KathiSchleidt** [comment]
Done!

**Comment by sgrellet** [comment]
Awaiting Carl's Reed review
