### ISSUE TITLE
Relation to ISO 19111

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#95]
MB/NC: NO-007-008
Line number: 
Clause/Subclause: 2
Paragraph/Figure/Table: 
Type of comment: Te 
Comments: ISO 19111 is a normative reference, but there are no dependency on any requirement in ISO 19111. 
Proposed change: Check if ISO 19111 really is a normative reference. Check also the other normative references

**Comment by cportele** [comment]
I will address this issue.

**Comment by KathiSchleidt** [comment]
Done my best to align, but run into some serious formatting issues, see #134

**Comment by sgrellet** [comment]
- Clause 2 checked -> ok
- the rest is already covered by issue #134
Bumping this to cross-checked
