### ISSUE TITLE
Corrections on Definitions

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#97]
MB/NC: TMG-015
Clause/Subclause: 3.2
Paragraph/Figure/Table: coverage 
Type of comment: ed 
Comments: the format of the source reference will need to be changed if there were changes in 19123-1
Proposed change: please confirm this entry in 19123-1 prior to the next project stage;

------------------------------------------

MB/NC: TMG-016
Clause/Subclause: 3.4
Paragraph/Figure/Table: domain 
Type of comment: ed 
Comments: the authoritative source reference is lacking the terminology entry number; the draft note does not match the note of the authoritative source reference
Proposed change: use the note to entry from the authoritative source reference; if the PT wishes to keep the revised note, the source reference needs to be corrected, as shown below: [SOURCE: ISO 19109:2015, 4.8, modified —  The original Note 1 to entry has been removed and a new Note 1 to entry has been added.

------------------------------------------

MB/NC: TMG-018
Clause/Subclause: 3.6
Paragraph/Figure/Table: ex-situ
Type of comment: 
Comments: the definition is slightly different at the end adding "off-site" which is not in the authoritative source entry; consider revision to match or keep as new definition
Proposed change: consider using the following modification:3.6ex-situoff sitereferring to the study, maintenance or conservation of a specimen or population away from its natural surroundingsNote 1 to entry: Opposite of in-situ (on site).

------------------------------------------

MB/NC: TMG-019
Clause/Subclause: 3.7
Paragraph/Figure/Table: feature 
Type of comment: ed 
Comments: the Note 1 to entry is different than the Note 1 to entry of the authoritative source;
Proposed change: revise the terminology entry as follows:
```
3.7
**feature**
abstraction of real-world phenomena
Note 1 to entry: A feature may occur as a type or an instance. In this document, feature instance is meant unless otherwise specified.
[ISO 19101-1:2014, definition 4.1.11, modified —  Note 1 to entry has been modified.]
```

------------------------------------------

MB/NC: TMG-020
Clause/Subclause: 3.9
Paragraph/Figure/Table: measure 
Type of comment: ed 
Comments: the domain <GML> is missing from the definition; ISO 19136-1 assigns the domain <GML> to this definition; the Note 1 to entry (from 19136-1) is missing; the authoritative source reference should be ISO 19136-1:2020 3.1.41 
Proposed change: if the candidate entry is not specific to GML then either the definition should be modified, and/or a new domain should be used, or the note to entry should be modified; aligning with the terminology entry defined by the source reference, the corrected terminology entry should be:
```
**3.1.41**
**measure**
<GML> value described using a numeric amount with a scale or using a scalar reference system
Note 1 to entry: When used as a noun, measure is a synonym for physical quantity.
[SOURCE: ISO 19136-1:2020 3.1.41]
```

------------------------------------------

MB/NC: TMG-021
Clause/Subclause: 3.10
Paragraph/Figure/Table: measurement 
Type of comment: ed 
Comments: the authoritative source is incorrect; the authoritative source reference is: ISO 19101-2:2018, 3.21; ISO 19101-2:2018 references the VIM as the source for the entry; the revision of ISO 19101-2 change from TS to IS
Proposed change: the authoritative source reference is: [SOURCE: ISO 19101-2:2018, 3.21]

------------------------------------------

MB/NC: TMG-022
Clause/Subclause: 3.11
Paragraph/Figure/Table: measurand 
Type of comment: ed 
Comments: the draft definition is different from the authoritative source definition which is the first edition of this standard  (IS0 19156:2011);the term is only used 1 time in the document (outside of clause 3) in Table B.2; ISO/CS may require the term be used in the body of the document – please consider this;
Proposed change: use the original definition from ISO 19156:2011; ISO 19136-1:2020 also contains this terminology entry but with the note removed and a different source; if you want to use the VIM as the source reference, consider this option: [SOURCE: VIM3:2012, 2.3]

------------------------------------------

MB/NC: TMG-024
Clause/Subclause: 3.12
Paragraph/Figure/Table: property 
Type of comment: ed 
Comments: the definition here and also from ISO 19156:2011 modified the source entry by adding a note which was not indicated correctly in the source reference
Proposed change: please use the following source reference:
`[SOURCE: ISO 19143:2010, 4.21, modified — Example has been added to the entry.]
`

------------------------------------------

MB/NC: TMG-024
Clause/Subclause: 3.12
Paragraph/Figure/Table: property 
Type of comment: ed 
Comments: the definition here and also from ISO 19156:2011 modified the source entry by adding a note which was not indicated correctly in the source reference
Proposed change: please use the following source reference:
`[SOURCE: ISO 19143:2010, 4.21, modified — Example has been added to the entry.]
`

------------------------------------------

MB/NC: TMG-025
Clause/Subclause: 3.13
Paragraph/Figure/Table: property type
Type of comment: ed 
Comments: The example should appear before the Notes to entry
Proposed change: Move the Example after the definition

------------------------------------------

MB/NC: TMG-026
Clause/Subclause: 3.14
Paragraph/Figure/Table: range 
Type of comment: ed 
Comments: the domain <coverage> is missing from the definition; check the definition in the reference source
Proposed change: please add the domain <coverage>;please confirm this entry in 19123-1 prior to the next project stage;

------------------------------------------

MB/NC: TMG-027
Clause/Subclause: 3.15
Paragraph/Figure/Table: value 
Type of comment: ed 
Comments: check the source reference;it appears that Notes to entry have been added;
Proposed change: 
```
**3.15**
**value**
element of a type domain
Note 1 to entry: A value considers a possible state of an object within a class or type (domain).
Note 2 to entry: A data value is an instance of a datatype, a value without identity.
Note 3 to entry: A value can use one of a variety of scales including nominal, ordinal, ratio and interval, spatial and temporal. Primitive datatypes can be combined to form aggregate datatypes with aggregate values, including vectors, tensors and images.
[SOURCE: ISO/IEC 19501:2005, 0000_5, modified — Notes to entry have been added.]

```

------------------------------------------

MB/NC: TMG-028
Clause/Subclause: 3.16
Paragraph/Figure/Table: requirement 
Type of comment: ed 
Comments: check the source reference of the entry;
Proposed change: while it is possible to use the ISO/IEC directives as the source, other more suitable terminology entries exist; check the OBP for alternatives

------------------------------------------

MB/NC: TMG-029
Clause/Subclause: 3.17
Paragraph/Figure/Table: recommendation 
Type of comment: ed 
Comments: check the source reference of the entry;
Proposed change: while it is possible to use the ISO/IEC directives as the source, other more suitable terminology entries exist; check the OBP for alternatives

**Comment by KathiSchleidt** [comment]
Cross check with GeoLexica

**Comment by KathiSchleidt** [comment]
In order to add additional notes to definitions, is it valid to provide these after the reference to the source.
If not, how can we add additional notes to make our definitions more precise than the original source?

**Comment by KathiSchleidt** [comment]
As we cannot identify a clear target for requirement and recommendation, and these terms are not defined within other ISO standards, we propose deleting them from the terms and definitions

**Comment by KathiSchleidt** [comment]
**MB/NC: TMG-[15-26]**
Modifications will be made in accordance with ISO requirements towards definition format as recommended

**Comment by KathiSchleidt** [comment]
**MB/NC: TMG-028 & MB/NC: TMG-029** Fixed

**Comment by sgrellet** [comment]
TMG-018 : Implementation cross-checked

**Comment by sgrellet** [comment]
TMG-019 : Implementation cross-checked

**Comment by sgrellet** [comment]
TMG-020:  Implementation cross-checked

**Comment by sgrellet** [comment]
TMG-021:  Implementation cross-checked

**Comment by sgrellet** [comment]
TMG-024: Implementation cross-checked. This example should not be deleted throughout O&M revisions :)

**Comment by sgrellet** [comment]
MB/NC: TMG-028 & TMG-029: Implementation cross-checked

**Comment by sgrellet** [comment]
TMG-027: Implementation cross-checked

**Comment by sgrellet** [comment]
pending questions before moving fully to "Implementation cross-checked"
- TMG-015: are we sure about 19123 definition ? -> if already checked then "Implementation cross-checked"
- TMG-016 : it looks weid to me that we have one def with 2 different sources. Is this content ok ?
- TMG-022 : suprizing to point to the previous version of the standard to support a term.
	- I would make more sense (to me) to make this reference an internal one
	- It would make even more sense to point to VIM (It's not us defining what a measurand is)
- TMG-025: We miss a source
- TMG-026 : are we sure about 19123 definition ? -> if already checked then "Implementation cross-checked"

**Comment by KathiSchleidt** [comment]
TMG-015: as unclear when 19123-1 will finally come out, I degraded the coverage definition back to the 2005 version - domain replaced with `spatial, temporal or spatiotemporal domain`

TMG-016 : it looks weid to me that we have one def with 2 different sources. Is this content ok ?
KS: the definition is from 19109, the note from 10123, only way I could figure correctly providing this

TMG-022: sorry, if TMG suggests, who am I to think or contradict? ;)

TMG-025: added a source

TMG-026: cut the final note as not in the 19123-2005, and the update still isn't out

**Comment by sgrellet** [comment]
TMG-015 : linked to https://github.com/opengeospatial/om-swg/issues/110 -> ok
 
TMG-016 : indeed this makes sense to do like this

TMG-022 : makes sense. I won't dare :)

TMG-025 : ok

TMG-026 : linked to https://github.com/opengeospatial/om-swg/issues/110 -> ok
