### ISSUE TITLE
Terms and definitions formating

### ISSUE THREAD

**Issue by KathiSchleidt** [opengeospatial/om-swg#98]
MB/NC: TMG-013
Line number: 
Clause/Subclause: 3
Paragraph/Figure/Table: Overall 
Type of comment: ed 
Comments: many of the authoritative source references in the terminology clause are not formatted correctly; some do not have the publication year, or the referenced terminology entry number; use of the word "definition" in the source reference is not correct;
Proposed change: the correct notate for a simple ISO source reference is:[SOURCE: ISO 19xxx:YYYY, 3.xx]ex: [SOURCE: ISO 19136-1:2020, 3.1.8]other formats exist if the notes or examples have been modified, added, or deleted; please see the ISO/IEC Directives, Part 2, Revision 8 2018.

------------------------------------------

MB/NC: TMG-014
Line number: 
Clause/Subclause: 3
Paragraph/Figure/Table: Overall 
Type of comment: ed 
Comments: Terminology entries shall follow ISO/IECDirectives, Part 2, Revision 8, 2018, Clauses16 and 17, and ISO 19104.
Proposed change: Follow ISO/IEC Directives, Part 2, Revision 8,2018, Clauses 16 and 17, and ISO 19104while drafting the terminology entries for the document.

**Comment by ilkkarinne** [comment]
I will ask for a copy of the 19104 (or try to find one) and check what is required there

**Comment by ilkkarinne** [comment]
See [ISO/IEC Directives, Part 2, Revision 8 2018, 16. Terms and definitions](https://www.iso.org/sites/directives/current/part2/index.xhtml#_idTextAnchor196)

**Comment by sgrellet** [comment]
in 3.2.2, Observer 
we  have a NOTE that does not correspond to the NOTE that is in /req/obs-cpt/Observer/Observer-sem
I guess we should align things otherwise it's not a 'NOTE' but a 'Note to entry'

"Note 1 to entry" added for pFOI and uFoI 

3.1.6 - ex-situ slightly edited 

The rest seems ok

**Comment by KathiSchleidt** [comment]
To 3.2.2, Observer and 
- NOTE: a sensor is a type of observer

The bit on Sensor was a bit confused, as we'd originally had it as a class but then removed.
We DO have a note under /req/obs-cpt/Observer/Observer-sem:
-	The Observer is an instance of a sensor, instrument, implementation of an algorithm or a being such as a person.

It may make sense to add the full note (rephrased so not referring to class Observer) to the definition
